### ISSUE TITLE
[Magical Crops 4.0 beta] essences get converted into the same thing

### ISSUE THREAD

**Issue by hvdklauw** [jaquadro/StorageDrawers#100]
Build my own local modpack on curse with storage drawers (1.5.6) and magical crops (4.0.0 beta 3) and all the essences from magical crops get ore dictionaried to the same thing when using the controller with AE. (Using the drawers manually does allow me to put them in as the correct item)

Looking at the ore dictionary names they all have: "accioMaterial" as their ore dictionary names.

How can I fix this?

I've looked at the code but I'm not sure how I would go and add support for this.

**Comment by hvdklauw** [comment]
ok, found the minetweaker support.. doh...

This fixed it for me:

```
mods.storagedrawers.OreDictionaryBlacklist.add("accioMaterial");
```

**Comment by jaquadro** [comment]
The drawer conversion is very smart, but this one can't be discerned from a categorical-type entry.  I might want to blacklist this one by default since it's as bad as a duping bug.

**Comment by hvdklauw** [comment]
Actually, I just discovered that it is only for items in the same tier, so you won't really gain anything with the dupe bug as it's just as easy to get it through normal means (and you need one of the item to begin  with).

Higher tiers are:
"crucioMaterial"
"imperioMaterial"
"zivicioMaterial"
