### ISSUE TITLE
[1.18.1] Crimson/Warped drawers do not have axe as appropriate tool

### ISSUE THREAD

**Issue by DefiantEmer** [jaquadro/StorageDrawers#1006]
Minecraft Version: 1.18.1
Forge Version: 39.1.2
Mod Version: 10.1.1
Single Player

All varieties of both crimson and warped drawers cannot be quickly mined with an axe, as opposed to the other wooden drawers. I noticed they were missing "#minecraft:mineable/axe" when hovering over blocks in F3.

![CrimsonWarped Not Mineable](https://user-images.githubusercontent.com/101599466/158259931-0219b758-9445-4eba-9c54-93a2a1d88597.png)

![Oak Drawer Mineable](https://user-images.githubusercontent.com/101599466/158259966-36123142-7403-47f0-bd3d-dd733fb49f02.png)

**Comment by Quinteger** [comment]
Thanks for reporting. Fixed in https://github.com/jaquadro/StorageDrawers/commit/31891d1b2fb3417cc0d8a13ecc2fdeaa504be2a1.
