### ISSUE TITLE
Server Crash after updating Storage Drawers to 1.5.6

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#101]
Storage Drawer: 1.5.6
Forge: 1403
Pastebin: http://pastebin.com/mYG124zW

Looks like a problem with my Cobblestone compacting drawers, I Have a SFM's program automatically transferring from one to the other to automatically compress up to octuple.
(screenshot coming)

**Comment by jaquadro** [comment]
It kind of looks like some other mod is including the StorageDrawers API and it's conflicting.  Could you try recreating your setup in a new instance with just the StorageDrawers, SFM, ExU, and any other immediately relevant mods present?

**Comment by jaquadro** [comment]
As pointed out in #107, this is a compatibility issue with the HoloInventory mod.  That mod is including an outdated copy of the Storage Drawers API.

**Comment by jaquadro** [comment]
Fixed with latest Holoinventory update, and possibly latest Storage Drawers update.
