### ISSUE TITLE
[1.18.2] Placing compacting drawer corrupted game. looks like render error.

### ISSUE THREAD

**Issue by truehunterethan** [jaquadro/StorageDrawers#1010]
Mod Version: StorageDrawers-1.18.1-10.1.1
Forge Version: 1.18.2-forge-40.0.32

After placing a compacting drawer game crashed and save was corrupted.

[crash-2022-03-31_15.31.42-client.txt](https://github.com/jaquadro/StorageDrawers/files/8393443/crash-2022-03-31_15.31.42-client.txt)

**Comment by Quinteger** [comment]
Most likely this happened due to version mismatch. A 1.18.2 version is available, try it out.
