### ISSUE TITLE
Void upgrade ignoring available slots

### ISSUE THREAD

**Issue by LindaJuffermans** [jaquadro/StorageDrawers#1023]
Steps to reproduce:
- Create a 2x2 drawer, give it a stack downgrade (for testing, upgrades also work) and a void upgrade.
- Assign multiple slots to an item
- Insert (pipe, hopper, etc.) more of the item than fits in a single slot
- The drawer voids additional items rather than using other slots.

![image](https://user-images.githubusercontent.com/31929183/171581584-7b697a1c-0380-4f2e-813a-57c0a52179e9.png)
Additional dirt in the hopper was being sent to the drawer and voided.

StorageDrawers-1.16.3-8.5.2.jar
Minecraft 1.16.5
Forge 36.2.34

**Comment by Jack-McKalling** [comment]
Still an issue in latest version:

SD: storagedrawers-1.20.1-12.0.3
MC: 1.20.1
Forge: 47.3.0

**Comment by jaquadro** [comment]
Fixed in 12.0.4
