### ISSUE TITLE
[1.19] Forge 41.0.94+ has more breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [jaquadro/StorageDrawers#1031]
Forge 41.0.98
StorageDrawers-1.19-11.1.0

[crashlog.txt](https://github.com/jaquadro/StorageDrawers/files/9120698/crash-2022-07-15_22.19.24-fml.txt)

Fix one problem and another 5 spring up.

**Comment by cech12** [comment]
In StorageDrawers-1.19-11.1.2 it should be fixed. :)
