### ISSUE TITLE
odd crash when placing a storage drawer

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawers#106]
client crash report: https://gist.github.com/kreezxil/1cb9a07cb810cf24b309#file-crash-report-client
client fml latest log: https://gist.github.com/kreezxil/1cb9a07cb810cf24b309#file-fml-latest-log-client

**Comment by jaquadro** [comment]
I rolled back 2.1.3 this morning and released the fix in 2.1.4.  It's available on Curse and GitHub.

**Comment by kreezxil** [comment]
Saw it right after I posted. Thanks. Btw, vid upgrade doesn't work.

-----Original Message-----

**Comment by jaquadro** [comment]
vid upgrade?

**Comment by kreezxil** [comment]
Void upgrade

-----Original Message-----

**Comment by kreezxil** [comment]
Ooh boy, I just realized how you programmed it to work. It stores what it is meant to store but then because of the void upgrade instead of slowing the overflow to seek a new drawer it then deletes the excess.

Is that correct?

-----Original Message-----

**Comment by jaquadro** [comment]
Yes, that is the intended purpose of the void upgrade.  It prevents things like cobblestone from filling all the available space in your network.

In the near future it will be even more explicit -- void drawers will receive the highest routing priority
