### ISSUE TITLE
compact drawers crashing? when pipe in items?

### ISSUE THREAD

**Issue by killmetohell** [jaquadro/StorageDrawers#107]
i was trying compacting drawers i haven't tried this on anything else but it seem that anytime an item that was move/pipe in compacting drawer after the first one would crash I only tried this with compress cobblestone from extra utilities. Here's the paste bin http://paste.ee/p/7yrAH its not error log it didn't gave me one. I'm using 1.5.7 version and 1.5.6 also same problem i don't know about older i haven't tried them yet.

**Comment by killmetohell** [comment]
I just recently tried 1.5.5 and its seem to be working fine so i don't know what causing the problem in the later version but it causing the mod to crash.

**Comment by jaquadro** [comment]
Does it crash if you run just vanilla, storage drawers, and extra utilities?

**Comment by killmetohell** [comment]
I don't know i'll try later

**Comment by jaquadro** [comment]
Another person reported this 2 weeks ago but did not answer my request for an isolated test.

ExtraUtilities is in my test environment and I've been able to transfer items with it.  The crash looks like another mod is providing an outdated copy of the Storage Drawers AP, although I don't see likely candidates for conflict in your mod list.  I want to try and rule out that possibility.

**Comment by killmetohell** [comment]
yes it works and i notice i saw the post for it.

**Comment by jaquadro** [comment]
So no crashing with those three?  Then can you either try and determine which mod is causing the conflict, or zip up your entire mods and config directory and upload it somewhere?

**Comment by killmetohell** [comment]
I don't know i'll look know about uploading the entire mods and config directory its from a mod pack other some extra mod i added because how annoying the mod pack was. So i guess i see what mod causes the crash

**Comment by killmetohell** [comment]
I found the cause I think something with holoinventory is causing the crash not sure about resource loader i'll to check that in my mod pack after i disable holoinventory i'll try with just holoinv and storage drawers and some other ulitiles mod like nei.

**Comment by jaquadro** [comment]
Thanks for doing the search.  I downloaded that mod and looking inside the jar.  It has a copy of my API, which is conflicting.  I've never heard of the mod before, so I wasn't aware of any attempted integration.

**Comment by killmetohell** [comment]
resource loader is fine might be due not having anything or something.

**Comment by jaquadro** [comment]
I opened an issue with the holoinventory mod.

**Comment by dries007** [comment]
The issue was fixed by 1933afdf184db47b513842f706bc5aad84b77636, a new build is going up to curse in a minute.

**Comment by dries007** [comment]
Oh and I suggest adding a [@API](https://github.com/Minalien/BlogArchive/blob/master/ForgeTutorials/Spotlight__API_Annotation.md) annotation in your API package info, it will prevent this in the future.

**Comment by jaquadro** [comment]
Fair enough.  My impression was @API and associated @optional was more targeted at implementers of an API interface.  Wasn't aware of the mod-ordering aspect.

Thanks for the fast turnaround.

**Comment by dries007** [comment]
I didn't know much about it either, until I came across that nice tutorial thing.
Np, the build is up on curse now too.

**Comment by ScottKillen** [comment]
@jaquadro The @ Optional annotation is very handy for making soft dependencies on third-party mod code.

**Comment by jaquadro** [comment]
@ScottKillen Definitely, and I leverage that in GardenStuff, and maybe a little here as a consumer.  But I've used it when needing to implement a foreign interface and/or methods with foreign types.  For bits of inline code, it's pretty easy to section that off and still maintain a soft dependency.

Regardless, the package-info is something I've been meaning to do, and now I have a renewed reason to do it.

**Comment by ScottKillen** [comment]
:+1:
