### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by aik0nik** [jaquadro/StorageDrawers#1081]
hiya not sure what the problem is it gave a very generic error message, minecraft is on 1.19.4 and forge is on 45.0.8 if that helps 
this is what came up in the crash report

Failure message: Storage Drawers (storagedrawers) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/client/event/TextureStitchEvent$Pre
	Mod Version: 11.1.2
	Mod Issue URL: https://github.com/jaquadro/StorageDrawers/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.TextureStitchEvent$Pre

**Comment by Artiow** [comment]
There is no StorageDrawers for 1.19.4. Minecraft source code changed and there is no more net/minecraftforge/client/event/TextureStitchEvent$Pre class, but StorageDrawers still use it.

**Comment by aik0nik** [comment]
ohh okok thank you
