### ISSUE TITLE
Missing recipes 

### ISSUE THREAD

**Issue by ScottKillen** [jaquadro/StorageDrawers#109]
Cannot use pack drawers to make controller or compacting drawers. Suggest oredict key and recipe? :grinning:

**Comment by jaquadro** [comment]
I have a mostly-hate relationship with the ore dictionary for categorical entries.  Probably biased as an implementer of unification.

What if I register blocks to the keys "drawerBasic", "drawerBasicFull1" (extrapolate for the other 4 basic types: Full2, Full4, Half2, Half4)?

Register the blocks as wildcards.  Besides the necessity for recipes picking up all the variants, a single wildcard entry registered to a key is enough of a hint to the unifier to blacklist it.

Or maybe I should let the packFactory register method do it on your behalf?

**Comment by ScottKillen** [comment]
I'm a big fan of the packFactory doing it as it allows you to retain some control.

**Comment by ScottKillen** [comment]
The oredict suggestion was meant with sarcasm. It is widely overused.

**Comment by jaquadro** [comment]
Case in point: I thought you were completely serious.  I understand the appeal, but I wish two separate systems had evolved.

**Comment by ScottKillen** [comment]
Sorry about that! :grinning: 

I actually thought about suggesting some kind of custom recipe handler...but then you've got to tweak the NEI interaction...

Were you serious about having packFactory do it?

**Comment by jaquadro** [comment]
I was, and that's true for any approach really.  Especially true if I pursued a custom handler...

I'm using recipe handlers in Garden Stuff for the million-woods problem.  I'll have to take another look at it.

**Comment by ScottKillen** [comment]
Thanks for looking at it!

**Comment by jaquadro** [comment]
Well despite my reservations, I'm fixing this with a single ore dictionary key for now.  Realized my existing recipe registrations are incomplete and the combinatorics are awful.

It will be handled automatically by the registration.  Your flavors should work in all the recipes (template/comp/controllers) after updating to 1.5.8.  Same for the other released packs.

**Comment by ScottKillen** [comment]
Thanks!
