### ISSUE TITLE
fatal crash - regrowth

### ISSUE THREAD

**Issue by sorvance** [jaquadro/StorageDrawers#110]
so in the last 2 days, the server my friends and I host/play on has been having an issue with storage drawers causing clients to be disconnected.
i'll post a pastebin of the crash log, but here's the line that i think is causing the issue:
Caused by: java.lang.NegativeArraySizeException at com.jaquadro.minecraft.storagedrawers.network.ControllerUpdateMessage.fromBytes(ControllerUpdateMessage.java:40)
link to pastebin : http://pastebin.com/TTRXy8rk

**Comment by jaquadro** [comment]
Update the mod if you can.  That network packet doesn't even exist anymore in current builds.  Hopefully, the Regrowth pack is nearing an update.
