### ISSUE TITLE
Interaction with Super Crafting Frame broken

### ISSUE THREAD

**Issue by Intemes** [jaquadro/StorageDrawers#111]
Between Version 1.5.7 to 1.5.8 the Interaction with Super Crafting Frames connected to a Controller Slave must have broken.

With 1.5.8 clicking on a frame connected to a Controller spits out a stack of each of the items used in the Recipe.

Downgraded to 1.5.7 again which fixed the issue.

**Comment by jaquadro** [comment]
When you say spits out a stack, is it a duping bug too?

And do Super crafting frames work if they're attached directly to a drawer?

**Comment by jaquadro** [comment]
Fixed in 1.5.9
