### ISSUE TITLE
Cherry not available as a drawer option

### ISSUE THREAD

**Issue by malice936** [jaquadro/StorageDrawers#1118]
Cherry trees were added to vanilla as of 1.20.x, so cherry drawers should probably be added.

**Comment by Oddlybird** [comment]
Ditto for Mangrove and Bamboo -- they both have vanilla planks, and would be fantastic to have

**Comment by drakray** [comment]
I too would love to see those please :D

**Comment by ItzDogo** [comment]
I too would love to see these drawers be added.

**Comment by DRD2k8** [comment]
This should be resolved on the pull request I made #1136

**Comment by jaquadro** [comment]
These were retroactively added to all versions that supported this wood type (and mangrove/bamboo)
