### ISSUE TITLE
not placeable and craftable

### ISSUE THREAD

**Issue by Lulsx123** [jaquadro/StorageDrawers#1133]
I created a Minecraft server and downloaded the storage drawer mod for 1.20.1. But whenever I try to place them, they always disappear immediately. Does anyone have an idea why?

Please reply.

Kind regards.

**Comment by jaquadro** [comment]
This sounds like it could have been caused by spawn protection if they were trying to be placed very near the server spawn.  I have not seen any problems in general with placing drawers.  Feel free to re-open as new issue if there is still a problem.
