### ISSUE TITLE
Why StorageDrawers 12.6.0 requires The One Probe

### ISSUE THREAD

**Issue by dnk1234567** [jaquadro/StorageDrawers#1141]
I didn't see any dependency requirement about TOP on curseforge.
[crash-2024-08-26_10.32.03-fml.txt](https://github.com/user-attachments/files/16743325/crash-2024-08-26_10.32.03-fml.txt)

**Comment by jaquadro** [comment]
This was a mistake I must have left in the build script, it's not supposed to be a hard dependency

**Comment by jaquadro** [comment]
Should be fixed in new release

**Comment by dnk1234567** [comment]
Thank you very much!
😄👍🏻
