### ISSUE TITLE
EMI Failing to load correctly with Storage Drawers installed (Forge, 1.20.1)

### ISSUE THREAD

**Issue by KooBaby** [jaquadro/StorageDrawers#1143]
Expected behavior: Recipes load and items display on right hand side of screen when inventory is opened

Current behavior:  Text reading "EMI waiting for recipe data from server..." and no items or recipes are ever displayed, load time is infinite.

Modlist and log, as well as screenshots provided below 

[latest.log](https://github.com/user-attachments/files/16775780/latest.log)

Mod list
<img width="976" alt="modlist" src="https://github.com/user-attachments/assets/d0d5b50e-a46d-4d1f-b489-cfb33bdb6dcb">

Current behavior
![Current behavior](https://github.com/user-attachments/assets/8c4bbf26-37e0-46f0-af09-6d59596260bb)

Expected Behavior
![Expected behavior](https://github.com/user-attachments/assets/54f99ef2-7d20-446c-9c9c-e7d581dce6a3)

**Comment by CaptConrad** [comment]
I'm getting this to.

**Comment by jaquadro** [comment]
Was this working okay pre-12.6.0?

**Comment by KooBaby** [comment]
> Was this working okay pre-12.6.0?

it is only this most recent updates that causes this; 12.6.2.
My current band-aid fix for this is just to remain on 12.6.1, where this bug doesn't occur

**Comment by jaquadro** [comment]
This should be fixed now, new builds should appear in a few minutes.

This was a little sneaky because it wasn't surfacing with just JEI present.
