### ISSUE TITLE
1.21.1 Storage Drawers not working at all

### ISSUE THREAD

**Issue by DagoMuc** [jaquadro/StorageDrawers#1145]
Hi jaquadro,
first of all thank you for making this mod.
Our family likes to tidy things up and this is the right mod for it.

### Versions Used:
Minecraft   1.21.1
Forge   52.0.9
Storage Drawers   13.2.0

### Problem Description:
Up until now, we used only the regular storage drawers which work like a charm.
We now started to use the compacting drawers and they don't work at all.
As we are using multiple mods to test, I tried to remove mod by mod to check when it works again.
But sadly the compacting drawers are not even working when the only mod available: 
![Installed](https://github.com/user-attachments/assets/e94e2b3c-1c40-432b-a273-06f228432498)

I also tried to create a new creative world with only the StorageDrawers mod as only available and I got the same result:
![In-Game-Screenshot](https://github.com/user-attachments/assets/7fde1449-971e-4f04-abc2-61043e1f99a3)

**Comment by jaquadro** [comment]
This got fixed in the NeoForge version a bit ago but got missed for Forge.  Should be fixed in the latest Forge release now.
