### ISSUE TITLE
Conection closed to server if i use StorageDrawers 

### ISSUE THREAD

**Issue by Pinhead1104** [jaquadro/StorageDrawers#1148]
I have an errormessage if i install StorageDrawers and connect to server. 

io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:container_set_content'
[latestmit drawer.log](https://github.com/user-attachments/files/16932381/latestmit.drawer.log)

**Comment by jaquadro** [comment]
That looks like a server log and I don't see anything specific in there.  Do you have your client log from when you failed to connect?

**Comment by Pinhead1104** [comment]
Here is the client log
[disconnect-2024-09-09_16.39.00-client.txt](https://github.com/user-attachments/files/16964393/disconnect-2024-09-09_16.39.00-client.txt)

**Comment by jaquadro** [comment]
I'm not sure there is anything I can spot to help here.  Are the versions of mods the same between client and server?  

There's some evidence in both logs of mixed up IDs, and specifically related to network it looks like the game is trying to decode one packet it received as some other packet type and the data is wildly mismatched and crashes.

**Comment by Pinhead1104** [comment]
Yes the versions of mods on client and server are the same

**Comment by jaquadro** [comment]
Been a little while since this was reported, but the underlying issue may be resolved as of Forge release 52.0.17, which fixes desyncs in the data component registry between client and server.
