### ISSUE TITLE
Empty Drawers pulled out with the puller don't retain upgrade size information/aren't accepted into upgraded drawer blocks

### ISSUE THREAD

**Issue by RumekFuria** [jaquadro/StorageDrawers#1150]
[Neoforge 1.20.1-12.6.4]

As the title says, if one pulls out an empty drawer from a unit that has any kind of size upgrade in it, the resulting empty drawer item defaults itself to a stock drawer with 32 stacks, and thus is no longer able to be inserted into the unit it just has been pulled out from due to size mismatch

Additional observations I can provide are:

- If a drawer block does support 32 stack size with upgrades, such as 2x upgrade on a 1x1 half drawer, it will accept the empty drawer item

- this doesn't affect un-upgraded drawer blocks, as, for example, half 2x2 without any size modifications will still provide and accept the same empty drawer item just fine, despite it's slot size being only 4

**Comment by jaquadro** [comment]
The 32 stack default size does give a little bit of freebie room at the bottom end as you observed, but ultimately felt that was acceptable even when the capacity limits are generally enforced.

I'll look into the empty drawer bug though

**Comment by jaquadro** [comment]
This should be fixed in latest release, 12.6.6
