### ISSUE TITLE
Can't put back empty detached drawer

### ISSUE THREAD

**Issue by SkaldBoy** [jaquadro/StorageDrawers#1151]
Tried moving an empty detached drawer from an upgraded (1 Tier V) 2x2 Drawer. But can't place them back as they indicate coming from an unupgraded 2x2 Drawer

**Comment by jaquadro** [comment]
Have you tried updating to the latest version?  (Will only fix newly pulled drawers, not ones you've already removed)

**Comment by SkaldBoy** [comment]
Thanks, it solved the problem, sorry, the update wasn't out when I started my session yesterday.
But I just found another issue, you can put an upgraded detached drawer in a lower upgraded drawer but not the other way around so I now have a detached drawer still in hand that I can't put anywhere.

**Comment by jaquadro** [comment]
You can upgrade it by combining it with storage upgrades on a crafting table.  Since you can craft new empty ones that's how you'd upgrade them to fit.  It's more of a safety net in case you lost or destroyed one.

**Comment by jaquadro** [comment]
Will assume this is fixed.  Worth noting, I ended up changing the default setting to not enforce the stack capacity check.  That won't change for any configs that have already been written, but something you can change at any time.
