### ISSUE TITLE
personal key

### ISSUE THREAD

**Issue by merko83** [jaquadro/StorageDrawers#1152]
Will personal keys be available again? I use 1.20.1 and they are not there. thank you

**Comment by jaquadro** [comment]
It might get added back as other missing 1.12 features trickle back, but if it does it's important to note its major limitations:

- It can't protect the block itself, e.g. from another player destroying it
- Locking is to a single player

**Comment by merko83** [comment]
okay great! Well, we are waiting for future updates. thank you artist

**Comment by jaquadro** [comment]
Good news, the personal key is available again in 12.7.1.  If you have CoFH Core installed, you can also use the CoFH variant which uses your CoFH friends list for determining access.

I'm not equipped to fully test this in MP right now, so please try it out and open a new issue if you encounter any problems with it.
