### ISSUE TITLE
[Suggestion] Add config to disallow auto I/O on controllers

### ISSUE THREAD

**Issue by MCTian-mi** [jaquadro/StorageDrawers#1153]
as the title says

btw I can draft a PR to 1.12.2 if you still accept PRs for this version.

**Comment by jaquadro** [comment]
There is an existing pair of config entries, enableSidedInput and enableSidedOutput, though at least on 1.20 it looks like they are not hooked up to anything.  Maybe that is also true on 1.12, but that could be something to look at.

I am accepting PRs on 1.12

**Comment by jaquadro** [comment]
So for clarification, did you intend for this to ONLY apply to the controller itself, or also to its connected IO (slave) blocks?

**Comment by MCTian-mi** [comment]
> So for clarification, did you intend for this to ONLY apply to the controller itself, or also to its connected IO (slave) blocks?

ah I thought disabling slave IO would be pointless since they can't be interacted manually
and it's no different to just disable them anyway (ig there is a config for this)

**Comment by jaquadro** [comment]
This is shipped now
