### ISSUE TITLE
Maxrange of Drawer Controller

### ISSUE THREAD

**Issue by Illiyanna** [jaquadro/StorageDrawers#1155]
Hey there, 

not sure if my issue a bug or just a limitation of your mod/ minecraft.

When I have interconnected my storage with your mod (put a controller slave drawer every 10 blocks and used trim in between.) I somehow can't input blocks at one end and have them placed in a drawer on the other end.

I've already checked multiple times if the connection between the drawer and my controller is interupted yet this doesn't look like the issue at all.  I'm trying to send blocks from 162 145 277 to 157 116 209.

Is there some max range of Drawer Controllers I should be aware about or could something else be my issue?

I'd love to have someones input on that.

**Comment by jaquadro** [comment]
Slaves don't extend range.  The controller has an absolute maximum range, which can be set in the mod config up to 75 blocks radius.  It should be 50 by default.  The upper bound of 75 has more to do with chunk loading considerations.

Keep an eye out for some updates in the near future for a wireless connection option and possibly longer supported ranges (barring, again, potential chunk loading considerations)

**Comment by Illiyanna** [comment]
Alright thank you. I'll have a look at that.

**Comment by Illiyanna** [comment]
Solved
