### ISSUE TITLE
[BUG] Missing GUI texture in Compacting Drawer (3 tier) - StorageDrawers-1.20.1-12.7.1

### ISSUE THREAD

**Issue by muggleorwizard** [jaquadro/StorageDrawers#1156]
The 3-tier compacting drawer is missing its GUI texture when accessing the inventory via shift-click. 
![3-tier](https://github.com/user-attachments/assets/24752748-b1bb-40df-b22c-d3b28d5fb513)

The 2-tier texture is working fine.
![2-tier](https://github.com/user-attachments/assets/9aa8786a-cbf1-4a1f-a790-9082166fb607)

Bug is on latest version on 1.20.1 as of 9/26/24: StorageDrawers-1.20.1-12.7.1

**Comment by jaquadro** [comment]
Do you have a custom data pack installed for Storage Drawers textures?

**Comment by jaquadro** [comment]
Nevermind this is something I forgot I fixed in my local build already.  This should be fixed in the new 12.7.2 release

**Comment by muggleorwizard** [comment]
Thanks! And, no, I did not have a custom data pack.
