### ISSUE TITLE
Can the fabric version not depend on the Forge Config API Port?

### ISSUE THREAD

**Issue by swe3per** [jaquadro/StorageDrawers#1160]
The compatibility of Forge Config API Port in higher versions is not good enough, which causes the server to be unable to shut down normally. Can subsequent versions consider not relying on this module? 
Such a powerful and easy-to-use drawer mod finally supports fabric. I don’t want the quality to be affected by the dependent mods. :)

**Comment by jaquadro** [comment]
It can probably be made optional with the obvious caveat that you will not get any config support available for the mod.  In the interim you can of course step back one version, as the only change was the reintroduction of config support

**Comment by swe3per** [comment]
This is a good idea. 
If it is installed on the server, is it also impossible to modify the configuration by modifying the toml file?

**Comment by jaquadro** [comment]
If there's no forge config API port present, then there are no toml files to configure.  The mod loads static defaults internally.  Forge config API port seemed like the obvious solution to carry over config support but if there's other solutions in common use that aren't too hard to adapt I could look into them.

**Comment by swe3per** [comment]
Thanks for your help. 
I'm sorry that I can only communicate with you from the perspective of a player/OP. 
When choosing a MOD, we often feel anxious because of powerful but unstable dependent MOD. 
I can understand the convenience these dependencies provide to developers, so I put forward this immature suggestion. 
Thank you very much for your understanding.

**Comment by jaquadro** [comment]
I published 13.7.2, which should make the dependency optional.  No ETA on when configuration might be available by a different method.

**Comment by swe3per** [comment]
Thanks a lot my bro!
