### ISSUE TITLE
[fabric] Incompatibility with refined storage2 mod causing lost items

### ISSUE THREAD

**Issue by swe3per** [jaquadro/StorageDrawers#1161]
Connect the RS terminal to the drawer controller externally, place the coal block in the 2x or 3x compression drawer, connect the output cable to the furnace configuration to output the coal, and when the furnace coal is filled to 64, all items in the compression drawer will be emptied.

![RS_bug](https://github.com/user-attachments/assets/56e62044-f36a-444b-a8cf-ee590c33767f)

Minecraft 1.21.1
refinedstorage-fabric-2.0.0-milestone.4.7.jar
Storage Drawers-fabric-1.21-13.7.1/13.7.2

**Comment by jaquadro** [comment]
Dropping this here for reference, it is most likely an SD an issue
https://github.com/refinedmods/refinedstorage2/issues/699

**Comment by jaquadro** [comment]
This should be fixed in 13.7.4.  Feel free to reopen the issue if you still encounter problems with interop.
