### ISSUE TITLE
1.21.1 Trims and draw controller (and IO) dont drop

### ISSUE THREAD

**Issue by Olarius405** [jaquadro/StorageDrawers#1166]
Hi StorageDrawersteam, 

i love your mod so long now and now i made a account in github in hoping of getting this bug fixed - at least it feels like a bug to me. I found out that the storagedrawer controller, the controller_io and the trims dont drop if i want to change my storage system and rebuild it. Is this intentional with the implementation of this mod or is this a bug that hasn't been noticed yet?

How to reproduce: 

demolish trims, controller and controller_io, even with silk touch and its gone forever. 

Hope you can help me :) 

Edit: I play with neoforge. maybe this is the reason. Earlier i played in forge and there was everytime a dropping storage controller

**Comment by Olarius405** [comment]
oooh - i upgraded to the last version 13.8.0 and suddenly it works. Sorry for disturbing your work :) 

Then i only wanted to ask one thing: If i build trims over a chest, the chest is not openable. If i build a wooden storage drawer, i can open it. Is this intentional? :) 

Thanks for your great work. Best storage system ever <3

**Comment by jaquadro** [comment]
Yeah that one was very recently fixed.

Trims are solid blocks, but drawers aren't.  That's why Minecraft treats it that way.
