### ISSUE TITLE
Thaumcraft Aspect Texture flicker

### ISSUE THREAD

**Issue by KennyBurch** [jaquadro/StorageDrawers#117]
As the title states, I seem to get texture flickering of the thaumcraft aspects on the latest update.

**Comment by jaquadro** [comment]
Forgot about even testing them... the item/block labels are flicker-free though?

**Comment by KennyBurch** [comment]
Aye, all the items themself look great.

**Comment by jaquadro** [comment]
Fixed in 1.5.11.
