### ISSUE TITLE
Ore dictionary support for chests

### ISSUE THREAD

**Issue by Adaptivity** [jaquadro/StorageDrawers#118]
@ganymedes01's Gany's Surface mod adds new variants of chests based on wood (it's the same chests as vanilla but with textures based on actual wood). @jaquadro can you convert your recipes to use ore dictionary name "chestWood" for chests? How it was added to Tinkers Construct: https://github.com/SlimeKnights/TinkersConstruct/commit/54d8bbcc028e504d0d2717473f0876328407200d Thanks in advance.

**Comment by ganymedes01** [comment]
Done :3

**Comment by Adaptivity** [comment]
Thanks again :3

**Comment by jaquadro** [comment]
That was fast.  Thanks for the PR!
