### ISSUE TITLE
Custom compacting rules for 1.21

### ISSUE THREAD

**Issue by Octelly** [jaquadro/StorageDrawers#1185]
Used to being able to add custom rules through the `.cfg` file which is nowhere to be found.
`13.8.3` on Minecraft `1.21.1` with NeoForge `21.1.80`

**Comment by jaquadro** [comment]
Might have been accidentally lost when converting the mod to multi-loader.  I see where it's commented out, so I can take a look

**Comment by jaquadro** [comment]
This should be available now in the common config
