### ISSUE TITLE
[Fabric 1.20.1] EVERY single interaction with drawers gets logged

### ISSUE THREAD

**Issue by StuntHacks** [jaquadro/StorageDrawers#1190]
This mod is great, However, right now it currently logs EVERY single interaction anyone has with a drawer to the output:
![image](https://github.com/user-attachments/assets/bce60cfb-ff94-4e46-b97b-5a5e765c089e)
This is probably a leftover from development, but it's kind of a pain lol. I haven't found any configs to disable this.

**Comment by jaquadro** [comment]
Hi, I tried poking around for all the places this could be happening.  The one spot I think this is coming from, has a check for the "debugTrace" config item.  Check that in the config.

It looks like I ALSO accidentally made that setting default-on (facepalm), so I'll need to change that and probably remove this specific log item too.

**Comment by jaquadro** [comment]
This should be fixed across versions now
