### ISSUE TITLE
Natura & BIOMESOP Drawers not recipe compatible

### ISSUE THREAD

**Issue by jburrows82** [jaquadro/StorageDrawers#121]
Crafting Compacting Drawers with drawers from Natura or Biomes o' Plenty wood addon for the drawer ingredient isn't possible. Oredict difference maybe? Haven't tested the other wood addon packs, but they're probably broken too. 

version: 1.5.11 

Not sure if 1.5.12 will correct the issue or not, if so please close out this ticket.

**Comment by jaquadro** [comment]
They're not using the latest API that would have auto-registered them.  I'll need to do a round of updates on the packs soon.

You can get this working immediately by registering those block IDs under the "drawerBasic" ore dictionary key in something like MineTweaker.  Ids are:

StorageDrawersBop:fullDrawers1, StorageDrawersBop:fullDrawers2, StorageDrawersBop:fullDrawers4, StorageDrawersBop:halfDrawers2, StorageDrawersBop:halfDrawers4
StorageDrawersNatura:fullDrawers1, StorageDrawersNatura:fullDrawers2, StorageDrawersNatura:fullDrawers4, StorageDrawersNatura:halfDrawers2, StorageDrawersNatura:halfDrawers4

**Comment by Zyin055** [comment]
Here is a minetweaker script that adds the BoP drawers to the oredict. This allows you to do things like craft the drawer controller using these new drawers. You can easily add in more lines that add in support for the Natura ones as well.

val oredict_drawerBasic = <ore:drawerBasic>;

val bopFullDrawer2 = <StorageDrawersBop:fullDrawers2:*>;
val bopFullDrawer4 = <StorageDrawersBop:fullDrawers4:*>;
val bopHalfDrawer2 = <StorageDrawersBop:halfDrawers2:*>;
val bopHalfDrawer4 = <StorageDrawersBop:halfDrawers4:*>;

oredict_drawerBasic.add(bopFullDrawer2);
oredict_drawerBasic.add(bopFullDrawer4);
oredict_drawerBasic.add(bopHalfDrawer2);
oredict_drawerBasic.add(bopHalfDrawer4);

**Comment by jaquadro** [comment]
I've just released a round of updates to all the addon packs.  They can now be used in recipes for anything requiring drawers.
