### ISSUE TITLE
Agrarian Skies 2: Copper ingots + nuggets have the same count in AE

### ISSUE THREAD

**Issue by eslachance** [jaquadro/StorageDrawers#122]
Setup:
 - Compacting Drawers
 - Drawer Controller
 - Storage Bus
 - Cables to AE network (which has drives, molecular assembler and that's pretty much it)

Essentially, the problem is that the number of copper nuggets and ingots is exactly the same (there is 868 ingots, there should be 7812 nuggest but there's only 868).

The rest of the drawers work fine: Tin, Iron, Lead, Gold, Silver, they all display nuggets=ingots*9. All of them are Thermal Expansion (they were all done through a smeltery). Only Copper has this issue.

It's not just a visual bug: crafting ingots out of nuggets basically divides the number of ingots by 9, as if the nuggets WERE ingots. (or vice versa, you get the point). 

Because this is AS2 and itt changes recipes, I'm going to take a wild guess maybe that maybe minetweaker maaaay cause this and I'm reporting it here even though it's an AS issue? Just want to confirm first though. Will provide any log/config/debug if required.

**Comment by jaquadro** [comment]
The issue was reported a few days ago.  I introduced the bug when I tried to make compacting drawers smarter about what mod they pick materials from.  It's been fixed in 1.5.12, so you can update the mod out-of-band to resolve it now.
