### ISSUE TITLE
Compatibility with Artifice (OreDictionary)

### ISSUE THREAD

**Issue by SDXC** [jaquadro/StorageDrawers#128]
The mod "Artifice" adds several decorative stone blocks (like basalt and marble) to the world. For every block type (basalt, marble, etc.) there are the equivalent ore versions of these block types (basalt iron ore, marble gold ore, etc.).

There is one problem with the compatibility between StorageDrawers and Artifice. The OreDictionary-Conversion by adding identical items/blocks from different mods to the drawers doesn't work anymore. For example copper ore from IC2 and SimpleOres2 (both with the same OreDict name "oreCopper") will not be converted anymore when Artifice is installed. I can add the ore of one mod to the drawer, the other will not be put into the drawer like it normally does when conversion is enabled.

Could you look into it when you have the time, please?

EDIT: Just checked with other items. Conversion of ingots and blocks works. Just the ores and some other blocks don't convert.

**Comment by jaquadro** [comment]
It's because Artifice adds several unique versions of the same block, and the general rule for that situation is to not allow conversion on that key.

You can whitelist the key through MineTweaker (look through the past few issues, you should find some sample scripts).

**Comment by SDXC** [comment]
Thank you really much.
It worked by adding the following line in my MineTweaker script:

mods.storagedrawers.OreDictionaryWhitelist.add("oreCopper");
