### ISSUE TITLE
Compacting drawer does not recognize ic2 scrap

### ISSUE THREAD

**Issue by robotbrain** [jaquadro/StorageDrawers#129]
IC2 scrap has a 3x3 full recipe to convert to a scrap box, but when scrap is placed in a compacting drawer it occupies the top space. This is probablty due to IC2's custom crafting handler

**Comment by robotbrain** [comment]
i just chatted with player, and scrap hano unpacking recipe, so that may be the issue

**Comment by jaquadro** [comment]
Yeah, if there is no uncrafting recipe back into 9 scrap, then it won't be allowed to compact.  That's by design, but you can add the recipe yourself via MineTweaker, or register the conversions for Storage Drawers in MineTweaker.  There's some example scripts somewhere in the past few issues.

**Comment by robotbrain** [comment]
thanks!
