### ISSUE TITLE
Font size in GUI is too small for Unicode

### ISSUE THREAD

**Issue by oldjunyi** [jaquadro/StorageDrawers#130]
Tested under 1600 x 900 Fullscreen, GUI Scale: Large (same as auto)
The font of itemstack size is too small:
![fontissue](https://cloud.githubusercontent.com/assets/641817/9288492/968a6862-437b-11e5-8da9-9f302f5cc5a5.png)

**Comment by jaquadro** [comment]
I had no idea a separate font existed at all.  Should be more readable in the next version.

**Comment by jaquadro** [comment]
Fixed in 1.5.14
