### ISSUE TITLE
Compacting Drawer, Refined Relocation issue

### ISSUE THREAD

**Issue by minyman60** [jaquadro/StorageDrawers#132]
Hey, Unsure if this is a bug.

Noticed the Sorting Compacting Drawer which uses Refined relocation's sorting with SD's drawers cant be crafted. I don't know if this is SDs responsibility but the recipe uses the item in question to craft its self, this making it unobtainable. 

The standard recipe should be a Compacting Drawer with 4 gold nuggets in the corners of the grid crafts 1 Sorting Compacting Drawer.
The current recipe is a Sorting Compacting Drawer with 4 gold nuggets in the corners of the grid crafts 1 Sorting Compacting Drawer.

Thanks lads.

Min / Adam

**Comment by jaquadro** [comment]
This was fixed in 1.5.14.  You can also craft the standalone sorting upgrade, and apply that to an already-placed compacting drawer, so it's a good workaround if you're stuck on a pack.

**Comment by minyman60** [comment]
Thanks a ton, sorry to have reported an older issue.
