### ISSUE TITLE
Drawer Textures incorrect type and placement 

### ISSUE THREAD

**Issue by nexela** [jaquadro/StorageDrawers#133]
Not sure if this is a bug on your end or from forge.
Storage Drawers 1.8-2.1.8 Chameleon 1.8-0.10
Forge 1.8-11.14.3.1499+

Forge versions 1499 and up only place drawers with the front texture facing east. and only places them in a dark oak color.  You can still interact with the drawers correctly.

From the forge changelog Build 1.8-11.14.3.1499:
	glstillman: Fixed a bug with ExtendedBlockStates containing at least one IProperty and one IUnlistedProperty not allowing blocks to be placed.

Forge 1499 and up
![2015-08-25_19 49 33](https://cloud.githubusercontent.com/assets/13972192/9482614/e5735d0e-4b63-11e5-9096-0ff1d7c320ea.png)

Forge up to 1498
![2015-08-25_19 55 22](https://cloud.githubusercontent.com/assets/13972192/9482616/e856ce98-4b63-11e5-8a37-f38861b19555.png)

**Comment by jaquadro** [comment]
I don't understand why the particular line breaking my mod was added in that PR.  However, it looks like I can return my data directly in getActualState instead of returning it in an extended state, so I can work around that.

Fixed in 2.1.9.
