### ISSUE TITLE
Waila Integration

### ISSUE THREAD

**Issue by geech** [jaquadro/StorageDrawers#137]
Is there a way to get integration for Waila for how many upgrade slots are left in the barrel much like Jabba?  If there already is integration like this, and I'm just being a noob, feel free to troll.

**Comment by jaquadro** [comment]
Well, you can shift+right-click with empty hand to pull up the GUI, which will show you how many slots are used and what's using them.

**Comment by geech** [comment]
Fair enough.  I remembered this about 2 hours after I posted this suggestion.
