### ISSUE TITLE
Gregtech ingot not rendering in Drawers

### ISSUE THREAD

**Issue by dkalnins** [jaquadro/StorageDrawers#138]
![2015-09-09_14 29 50](https://cloud.githubusercontent.com/assets/3414804/9753407/9700f80a-56ff-11e5-9c2a-49758c6d145a.png)

Playing FTB Infitech 2 v3.1.7 with Storage Drawers dropped in with no changes to config files. Storage Drawers version StorageDrawers-1.7.10-1.6.0

Gregtech version gregtech_1.7.10-5.08.27

**Comment by Kehaan** [comment]
I am having the same issue. Using  gregtech_1.7.10-5.08.29 and StorageDrawers-1.7.10-1.6.2

**Comment by jaquadro** [comment]
Fixed in dev, and release will be out within a couple days.  Sorry this one got neglected for so long.

**Comment by jaquadro** [comment]
Fixed in 1.6.3.
