### ISSUE TITLE
Recipes do not work for some Biomes O'Plenty drawers.

### ISSUE THREAD

**Issue by IdleMuse** [jaquadro/StorageDrawers#140]
I've noticed a bug on my server where some of the Biomes O'Plenty recipes seem to be incorrectly functioning (using the BoP pack, obviously). Notably, shallow Willow and Redwood Drawers both seem to either not work at all (halfdrawers2), or give me Oak drawers (fulldrawers4) instead (halfdrawers4). The recipes appear correctly in NEI but do not function on a crafting bench.

Fixed with Minetweaker for now, can post script if it'd help.

**Comment by jaquadro** [comment]
Should be fixed in 1.6.2.  The fallback recipes (all planks could make oak drawers if the pack wasn't present) were messed up and taking higher precedence on your server.
