### ISSUE TITLE
Another compatibility issue with logistics pipes. 

### ISSUE THREAD

**Issue by Nagapito** [jaquadro/StorageDrawers#141]
Besides the polymorphic problem, when a drawer has a void upgrade and is full, LP does not try to place items inside the drawer. 

Maybe it is seeing the drawer with zero space available which should be an exception when a void upgrade is installed...

**Comment by 1n5aN1aC** [comment]
Same issue :/

If the drawers / controller could advertise themselves as still having space when they are full and have a void upgrade, then pipe systems would see them as a valid destination, and route the items to it, which would be a very nice feature.

**Comment by 1n5aN1aC** [comment]
I submitted a pull request to Logistics Pipes that was just Merged into it, that fixes this.
(https://github.com/RS485/LogisticsPipes/pull/833)

So this little interaction issue should be fixed int he latest Dev version.  Try it out and tell me if it hasn't!

**Comment by 1n5aN1aC** [comment]
The implementation / fix for this issue is now in the branch that everyone downloads from curse.

With over 26,000 downloads since that patch, I think it's safe to say that it is stable and implemented.  :smile:

**Comment by jaquadro** [comment]
Thanks @1n5aN1aC for improving the LP compatibility on both projects.  

LP is something that's difficult for me to look at because it's not a mod I normally play with and I don't understand how to put interesting systems together.
