### ISSUE TITLE
Recipes do not work for some Erebus drawers

### ISSUE THREAD

**Issue by IdleMuse** [jaquadro/StorageDrawers#145]
Exactly the same issue as https://github.com/jaquadro/StorageDrawers/issues/140 but for some drawers with Erebus woods - specifically Scorched Wood. I know that the thin scorched drawers aren't craftable normally until The Erebus implements Scorched Slabs (https://github.com/ganymedes01/TheErebus/issues/325), but is that also preventing full-thickness drawers from working correctly?

https://www.dropbox.com/s/dd2za5xgpioln8y/Screenshot%202015-10-08%2021.52.50.png

(This is with StorageDrawers-1.7.10-1.6.2 and StorageDrawers-Erebus-1.7.10-1.0.2)

**Comment by jaquadro** [comment]
The scorched and varnished types were using the wrong meta value.  This is now fixed in 1.0.3 of the Erebus pack.
