### ISSUE TITLE
Crash while looking up item in NEI

### ISSUE THREAD

**Issue by ugrashrath** [jaquadro/StorageDrawers#146]
I was playing the Regrowth modpack on the curse launcher, when I had a crash. Report here: https://gist.github.com/ugrashrath/0573198ebb0114a204b4

After the crash, I'm unable to open my world at all.

**Comment by jaquadro** [comment]
Try updating to 1.6.2 of the mod.  That released contained extra checks to prevent this.

The item that you inserted into your drawer that is triggering the crash will not render, however.

**Comment by ugrashrath** [comment]
Hmm, well updating the file seems to have worked. I'm not sure what item was causing the issue as every drawer that I put items does show the picture. I believe it's solved then!

**Comment by jaquadro** [comment]
I guess it's possible that it could have partially rendered before throwing.  Anyway, good to hear it's not crashing with latest.
