### ISSUE TITLE
Recipes do not work for Forestry 4

### ISSUE THREAD

**Issue by Rukachan** [jaquadro/StorageDrawers#147]
forestry_1.7.10-4.0.9.38
StorageDrawers-Forestry-1.7.10-1.0.3
StorageDrawers-1.7.10-1.6.2

The drawers are not craftable nor their recipes appear in NEI.
They do appear in the creative tabs and NEI and they do seem to work properly when placed in creative mode.

**Comment by jaquadro** [comment]
Do the recipes work if you turn off the "fallback recipes" in the mod config?

Do you know if you're running any mods that would re-sort the recipe list?

**Comment by Rukachan** [comment]
The recipes do not work if I turn off the fallback recipes.
I am not running any mods that would re-sort the recipe list. (NEI does not belong in this kind of mods, right? I also tried a game with only forestry, StorageDrawers-Forestry, StorageDrawers and NEI but nothing changes)

I should also mention that I am talking only about the recipes added by StorageDrawers-Forestry and that the problem still exists under forestry_1.7.10-3.6.11.2.

**Comment by jaquadro** [comment]
The forestry pack did turn out to have a bug in its recipes.  This is now fixed in the 1.0.4 release of the Forestry pack, up on Curse.

I got confused while testing the fix, because I did not know Forestry also had fireproof-versions of planks.  These are now valid in recipes as well.
