### ISSUE TITLE
Erebus recipes do not seem to work [Erebus add-on]

### ISSUE THREAD

**Issue by Dylan4ever** [jaquadro/StorageDrawers#149]
The woods native to the Erebus all craft into the ''Oak'' variant, despite them having their own. Seems OreDict or something is taking higher priority than the ''natives'' themselves.

**Comment by Dylan4ever** [comment]
It might be a fault of the Erebus but it doesn't seem to be that way. Sorry if i'm just dumb.

**Comment by jaquadro** [comment]
Assuming you're on the latest version, the fallback recipes are registered with lower priority than the native recipes.  It's possible another mod could be resorting the recipe list.

Does everything craft normally if you disable the fallback recipes in the config?

**Comment by Dylan4ever** [comment]
I had not seen nor tried this. Thank you, going to check it out right now.

**Comment by jaquadro** [comment]
I tested the recipes in my dev environment and they work fine.  Are you playing on a public pack?  This is almost definitely related to other mods.

**Comment by jaquadro** [comment]
The scorched and varnished varieties were bugged and would always craft oak drawers.  That's fixed in 1.0.3.  For anything else, I need a pack.

**Comment by jaquadro** [comment]
Is this still an issue with the latest SD and pack version?
