### ISSUE TITLE
[ENHANCEMENT] Add a modern-themed texture pack

### ISSUE THREAD

**Issue by Haggle1996** [jaquadro/StorageDrawers#150]
A techno- or modern-themed texture pack would be an awesome addition, so that your mod would look just at home on a space station, as it would in a treehouse. :)

**Comment by jaquadro** [comment]
There is a very old feature request for a "furniture paneler"-esque option.  I have a partly implemented prototype of it.  I think it would cover this case by letting you use metal blocks or some other interesting textured blocks.

As with wood however, a dedicated texture pack may give a more refined appearance.  I don't plan on making such a pack, but it could be created by someone as an addon mod fairly easy.

**Comment by jaquadro** [comment]
"Framed Drawers" are a feature as of 1.9.0 release, and may suit your needs for themed blocks.

**Comment by Haggle1996** [comment]
Awesome! Thank you!
