### ISSUE TITLE
[Feature Request] Deep Storage Upgrade

### ISSUE THREAD

**Issue by Silly511** [jaquadro/StorageDrawers#151]
Allow the drawer you put it on to store an infinite number of items. The upgrade's crafting recipe would obviously be very expensive.

**Comment by jaquadro** [comment]
I won't add an upgrade with a recipe, but I am considering a creative/infinity upgrade.  Then you could MineTweak your own recipe with a cost you deem appropriate.

**Comment by jaquadro** [comment]
I've added a "Creative Storage Upgrade" in 1.7.10, which will give a drawer infinite (well, 2.17 billion) capacity.  You'll have to invent your own suitable recipe via MineTweaker or similar.
