### ISSUE TITLE
Flint reappearing in inventory after double clicking storage drawer.

### ISSUE THREAD

**Issue by rckymtnrfc** [jaquadro/StorageDrawers#155]
When I have flint in my inventory and double click on the storage drawer it appears to enter the drawer but upon opening my inventory, it reappears.  If I'm holding the flint in my hand when double clicking the drawer, the flint does not reappear in my inventory.

All other items that are in my inventory go into their correct drawer and do not reappear in my inventory later.  

I'm assuming it's a sync issues as this is on a server.  Just not sure why only flint is effected.

**Comment by jaquadro** [comment]
I can't really think of any reason for this, and as expected it doesn't reproduce in my environment.  There isn't anything special about flint.

**Comment by rckymtnrfc** [comment]
I think it may have just been a server sync issue.  I'm not sure why it was only effecting flint.

Thanks!
