### ISSUE TITLE
(Erebus Pack) Compact versions of drawers have no recipe

### ISSUE THREAD

**Issue by xeronut** [jaquadro/StorageDrawers#156]
As title.  All other drawers in Erebus Pack have recipes, as do compact drawers in vanilla SD, Natura and Misc Packs (the ones I specifically have installed, others untested).  I'm on 1.7.10 Forge 1492 using Storage Drawers 1.6.2, Erebus Pack 1.0.3, Erebus 0.3a.   Thanks for your time!

**Comment by jaquadro** [comment]
Should be fixed in the latest Erebus pack on Curse
