### ISSUE TITLE
[suggestion] MrCrayfish's Key Mod in 1.8

### ISSUE THREAD

**Issue by InkDragon** [jaquadro/StorageDrawers#159]
MrCrayfish's Key Mod
http://www.mrcrayfish.com/mods.php?id=ckm

uses minecraft's in built lock system to allow players to lock storage items preventing players without the key from accessing the block.

Would be useful for multiplayer environments

**Comment by Royal-Jelly** [comment]
I second this, it would be a welcomed feature i would use often

**Comment by jaquadro** [comment]
Support for the ILockableContainer API is finally implemented for 1.8.9 and 1.9.4+.  But since this support doesn't extend back to 1.8 and the Key mod appears to be discontinued in 1.8.9+, it's a moot point.
