### ISSUE TITLE
[enhancement] Add support for Chiseled Stone Bricks in Compacting Drawers

### ISSUE THREAD

**Issue by victicdin** [jaquadro/StorageDrawers#161]
I'm coming from Thaumcraft, which has a fair amount of use out of these blocks as basic alchemy ingredients early on. Unfortunately they have two different recipes for 1.7.10 and 1.8, [Stone -> Stone Bricks -> Chiseled Stone Bricks] and [Stone Brick -> Stone Brick Slabs -> Chiseled Stone Bricks].

Being able to throw a few Chiseled Stone in and then insert stacks of Stone or Stone bricks would be a good time saver, much like the ore/ingot/compressed forms. I think it's quite similar, but it's up to you in the end if and how to support it.

**Comment by jaquadro** [comment]
It's not something I will add by default, but I think you can make this happen with the existing MineTweaker support for compacting tiers.  You could register tier relationships with a conversion factor of 1.

**Comment by victicdin** [comment]
Found some examples of the SD minetweaker API via #127 in which you referenced #123 and have examples. The curse page mentions the api but doesn't link to anything to explain/document it, if you've added minetweaker functions could you link to the documentation in here for future people with similar issues? I actually searched around for it prior to opening this issue but google wasn't useful for locating it. I've used minetweaker for a couple months but I'm not experienced enough to be able to infer what I need to use based on the information I'm finding. (Except the explicitly named functions in #123 obviously)

Lastly, I'd appreciate it if you left the issue open and allowed me to post a gist of my solution since it pertains to the issue, then I can close it myself.

**Comment by jaquadro** [comment]
I've created a wiki page for the MineTweaker APIs: https://github.com/jaquadro/StorageDrawers/wiki/MineTweaker-API

If you still think your gist adds helpful information/examples, you could edit the wiki to include that or link to it.
