### ISSUE TITLE
Big Reactors Yellorium Compacting Drawer

### ISSUE THREAD

**Issue by rmb938** [jaquadro/StorageDrawers#164]
In single player putting yellorium in a compacting drawer works fine where the ingot is in the bottom left and block in the top middle. However in multiplayer the ingot is placed into the top middle and is not compressed into a block.

StorageDrawers Version 1.7.10-1.6.2
Big Reactors 0.4.3A

**Comment by jaquadro** [comment]
Is IC2 or another Uranium provider present in the pack?

**Comment by rmb938** [comment]
I have ic2 version 2.2.785-experimental and advanced solar panel 1.7.10-3.5.1.

I don't see how that would make a difference through as it works fine in single player but doesn't work in multiplayer.

**Comment by jaquadro** [comment]
I mentioned Ic2 because I've seen this happen before on a pack I was playing on.  Specifically with the uranium taking precedence and in such a way that the yellorium equivalence wasn't working correctly.

If you can give me a dump of your ore dictionary table and recipe table, then I can investigate.  Minetweaker can give you both.

**Comment by rmb938** [comment]
Ah ok.

Here are the dumps: https://gist.github.com/rmb938/1ac632209ad0021a9301

**Comment by jaquadro** [comment]
Sorry, I didn't get to look at this right away.

In your recipe dump, I found a recipe to turn 9 yellorium ingots into a block, but I could find no recipe to turn a yellorium block back into ingots.  That includes looking for recipes in terms of the yellorium 'ore dictionary' keys.

According to the BigReactors source, the block->ingot recipe should be registered, and there's no special IRecipe implementations hanging around.

Now it's possible there's a problem with the dump, but I do see both recipe directions for all the BR metal types, so this looks like a specific issue with your environment.  What does NEI think about the recipes for a Yellorium ingot?

**Comment by rmb938** [comment]
Ah you are right. There is no recipe to turn yellorium blocks back to ingots. It seems like in FTB infinity expert mode you must use a sag mill to get 9 dust to smelt back.
