### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by JasonMcRay** [jaquadro/StorageDrawers#165]
When i put GT metagenerated items (for example Copper Gear) into storage drawer, it doesnt render it on the label.
![image](https://cloud.githubusercontent.com/assets/4236895/11164900/5001b862-8afe-11e5-8271-e519773c59bd.png)
Top drawer contains Forestry Copper Gear (renders fine), bottom one has GregTech Copper Gear (doesnt render).
Happens with any storage drawer and is not a texturepack issue, since I tested with default vanilla as well.

GT: 5.08.32
SD: 1.6.2
Forge: 1490

**Comment by JasonMcRay** [comment]
After bit more testing it appears that the Label is getting somewhat rendered. When I move further away from the Drawer I can definitely see that it "tries" to render the item

**Comment by JasonMcRay** [comment]
Ok found a fix/workaround. But it can affect FPS on slower machines. Fix is to set the itemRenderType from Fast to Fancy.

Leaving this open with hope for a fix with the Fast render.

**Comment by jaquadro** [comment]
I tracked down and fixed the issue.  Update should be out by the end of the weekend.

**Comment by jaquadro** [comment]
Fixed in 1.6.3.
