### ISSUE TITLE
server crashing when trying to put items into a drawer 1.7.1

### ISSUE THREAD

**Issue by sircrimer** [jaquadro/StorageDrawers#169]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 28.11.15 00:19
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.jaquadro.minecraft.storagedrawers.block.BlockDrawers.func_149727_a(BlockDrawers.java:241)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.RuntimeException: Attempted to load class bao for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.2.5-1-ARCH
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3786711744 bytes (3611 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 13 total; -Xmx5G -Xms5G -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 93
	FML: MCP v9.05 FML v7.10.99.99 CoFHTweaks v1.0.2B1 Minecraft Forge 10.13.4.1558 140 mods loaded, 140 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.20.38} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoreTinkerTailor{Whatever} [CoreTinkerTailor] (minecraft.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAA	Agriculture{2.0} [Agriculture] (Agriculture-1.7.10-2.0.52.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.13} [BuildCraft] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.13} [BC Builders] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.13} [BC Energy] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.13} [BC Factory] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	chisel{2.9.3.9} [Chisel] (Chisel-2.9.3.9.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1465-universal.jar) 
	UCHIJAAAA	Forestry{4.2.0.47} [Forestry for Minecraft] (forestry_1.7.10-4.2.0.47.jar) 
	UCHIJAAAA	koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.7.1} [Storage Drawers] (StorageDrawers-1.7.10-1.7.1.jar) 
	UCHIJAAAA	dendrology{1.7.10-1.6.4} [Ancient Trees] (AncientTrees-1.7.10-1.6.4.jar) 
	UCHIJAAAA	DCsAppleMilk{1.7.10_2.8o} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.8o.jar) 
	UCHIJAAAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.8o.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	AromaBackup{0.0.0.6} [AromaBackup] (AromaBackup-1.7.10-0.0.0.6.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.6.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-399.jar) 
	UCHIJAAAA	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5-noforestry.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCHIJAAAA	bluepower{0.2.962} [Blue Power] (BluePower-1.7.10-0.2.962-universal.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.7-236} [Botania] (Botania r1.7-236.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.13} [BC Transport] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.13} [BC Silicon] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.13} [BC Robotics] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8_dev_r4} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r4 - MC 1.7.10.jar) 
	UCHIJAAAA	CartLivery{0.11.1} [Cart Livery] (CartLivery-1.7.10-0.11.1.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	OpenComputers{1.5.20.38} [OpenComputers] (OpenComputers-MC1.7.10-1.5.20.38-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	computronics{1.5.10} [Computronics] (Computronics-1.7.10-1.5.10-noforestry.jar) 
	UCHIJAAAA	ElecCore{1.4.176} [ElecCore] (ElecCore-1.7.10-1.4.176.jar) 
	UCHIJAAAA	deepresonance{1.1.2} [DeepResonance] (deepresonance-1.1.2.jar) 
	UCHIJAAAA	doorsoplenty{0.1} [Doors O' Plenty] (doorsoplenty-1.0.jar) 
	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHIJAAAA	EnhancedInventories{1.7.10-1.1.8} [Enhanced Inventories] (EnhancedInventories-1.7.10-1.1.8.jar) 
	UCHIJAAAA	etfuturum{1.4.4} [Et Futurum] (Et Futurum-1.4.4.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.6.2} [Immersive Engineering] (ImmersiveEngineering-0.6.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJAAAA	Growthcraft{1.7.10-2.3.1} [Growthcraft] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Cellar{1.7.10-2.3.1} [Growthcraft Cellar] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Apples{1.7.10-2.3.1} [Growthcraft Apples] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Bamboo{1.7.10-2.3.1} [Growthcraft Bamboo] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Bees{1.7.10-2.3.1} [Growthcraft Bees] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Fishtrap{1.7.10-2.3.1} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Grapes{1.7.10-2.3.1} [Growthcraft Grapes] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Hops{1.7.10-2.3.1} [Growthcraft Hops] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	Growthcraft|Rice{1.7.10-2.3.1} [Growthcraft Rice] (growthcraft-1.7.10-2.3.1-complete.jar) 
	UCHIJAAAA	immersiveintegration{0.6.1} [Immersive Integration] (immersiveintegration-0.6.1.jar) 
	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.69} [Logistics Pipes] (logisticspipes-0.9.3.69.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	MagicBees{1.7.10-2.4.0} [Magic Bees] (magicbees-1.7.10-2.4.0.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.13.1} [MalisisCore] (malisiscore-1.7.10-0.13.1.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.12.1} [Malisis' Doors] (malisisdoors-1.7.10-1.12.1.jar) 
	UCHIJAAAA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.7.10-1.9.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1RC1} [Nether Ores] (NetherOres-[1.7.10]2.3.1RC1-18.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	OpenPeripheralCore{1.2} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.2.jar) 
	UCHIJAAAA	OpenPeripheral{0.4} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.4.jar) 
	UCHIJAAAA	OpenPeripheralIntegration{0.3} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.3.jar) 
	UCHIJAAAA	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCHIJAAAA	mobdropcrops{1.7.2a} [Pam's Mob Drop Crops] (Pam's Mob Drop Crops 1.7.10a.zip) 
	UCHIJAAAA	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pam's WeeeFlowers 1.7.2b.zip) 
	UCHIJAAAA	ResourcefulCrops{1.7.10-1.0.0-25} [ResourcefulCrops] (ResourcefulCrops-1.7.10-1.0.0-25.jar) 
	UCHIJAAAA	rftools{4.13} [RFTools] (rftools-4.13.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.2.jar) 
	UCHIJAAAA	SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
	UCHIJAAAA	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
	UCHIJAAAA	StacksOnStacks{{$version}} [Stacks on Stacks!] (StacksOnStacks-1.7.10-2.4.1.jar) 
	UCHIJAAAA	StorageDrawersBop{1.7.10-1.0.3} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.0.3.jar) 
	UCHIJAAAA	StorageDrawersForestry{1.7.10-1.0.5} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.0.5.jar) 
	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.0.4} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.0.4.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	TinkersTailor{1.0} [TinkersTailor] (TinkersTailor-alpha-0.3.0.jar) 
	UCHIJAAAA	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-universal.jar) 
	UCHIJAAAA	Waterproof{1.0} [Waterproof] (Waterproof 1.0-1.jar) 
	UCHIJAAAA	woodstuff{1.3.1} [WoodStuff] (WoodStuff-1.3.1.jar) 
	UCHIJAAAA	aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.1-89
	NetherOres: -[1.7.10]2.3.1RC1-18
	ThermalDynamics: -[1.7.10]1.1.0-161
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['sircrimer'/316, l='world', x=671,43, y=69,00, z=994,61]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by jaquadro** [comment]
Blehhhhh thanks for the report.  Fixed again in 1.7.2.
