### ISSUE TITLE
[Enhancement] ThermalExpansion integration

### ISSUE THREAD

**Issue by codewarrior0** [jaquadro/StorageDrawers#174]
In addition to cutting logs, TE's Sawmill allows reclaiming planks and other materials from wooden items. What do you think about using the Sawmill API to add recipes for breaking drawers down into planks and sawdust?

(I have all these extra drawers sitting around that don't match the theme of my base... :factory:)

Similarly, TE's Pulverizer allows reclaiming metal dust from some metal items and could be used to break upgrades down to metal dust and sawdust.

**Comment by jaquadro** [comment]
This sounds like a good integration to add.

**Comment by jaquadro** [comment]
I have this mostly implemented now, but the pack system needs an extension and some refactoring to support breaking down blocks with mod planks.

**Comment by codewarrior0** [comment]
Awesome!

I'm guessing the recipes are just placeholders for now. I'd expect to get back the planks used for the chest too, so I'd get back 8 oak planks + 6 other planks for a full drawer, 8+3 for a 1x2 drawer, etc. Said refactoring would probably help with that.

**Comment by jaquadro** [comment]
This is up now, and works with all the packs.

There was a surprisingly large amount of rework to do with the packs, but they're more consistent now.
