### ISSUE TITLE
Natura slabs crafting into normal compact oak drawers

### ISSUE THREAD

**Issue by Shinisuryu** [jaquadro/StorageDrawers#175]
Specifically Amaranth, Tigerwood, Willow, Darkwood and Fusewood. Not sure why, all the planks work fine, it's only when the slabs are involved that it gives oak drawers.

**Comment by jaquadro** [comment]
This was actually widespread, affecting all packs except Erebus.  They've all been updated and the slabs should all be working.

**Comment by Shinisuryu** [comment]
Oh wow. Thanks!
