### ISSUE TITLE
Critical bug: Sorting Upgrade deletes entire drawer

### ISSUE THREAD

**Issue by Keridos** [jaquadro/StorageDrawers#177]
I just had an entire drawer (4 slot oak, full block) which was locked and had the obsidian upgrade and the level 2 status upgrade. When I rightclicked that one with a stack of 3 sorting upgrades, 2 of the sorting upgrades vanished, the whole block got deleted (including all the contents).
This is replicatable.

MC 1.7.10, Storage Drawers 1.7.2.

**Comment by jaquadro** [comment]
Thanks, I'll try and look into it this weekend.  The refined relocation bits are tested pretty lightly.

**Comment by jaquadro** [comment]
Fixed in 1.7.4.  The bug was applying a sorting upgrade to a sorting drawer (the hint was that you said 2 upgrade vanished -- maybe it registered a double click).
