### ISSUE TITLE
WAILA Integration Suggestion: Display capacity as well as count

### ISSUE THREAD

**Issue by sctjkc01** [jaquadro/StorageDrawers#179]
Basically, title.  I'd like to be able to see exact numbers on how full my drawers are (even if they're reduced a little to fit on screen, ie 12.5M), because while the storage level gives good at-a-glance storage levels, I'd like to know how close to full my drawers really are.

(That, and I'm amassing so much Essence of Coal in one quadruple-Emerald single-slot full-size drawer that I'd like to estimate when I'd need to move it over to a large storage drive... I pulled out a calculator and it said (13 ^ 4) * 32 * 64 is just shy of 58.5 million, and the storage level upgrade is saying I'm about a third full on only 43 thousand.)

**Comment by codewarrior0** [comment]
Upgrades are additive. Try 13 * 4 * 32 * 64 = ~106 thousand.

**Comment by Nentify** [comment]
Wouldn't it be (13*32*64)^4? You can shift right click to see number of items stored in a drawer.

**Comment by jaquadro** [comment]
(13 * 32 * 64) ^ 4 is 502,450,425,614,565,376, which is a bit out of reach of a Java integer :)

codewarrior0 is right, the multipliers from the upgrades are additive.  (32 * 64) * (13 + 13 + 13 + 13) = ~106 thousand.

**Comment by Nentify** [comment]
Sorry, (13 * 32 * 64) x 4 is what I found

**Comment by Nentify** [comment]
Yeah, sorry, should be x 4. I was doing calculations earlier, but with 5 upgrades so was confused about the numbers. ;P

**Comment by codewarrior0** [comment]
I even had to check the source to see if there wasn't a "+1" lurking in the formula. After reading three different answers about the capacity, maybe the waila readout is a good idea. Though the whole thing about varying stack sizes and items that only stack some of the time would complicate things.

(Did you know IE wooden crates keep their items when broken, and will stack if and only if they contain the exact same items?)

**Comment by sctjkc01** [comment]
@codewarrior0 - Jabba Barrels always [read out their contents to the world](https://bitbucket.org/ProfMobius/jabba/src/4c1ccec85db33e4e43e5a68f2983d80da5b96093/src/main/java/mcp/mobius/betterbarrels/client/render/TileEntityBarrelRenderer.java?at=forge_1187&fileviewer=file-view-default#TileEntityBarrelRenderer.java-59), listing it as "34x64 + 42" Cobblestone or "23x16 + 6" Eggs.  And the [Waila integration](https://bitbucket.org/ProfMobius/jabba/src/4c1ccec85db33e4e43e5a68f2983d80da5b96093/src/main/java/mcp/mobius/betterbarrels/BBWailaProvider.java?at=forge_1187&fileviewer=file-view-default#BBWailaProvider.java-38) has a readout of current item count _slash_ maximum item count.

One would think, if it's been done already, it shouldn't be too hard to re-implement it for Storage Drawers.

**Comment by jaquadro** [comment]
Jabba has more room to work with, both on the block face and in Waila.  I've been meaning to try a new LIII indicator upgrade to render text, but I almost surely need a more compact representation of count for that.

For Waila, if you're looking at a 2x2 then the information window is already pretty huge.  It's why I've held back from adding more information to it.  But I could expose more flexibility in the config, like letting you format your own information strings.

**Comment by sctjkc01** [comment]
If the most a drawer can store is six digits, I'm sure nobody would complain if you added six more characters (like straight item count) to a drawer's line in Jabba.  Since you spit out the full item name in the Waila tooltip (ie "Essence of the Nether"), I can imagine you might be able to truncate at least some of it if you're looking to save space.

And I'm almost curious how large a font you're using if you're needing a more compact textual representation.  Surely you would be able to fit it in about the same amount of space the current Status Lv2 bar is using...

**Comment by jaquadro** [comment]
This will be available in the next release.  Each drawer will report a line like:

Stack Limit: 832 (x26)

Where the first number is the number of stacks each drawer can hold, and the number in parentheses is your current upgrade multiplier.  Hopefully that won't be confusing to most people.

The default item count representation has been changed to "stack + remainder" (JABBA-style), which will make comparing against the limit more natural without me having to break out a separate one for each item.  The default change will only affect new mod installations.
