### ISSUE TITLE
1.7.7 (1.7.10) Thermal Expansion

### ISSUE THREAD

**Issue by O13SC3N3** [jaquadro/StorageDrawers#201]
Still fails to integrate.

**Comment by jaquadro** [comment]
I need, at minimum, your version of Thermal Expansion, and preferably the failure message printed to the log.

**Comment by O13SC3N3** [comment]
Sorry for the short post, thought I posted this originally.

Thermal Expansion 4.1.1-237
Forge 1566
FastCraft is installed.
Java 8

and I get the following; http://pastebin.com/7exWrL9u

**Comment by O13SC3N3** [comment]
Any luck m8 on how I can fix this?

**Comment by jaquadro** [comment]
This is actually a bug in the Forestry (and Misc) packs.  There's a new update out for them which should fix it.
