### ISSUE TITLE
Drawer reverts to Oak after being broken

### ISSUE THREAD

**Issue by horsten** [jaquadro/StorageDrawers#203]
Thanks for a fantastic mod. I noticed this in 1.8.9-2.3.1: When I place a drawer unit e.g. the Basic Drawers 2x2 unit in Dark Oak, and then I break it with an axe to move it, it reverts back to the standard Oak finish.

In the inventory, WAILA shows "Material: Dark Oak" on the original unit, but no "Material" line after it's been dismantled and picked up again.

This is a little annoying since it prevents me from reusing the units after moving them, since I like to keep a consistent dark oak finish in my storage racks :)

**Comment by codewarrior0** [comment]
A workaround: If you update to 2.3.2, you will be able to craft some dark oak trim, and shift-right-click it onto the drawer to change it back to dark oak.

**Comment by jaquadro** [comment]
Fixed in 2.3.3
