### ISSUE TITLE
SD crashes because of rendering error when using NEI

### ISSUE THREAD

**Issue by SDXC** [jaquadro/StorageDrawers#205]
Since the last update of StorageDrawers for 1.7.10 Minecraft sometimes crashes with this error:
http://pastebin.com/wmZWY0RB

Until now it happend only while using NEI to look up some recipes.

**Comment by jaquadro** [comment]
I don't have any thoughts on why the NEI render would be crashing.  I added some safety checks, so at worst the offending items should just not render.  Re-open if that's not the case.
