### ISSUE TITLE
Feature Request: Metal Drawers

### ISSUE THREAD

**Issue by netzgeist** [jaquadro/StorageDrawers#207]
Im in love with storage drawers, I do use them whenever I can. 

Though, they sometimes are aesthetically unpleasing, especially when I am dealing with techy setups:

http://i.imgur.com/mhJgxUs.png

So the humble feature request is: Add some metals as base materials. Vanilla Iron/Gold would be enough I guess.

**Comment by codewarrior0** [comment]
I like this idea. Sometimes I think it would be cool to have metal variants of the compacting drawers, too.

**Comment by codewarrior0** [comment]
I remember the boss saying he was working on a way to use any block's texture on a drawer. If that feature makes it to a release, we will be able to use any metal block as a drawer material - even Chisel variants of metal blocks and alloys like signalum or pulsating iron.

**Comment by netzgeist** [comment]
That would be god tier ofc and if anyone works on that, my request should be closed to save ressources

**Comment by jaquadro** [comment]
Framed drawers (stealing Bibliocraft terminology) is the next feature I want to deliver.

**Comment by codewarrior0** [comment]
Can't wait!

**Comment by jaquadro** [comment]
Check out version 1.9.0.  Does this allow you create suitably styled drawers?

**Comment by netzgeist** [comment]
Absolutely. Drawers will now fit into labs, dungeons, fabs, and whatnot building style I used to avoid them for. This is big for me, thank you alot!
