### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by robertm1771** [jaquadro/StorageDrawers#208]
Seem to be an issue with Aura cascade crystals placed white in the controller once I placed yellow it crashed. Using AuraCascade 557 

[crash-2016-02-08_17.17.48-server.txt](https://github.com/jaquadro/StorageDrawers/files/122300/crash-2016-02-08_17.17.48-server.txt)

**Comment by jaquadro** [comment]
Thanks, turns out it's a recent bug with the controller (in 1.7.10 and 1.8.9), not Aura cascade.

Fixed in both versions
