### ISSUE TITLE
Potential issue: Exact Same Items will not stack.

### ISSUE THREAD

**Issue by AryuSyrius** [jaquadro/StorageDrawers#212]
I have a private modpack that contains this mod. I updated this mod to 1.7.8 then to 1.7.9 along with   The Erebus, Special Mobs, and PneumaticCraft at the same time. After updating to 1.7.9 I started to notice an issue in which the exact same items were not stacking, until I throw both on the ground and then pick them up. Looking at the metadata via NEI revealed they are the same. I am not sure if it the issue is a result of this mod or another.
[Here is the modlist of my pack.](http://www.technicpack.net/modpack/curiosity-x.789812)

**Comment by jaquadro** [comment]
Is it limited to certain items, or all items?

**Comment by AryuSyrius** [comment]
It's been multiple items and seemingly random. Carrots, torches, obsidian blocks. Also, the glitch may cause me not to be able to put an item in a drawer. Even if the drawer is locked without items in it already.

**Comment by jaquadro** [comment]
Well, I can't say that anything in 1.7.9 would cause this.  1.7.8 included a lot of changes item handling, mainly in the controller.  But 1.7.9 was a tiny bugfix exclusive to the controller.

If an item and its metadata are the same, then the only thing I can think of off-hand is that something started adding tag data to items.  If the tags mismatch, the items are considered unequal.  Think things like dyed leather armor.

Try taking a look with something like InvEdit or MCEdit.

**Comment by jaquadro** [comment]
Oh wait, you mentioned this applied to 1.7.8 too.  If it's a controller issue specifically, it's worth more investigation on my side.  But if you're having troubles putting into drawers directly, then then 1.7.8 changes shouldn't have affected that.

**Comment by AryuSyrius** [comment]
I haven't been able to reproduce the issue at will, and I don't think that it explicitly happens with drawers or controllers as I can just fine items out and about and they will not stack. I appreciate your suggestions regardless. If I do come up with a way to consistently reproduce the issue, and it does involve the mod, i'll let you know. Again thank you.

**Comment by AryuSyrius** [comment]
I know it is out of line at this point, but I used your NBTEditor and I found that your assumption regarding tags was correct. In at least one instance of items not stacking I found [this](http://imgur.com/ctM97Ts) which are two stacks of 4 Nether Redstone Ore that will not stack. One has a tag and another doesn't. Do you think that is the issue and would you have any idea how I can figure out what mod is doing it?

**Comment by jaquadro** [comment]
I have no idea what mod is causing it.  You might be able to ask around on MCF or FTB.

But yeah, that "feature" is going to cause a lot of havoc with item stacking everywhere.

**Comment by AryuSyrius** [comment]
Alright, well I think we can consider this closed on on your end. Again I appreciate the assistance.
