### ISSUE TITLE
Can only make oak drawers (1.7.10-1.8.0)

### ISSUE THREAD

**Issue by Trixtrox** [jaquadro/StorageDrawers#214]
Can't make any drawers other than oak. All recipes using birch, spruce, etc, are functional but make oak drawers instead of their respective type.

This error occurs even with a fresh install on forge version 10.13.4.1448-1.7.10, and storage drawers version 1.7.10-1.8.0

![untitled](https://cloud.githubusercontent.com/assets/17035158/13031245/b764360c-d283-11e5-8fd3-a429428136e7.png)

**Comment by jaquadro** [comment]
Do you have any other mods present?  And does this happen if you disable the 'fallback recipes' option?

**Comment by Trixtrox** [comment]
I noticed this first on a client with other mods but verified it on a test client with no other mods present.

Disabling the fallback recipes option seems to have fixed the issue on both clients.

**Comment by jaquadro** [comment]
The fallback recipes are explicitly registered at a lower priority in the Forge recipe list.  I could maybe see this happening if another mod re-sorted the recipes.  

It's more concerning that it happened with no other mods present.  I'm not sure how to reproduce it.
