### ISSUE TITLE
Right Click with empty hand Crash on Drawer Controller

### ISSUE THREAD

**Issue by Rene211** [jaquadro/StorageDrawers#215]
If i click with an empty hand on a Drawer Controller it crashes the Game to the Desktop.
Iam playing on the Revolution 2 Beta Modpack.

Crash report is down below.

[storage_drawer_crash_report.txt](https://github.com/jaquadro/StorageDrawers/files/131508/storage_drawer_crash_report.txt)

I dont know how to crate a Drop down for the Crash Report. Would be nice if someone could explain me that. 

Thank yoou :)

**Comment by jaquadro** [comment]
You need to update to 1.7.9 or 1.8.0.
