### ISSUE TITLE
Controller Slave block will not take input

### ISSUE THREAD

**Issue by PGMacDesign** [jaquadro/StorageDrawers#221]
I have a setup that looks like this:
http://screencloud.net/v/40RP
I am trying to get the pipes to drop items into the controller slave, but after the first one, it never seems to drop it (Using Flint as a test item, I have the box a little to the left of what you see.) 
Underneath the block rows/ columns I have trim connecting them.
Am I straight up doing something wrong? Or is there a way to force items into the controller slave block properly?
Just to add one more thing, if I try to force items from a pipe directly into a controller slave block without anywhere else to go with the item (flint) drawer right below it, it will still not get placed in and will instead spit it out. 
Thanks all
-PGMacDesign

**Comment by jaquadro** [comment]
It looks like the entire left wall is out of range of the controller.  I'm counting out 14 from the controller, but the limit is 12, unless you modify the config.

**Comment by PGMacDesign** [comment]
Ah, I must have misunderstood the Controller slave then. Does it either extend the range OR allow for another access point into the same network? Or does it serve another function?

**Comment by codewarrior0** [comment]
The slave does not extend the range. It simply acts as another access point for pipes/hoppers/etc. 

Looks to me like the left wall is out of the controller's range, too. The controller should be at the center of a 25x25x25 cube that contains all of your drawers. If I were working on your drawer setup, I'd put the controller... right about where you're standing, and connect it to the bank of drawers using a line of drawer trim buried under the floor.

**Comment by PGMacDesign** [comment]
Understood. Thank you for the clarification. I assume I could also theoretically place controllers in place of those slaves and it would technically function? (Though be less efficient if I read the docs correctly)

**Comment by jaquadro** [comment]
The controllers might not all see the same set of blocks.  Otherwise it would work but they would each be rebuilding the network every 5 seconds.

**Comment by PGMacDesign** [comment]
Perfect, thanks for the tips all.
