### ISSUE TITLE
World corrupting mod interaction between StorageDrawers and Chisel.

### ISSUE THREAD

**Issue by netzgeist** [jaquadro/StorageDrawers#222]
Summary:
You can corrupt your savegame if you try to add a specific chisel block to the framing table. See the picture:

http://imgur.com/4CBqWS9

As soon as I shift-click that block into the table, the game crashes with an already tesselating exception:

http://pastebin.com/AKiwGyhJ

Furthermore, the table stays in this state, your client will crash again as soon as you reconnect.

**Comment by jaquadro** [comment]
Disable the framed drawer feature in the config to de-register the blocks (which will also cause you to lose every framed drawer in your game), otherwise you can try to manually fix it in MCedit or NBTExplorer.  I'll check out the chisel blocks.

**Comment by netzgeist** [comment]
No worries its a test savegame.Most of the chisel blocks work as expected. A few are badly rendered as half transparent and the 3x3 ones seem to create the issue

**Comment by jaquadro** [comment]
This took a while to track down, but there's a fix in 1.9.2 now.  

The CTM chisel blocks don't supply icons, so using them will cause a drawer to be framed with a default texture more or less intended to look invalid.
