### ISSUE TITLE
Ticking block entity crash when picking up drawer with JABBA dolly

### ISSUE THREAD

**Issue by wjrogers** [jaquadro/StorageDrawers#224]
I had noticed I had two drawers containing the same item, so I picked up one with a dolly to move it out of the system and remove the items. Meanwhile, a machine was sending the same item into a controller slave via item duct. The game crashed almost immediately after I picked up the drawer with the dolly.

[crash-2016-02-24_23.19.19-server.txt](https://github.com/jaquadro/StorageDrawers/files/146545/crash-2016-02-24_23.19.19-server.txt)

**Comment by jaquadro** [comment]
This should be fixed with 1.9.3.  If not, please re-open the issue with a new crash log.
