### ISSUE TITLE
Drawer Controller not respecting void upgrade

### ISSUE THREAD

**Issue by jinks** [jaquadro/StorageDrawers#227]
I recently updated my modpack (Infinity) which came among others with a Storage Drawers update from 1.7.5 to 1.9.2.

After a while I noticed my AE system filling up with items that should be going into drawers. Checking on the drawer system I noticed that the controller won't accept items that would go into full void drawers any more, even trying to manually inserting them into the controller (double right-click) won't work. The void drawer itself accepts the items just fine.

**Comment by codewarrior0** [comment]
Same here. With 2.4.1, I noticed the controller won't void my cobble when I double-right-click on it, but doing so on the cobble drawer works. I didn't try inserting the cobble with a hopper yet, although Thaumcraft 5 golems obeying a Store seal on the controller will void items when appropriate.

**Comment by jinks** [comment]
Some more testing: The AE2 (rv3-beta) storage bus definitely doesn't put items into a full void drawer via controller and uses a disk instead. TE itemducts can pipe into the controller without problem.

**Comment by codewarrior0** [comment]
@jinks Does anything change if you make the storage bus a higher priority than the ME drives? I remember with 1.8.8 or so, I had no problems voiding items via the ME network.

**Comment by jinks** [comment]
The storage bus is at priority 10000, nothing else has any priority set at all.

**Comment by jaquadro** [comment]
Did you happen to update AE2 at the same time?  A few days ago I ran across a comment that neither SD nor JABBA was voiding correctly on an ME network.

I'll try and check my dev world this evening which is using an RV2 build.

**Comment by jinks** [comment]
Might well be AE2's fault. No idea why the mack maintainers decided to go for RV3 beta builds, but it's what I'm stuck with for now.

**Comment by jaquadro** [comment]
Confirmed the issue also existed with RV2.  The routing logic improvements in 1.8.8 introduced a regression to voiding for anything using the new API (namely, AE2).

Fix is available in version 1.9.4.
