### ISSUE TITLE
[Crash]OreDicted storage drawers (with wildcard meta) crash on handling

### ISSUE THREAD

**Issue by ReikaKalseki** [jaquadro/StorageDrawers#230]
The easiest fix is to make the renderer and localization treat metadata 32767 as metadata 0.

Example error:
http://pastebin.com/gWHCQtKf

**Comment by jaquadro** [comment]
The render path looks outdated -- I bet it won't crash with the latest release.  But it might render invisibly.

Do you know what block triggered the error?  The standard drawers use a modulus meta value, so they shouldn't be returning null icons, though converting the overflow to 0 would be better.  If you have any of the optional wood packs loaded in however, those might give back null icons.

**Comment by ReikaKalseki** [comment]
> I bet it won't crash with the latest release. 

My version is what was latest a couple months ago when the pack was built: 1.7.5

> But it might render invisibly.

Which is fine, as long as it does not crash when NEI or similar cycles to it.

> Do you know what block triggered the error? If you have any of the optional wood packs loaded in however, those might give back null icons.

And those are the ones crashing, yes. Is that another mod dev?

**Comment by jaquadro** [comment]
The cosmetic half of this should be fixed in 1.9.5, and I'm pretty sure the crash itself was fixed long before.

To answer the pack question, I maintain all of the wood packs.  The exception is Scott Killin's Ancient Trees, which embeds its own support and may not integrate with the current API as deeply.
