### ISSUE TITLE
Crash with v2.4.3 on 1.8.9

### ISSUE THREAD

**Issue by jrpoints** [jaquadro/StorageDrawers#231]
http://pastebin.com/eTFevtg3

Client side crash only, thaumcraft is mentioned, so maybe a issue on that end, not sure, reverting to 2.4.2 fixed the crash.

**Comment by jaquadro** [comment]
Wow.  This should not have been able to happen.  Forge did not properly translate the names back when compiling the jar.

I completely rebuilt my environment, and the new JAR looks better.  Released as 2.4.4.
