### ISSUE TITLE
Framed drawers do not get used up while framing

### ISSUE THREAD

**Issue by Dijkstra1** [jaquadro/StorageDrawers#232]
I made up a bunch of framed drawers and framed some of them, when I went back to frame more that there should have been so I paid more attention an noticed that none of the framed drawer got used plus i got an extra framed drawer so my drawer are go up as I make more.

Attached is a video of bug.
 
[Drawer Bug.zip](https://github.com/jaquadro/StorageDrawers/files/158577/Drawer.Bug.zip)

**Comment by jaquadro** [comment]
Is this the latest version?

**Comment by Dijkstra1** [comment]
I do not know I am playing the latest version of FTB infinity evolved.

**Comment by jaquadro** [comment]
There was a handful of bugfixes released since the last FTB pack update, including the duplication bug.  You could update the mod separately, or you'll need to wait and see if the FTB team releases another update.

**Comment by Dijkstra1** [comment]
Thanks it is another mod I will have to update my self
