### ISSUE TITLE
[QUESTION] Misc pack for 1.8?

### ISSUE THREAD

**Issue by hron84** [jaquadro/StorageDrawers#240]
Will the Misc pack released for 1.8? I really miss silverwood and greatwood drawers, it would fit very well in my magic room. Please, please upgrade it.

**Comment by jaquadro** [comment]
My plan is to merge all the packs into one for 1.8.

**Comment by codewarrior0** [comment]
:+1: 

The 1.8 server I'm playing on has Botania and Thaumcraft 5, and I'd like more drawer types than just the Vanilla ones.

**Comment by jaquadro** [comment]
This clearly didn't happen for 1.8, but it is finally here for 1.9/1.10, and should be easy to maintain going forward.

https://minecraft.curseforge.com/projects/storage-drawers-extras
