### ISSUE TITLE
Trying to use StorageDrawersPack crashes on PostInit

### ISSUE THREAD

**Issue by P3t3rU5** [jaquadro/StorageDrawers#245]
I'm trying to set up a server with Natura, Forestry, BoP and Misc Pack's but it seems to be crashing on PostInit

[http://pastebin.com/Ab0HyU3y](http://pastebin.com/Ab0HyU3y)

**Comment by jaquadro** [comment]
Most likely you just need to update Storage Drawers

**Comment by P3t3rU5** [comment]
oh, thanks that solved it, didn't pay attention to version
