### ISSUE TITLE
1.9 Half block drawers' hitbox reverts to facing east on chunk reload.

### ISSUE THREAD

**Issue by NolanSyKinsley** [jaquadro/StorageDrawers#246]
MC 1.9 forge build #1784 After you place a half size drawer and the chunk is unloaded and reloaded, the drawers still look like they are facing normally but the hitbox is facing east. You can't access the drawer by clicking on it anymore but the contents are still there and can be regained by breaking the drawer.

Does not affect full size drawers.

**Comment by jaquadro** [comment]
This should be fixed in 3.1.0+
