### ISSUE TITLE
[1.8.9] Crash on picking up taped Comapcting Drawer

### ISSUE THREAD

**Issue by BraynStorm** [jaquadro/StorageDrawers#252]
[CrashReport](http://pastebin.com/bskYqxQK)
I used the packing tape on a Compacting drawer and tried to pick it up with my pick (with Silk Touch).
`Forge: 1794`
`Chameleon: 1.1.0`
`Storage Drawers: 2.6.0`

**Comment by jaquadro** [comment]
This should be fixed in 2.6.1.
