### ISSUE TITLE
[1.8.9][Rendering] Random crashes. 

### ISSUE THREAD

**Issue by BraynStorm** [jaquadro/StorageDrawers#253]
[Crash report](http://pastebin.com/F0LF5DWN)
Happens at random (mostly when I port from the Nether to the Overworld where the Dark Oak drawer in question is positioned). When I restart the instance everything works fine, after say an hour - the same crash. The drawer contains some Reliquary items (The mob hearts, they have an animations (possible cause?)).
`Forge: 1794`
`Chameleon: 1.1.0`
`Storage Drawers: 2.6.0`

**Comment by jaquadro** [comment]
Looks like I'm probably trashing my own render state against the new multi-threaded rendering.  I have a general idea to fix this, but won't be able to test it.

**Comment by jaquadro** [comment]
See if version 2.6.1 helps.  Rendering should be protected from sharing render state across threads, if that's what was really happening.  

If it's still occurring, re-open the issue and see if you can find a fast, reliable way to reproduce the crash.  Was the dimension travel a guaranteed way to cause it?
