### ISSUE TITLE
[1.8.9] Errors in Client Log

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#254]
I have a few errors showing up in my client log when trying to connect to my server, the first time I connect to the server I get a "Fatal Error" message, and I believe storage drawer might be the cause.

Client-log: https://drive.google.com/file/d/0BxQWn9jKBIAJNUxZSndfdzIxZkU/view?usp=sharing
The first error shows up at line 38422 (timestamp 14:46:19)
if it's not storage drawer could you point me to the culprit?

**Comment by jaquadro** [comment]
Are you connecting to an independent multiplayer server, or are you connecting through LAN play?

**Comment by jaquadro** [comment]
I'm not sure what's going on with your world that a packet would have crashed there, but given the large number of severe entity errors I would guess you crashed and possibly corrupted your world.

However, I've put a fix in 2.6.1 that should avoid causing the Storage Drawers exception in your log.

**Comment by Xiaminou** [comment]
Well it actually works fine, I just get a fatal error the first time I connect to the server after I've launched minecraft, the second time works fine.
I just thought maybe it was a bug, if not, don't worry about it.
