### ISSUE TITLE
[1.9] Can't mine blocks at all.

### ISSUE THREAD

**Issue by jayands** [jaquadro/StorageDrawers#255]
I just got my Minecraft re-installed, so this was a fresh install. I got Forge, build 1811, and installed about eleven mods, including StorageDrawers and Chameleon. After loading up the new world, I found I could break blocks, but they would appear before they were collectible, about a second later. Using the correct tool (via the bonus box) doesn't help. I narrowed it down to either StorageDrawers 3.0.0 or Chameleon 2.0.1, as SD is the only mod I have that relies on Chameleon.

**Comment by jaquadro** [comment]
SD 3.0.0 isn't compatible with Forge 1811.  There's an SD 3.0.1.  That aside, there's nothing in either mod that should interfere with general mining.  Your description sounds like more like client/server lag.

**Comment by jayands** [comment]
Thanks, I'll try it right now.

EDIT: Upgrading to 3.0.1 fixed it, thanks.
