### ISSUE TITLE
Item Dupe with Framing Table. 1.7.10-1.9.4

### ISSUE THREAD

**Issue by ZornTaov** [jaquadro/StorageDrawers#256]
When shift clicking on the resulting item, the frame isn't used and all other items are used up in a weird amount each instead of 1:1.
Example pictures: http://imgur.com/a/adWO3
Mod List: http://pastebin.com/S1sts7eu

**Comment by jaquadro** [comment]
Fixed in 1.9.5 / 2.6.2 / 3.1.1
