### ISSUE TITLE
[1.7.10] Can't insert item in hand to drawer when locked with Personal Key

### ISSUE THREAD

**Issue by eranor** [jaquadro/StorageDrawers#258]
Hi.

I think I found a bug. When I try to insert an item directly to the drawer, with the item in hand it won't insert it, but the double right click with empty hand does.
- Storage Drawers version: 1.7.10-1.9.4
- Forge version: 10.13.4.1614

**Comment by jaquadro** [comment]
Can't replicate this.  Tested in SSP and SMP with another player.  Everything with the standard personal key seems fine.

**Comment by eranor** [comment]
Now it works, and I have not changed anything. Maybe I have not clicked it or Inventory Tweaks was trolling me. Sorry for the inconvenience.
