### ISSUE TITLE
Taking TiC tools out from drawers teleports them to random location

### ISSUE THREAD

**Issue by Zaflis** [jaquadro/StorageDrawers#261]
I first noticed this issue when i had TE's Energetic infuser outputting charged tools into a 2x2 drawer. Taking it out would make it vanish. I looked everywhere around but couldn't find it. Crafted another one and repeated the test, again it vanish somewhere.

In creative world they only warp 3-4 blocks away from player at max, so it's possible they got stuck on the roof or under floor, i don't know. Vanilla tools like diamond pickaxe always goes directly to player inventory.

StorageDrawers-1.7.10-1.9.5

**Comment by jaquadro** [comment]
Fixed in latest versions.  All items will try to go directly into your inventory first, otherwise they will drop in front of the drawer.

Originally, items dropped directly on the player, and tinker tools must handle this a bit differently.

**Comment by codewarrior0** [comment]
For the record, the way items dropped directly on the player had an interaction with TE's Forge Lexicon: If the lexicon is in Empowered mode, it will auto-convert the dropped item to the "preferred oreDict equivalent" set up in the lexicon, which would make it look like a different item was pulled out of the drawer. I guess I'll find out if this changed when I get around to updating.
