### ISSUE TITLE
1.9-3.1.1 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawers#263]
Issue: storage-drawers-1.9-3.1.1 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/c059d0682c598614f8a8fcbcc333c5f2

fml server latest:
https://gist.github.com/6b1dd647ccc7ae1b2c79c99d2c144134

**Comment by jaquadro** [comment]
This will probably be happening for a while as Forge keeps ripping up the carpet from under our feet.  I'm planning on another release sometime today.

**Comment by kreezxil** [comment]
Yeah they released two new versions since the report 

-----Original Message-----

**Comment by jaquadro** [comment]
I didn't really see changes required for the newest Forge.  Maybe the jar just needed to be recompiled with it.  Tested 3.1.2 on a dedicated 1826 server and it loaded fine.
