### ISSUE TITLE
[3.1.1] Crash related to HalfDrawers Render

### ISSUE THREAD

**Issue by KennyBurch** [jaquadro/StorageDrawers#264]
During an attempt to craft the storage upgrade template I experienced a crash. Turns out that when an item is placed on a Tinkers construct workbench it is rendered in a 3d model that slowly spins. Somehow this rendering must be different than normal because the game crashes with the following:

[crash-2016-04-02_20.08.35-client.txt](https://github.com/jaquadro/StorageDrawers/files/201148/crash-2016-04-02_20.08.35-client.txt)

To reproduce: Place a tinker construct crafting station in the world. Then place a Half Drawers on the table.

**Comment by jaquadro** [comment]
This should be fixed on the Tinkers/Mantle side, but we're waiting for a new build from them.
