### ISSUE TITLE
[Crash]: net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException: Attempted to register a Block with conflicting names

### ISSUE THREAD

**Issue by Lanse505** [jaquadro/StorageDrawers#265]
Crash Log:
http://puu.sh/o4tzL/2d42c43d53.txt

Entire Log:
http://puu.sh/o4tJl/e8160fba1c.log

**Comment by Lanse505** [comment]
Not sure which other mods are at fault here but i'm reporting it so you atleast know :)

**Comment by BJR1984** [comment]
Same, Tested with Just Storage Drawers and Chameleon mods installed
[crash-2016-04-03_07.08.34-client.txt](https://github.com/jaquadro/StorageDrawers/files/201338/crash-2016-04-03_07.08.34-client.txt)
[fml-client-latest.txt](https://github.com/jaquadro/StorageDrawers/files/201339/fml-client-latest.txt)

**Comment by jaquadro** [comment]
Forge is in the middle of a major registry change.  Yesterday's release is probably caught in the middle of that.

**Comment by ghost** [comment]
Same problem. With Forge 1832 http://pastebin.com/P1qP0muT

With Forge 1813 http://pastebin.com/Bjw6L1kg

I guess this things will happen until we get some Recommended stable version of Forge.

Is there any Forge version this release should be running ok on?
Thanks.

**Comment by jaquadro** [comment]
Yeah the current release will pretty much only work with 1826.  And even then, I can only say "works on my machine".  Everything immediately before and after is broken due to Forge registry refactoring.

I'll have another build out today, but no guarantees it'll be good for more than a few hours.  Forge is taking these pre-stable builds as an opportunity to make breaking changes.

**Comment by jaquadro** [comment]
Give SD 3.1.3 and Chameleon 2.1.2 a try.  The set Forge dependency is 1832.

**Comment by ghost** [comment]
Perfectly working on 1832. One question, the drawers doesn't show anymore when an upgrade was applied?

**Comment by jaquadro** [comment]
Yeah that's deliberate.  Originally it was a 1.8.9 limitation, but I always hated them actually.  But I could image they are sometimes useful, so I am open to other ideas.

**Comment by ghost** [comment]
Maybe some visual indicator when holding the upgrade, to know what drawers have them already applied, or a wrench maybe. Or even a config to turn that on/off to taste.
