### ISSUE TITLE
Drawer Controller ignores Slaves / Has lower reach than supposed to

### ISSUE THREAD

**Issue by MechMK1** [jaquadro/StorageDrawers#266]
In the attached setup, the shown drawer controller is unable to find the Crop Sticks (in the right part of the image), even though the Slaves should technically extend the range for them to be found.

I have waited more than 5 seconds, but to no avail. The version used was 1.7.10-1.9.4.

![2016-04-09_21 35 06](https://cloud.githubusercontent.com/assets/979843/14405941/242aead6-fe9b-11e5-91ec-4465c76bd2d1.png)

**Comment by jaquadro** [comment]
Slaves don't extend range.  So your far wall is just 1 block out of range of the controller.

**Comment by MechMK1** [comment]
So what exactly do slaves do then? Just serve as a secondary input for automated systems?

**Comment by jaquadro** [comment]
Yes, they are additional input/outputs.  Some setups need lots of them.  This block has caused enough confusion that I should rename it.

**Comment by MechMK1** [comment]
A NEI tooltip on the Slave might help, such as "Additional Input/Output for a drawer network" or similar.

Further, would it be possible to create a network extender block or upgrade for the drawer controller? I'm sorting my rooms chuck-wise, so I use a 14x14 room for storage - barely not enough for one controller.

**Comment by jaquadro** [comment]
Well if you're playing SSP or control the server, you could change the range in the config.  Or you could try to work the controller into the center of your room and connect it to the wall via buried trim blocks.

A network bridge is on my list of things I'd like to do, but I don't know when it will happen.

**Comment by MechMK1** [comment]
I think changing the range in the config will be the most viable short-term solution! Thank you a lot for your help.

And thank you for your great mod.

**Comment by codewarrior0** [comment]
For setups like this, I found it handy to use the drawer key on the controller to lock the entire drawer bank. The TE and EIO item pipes I use will refuse to fill an empty, locked drawer, instead routing the item elsewhere (such as to the following drawer bank, or to an overflow chest). I can still manually insert an item into a locked drawer to set it to store that item.

**Comment by pedrofracassi** [comment]
Is the bridge still planned?
