### ISSUE TITLE
Framing table render crash [1.8.9]

### ISSUE THREAD

**Issue by BBoldt** [jaquadro/StorageDrawers#268]
Happens occasionally when I look towards the direction of my base.

https://gist.github.com/3267386615b5fa7b6000dbda3cb361a4

forge-1.8.9-11.15.1.1808.jar
StorageDrawers-1.8.9-2.6.3.jar
Chameleon-1.8.9-1.1.1.jar

**Comment by jaquadro** [comment]
There's a framing table entity at a position without a corresponding framing table block.  Can you think of any reason this might have happened?

I will add a test to avoid the crash, but it's weird to have a rogue tile entity hanging out.

**Comment by jaquadro** [comment]
Try version 2.6.4.
