### ISSUE TITLE
Cannot get property PropertyEnum - 1.9 all latest versions and forge 1862

### ISSUE THREAD

**Issue by goosezilla** [jaquadro/StorageDrawers#269]
Sorry if this is a TiC issue and not yours but you seen more active than boni for 1.9. 

When crafting drawers in a tinkers construct crafting table I crash when removing them.

http://pastebin.com/zxCvv0AY

**Comment by novasolarius** [comment]
I have a similar issue when trying to craft upgrade... templates, I believe they called. Whichever item you craft with a drawer and eight sticks. Can't even open my world anymore.

**Comment by jaquadro** [comment]
This is supposedly fixed on the Tinkers/Mantle side now (https://github.com/SlimeKnights/TinkersConstruct/issues/2010).  There isn't a published build with the fix yet.

Mantle wasn't caching item model data in a way that was transparent to the item models it wanted to render.
