### ISSUE TITLE
Controller won't connect to hopper

### ISSUE THREAD

**Issue by Gilligan128** [jaquadro/StorageDrawers#277]
so I swear that at first connecting my controller to a Hopper and a chest worked. But then when I moved it it would not accept anything from the hopper. I am wondering if this controller block is borked now due to some glitch

**Comment by jaquadro** [comment]
Can you insert items into the controller by hand (assuming you have said item already in a connected drawer)?  Can't see any reason why a hopper wouldn't push into a controller.  But if the controller can't see drawer slots, the inventory looks empty to the hopper.

**Comment by Gilligan128** [comment]
I tried placing the drawers adjacent, and even attaching them against the controller itself (where the back of the drawer is against the controller) and waited 5 seconds, but nothing has worked thus far. I can use the controller by itself a long as there is a locked or partially filled drawer for that item, atm, it just does not work with the hopper.

**Comment by Gilligan128** [comment]
So, I may need to `Sneak place` the hopper instead of just placing it. I will try this when I get a chance.

**Comment by Gilligan128** [comment]
shift-clicking made the hopper connect. I am all good now, thank you for your quick response.
