### ISSUE TITLE
Crafting station causes crashes

### ISSUE THREAD

**Issue by itayganor** [jaquadro/StorageDrawers#280]
hey,
I just put 8 regular sticks and one 2x2 drawer in a Crafting Station (from Tinker's Construct Mod) and the game crashed. I wasted a few hours on MCEdit trying to figure out what causes the game to crash, and it's probably becuase of the displaying of the items in the crafting station.

minecraft version 1.9

**Comment by jaquadro** [comment]
Try updating to the latest Mantle alpha.  That's where the fix is supposed to be.  Workaround is to disable item display in the tinkers crafting table.

**Comment by WazWaz** [comment]
Yes! Updated TCon and Mantle and crash went away! Phew, thanks!
