### ISSUE TITLE
[1.8.9] Changing Drawer Controller's range does nothing

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#283]
I was about to report a bug where Drawer Controller cannot see past a certain but then I found that this  range is determined in the config file and therefore changeable. However I have tried changing it and it does nothing, the Drawer Controller still doesn't see/detect items in drawer past 12 range.

After restarting the server I have tried breaking the and replacing, using a new controller, I have tried reducing the range limit to 16 instead of my initial 100.

**Comment by jaquadro** [comment]
Looks like a failed merge from 1.7.10.

**Comment by jaquadro** [comment]
Fixed in 1.8.9 and 1.9.4; available now in the latest releases.
