### ISSUE TITLE
Crash with Tinkers' Construct

### ISSUE THREAD

**Issue by FusionLord** [jaquadro/StorageDrawers#285]
There is a crash when the Tinkers' Construct Workbench table tries to render the drawer.
Log: http://pastebin.com/xNS5aKGm
Issue on Storage Drawers: [Here](https://github.com/SlimeKnights/TinkersConstruct/issues/2078)

**Comment by jaquadro** [comment]
As mentioned in referenced issue, you need to update to the latest available Mantle (probably still an alpha release on CurseForge).
