### ISSUE TITLE
MC1.7.10 -- Not rendering Osmium properly

### ISSUE THREAD

**Issue by addrever** [jaquadro/StorageDrawers#290]
When I place osmium blocks into a compacting drawer the ingot and nugget do not show up.  If I place the ingot in all three do.

![2016-05-28_21 12 58](https://cloud.githubusercontent.com/assets/190461/15630825/0ba63f16-2519-11e6-9b69-7d97c130425c.png)
![2016-05-28_21 13 29](https://cloud.githubusercontent.com/assets/190461/15630826/0ba66f72-2519-11e6-8062-2254f5ce927a.png)

I also tried the latest mod version too.

**Comment by addrever** [comment]
I should also mention that when you try and take an ingot or a nugget out it doesn't allow you to.

**Comment by jaquadro** [comment]
Please enable debug logging in the storage drawers options, then try inserting the block.  A bunch of stuff should get printed to the server console.  Copy it into the issue.  A dump of your oredict registry and recipe registry would also be useful.

**Comment by addrever** [comment]
I just tried it and it seems to be working now.
