### ISSUE TITLE
Rendering Block Entity java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by 0Navis0** [jaquadro/StorageDrawers#292]
A strange bug happens when I destroy a framing table and causes Minecraft to crash  http://pastebin.com/3077W3Wz

**Comment by jaquadro** [comment]
I'm not sure if it's the particular way the table is being destroyed, or it's a multiplayer problem or just random.  I've checked in a guard that should prevent a crash (though it's possible you still have a tile hanging out where the game thinks there's an air block).  Will be available in the next releases for 1.8.9 and 1.9.4.

**Comment by jaquadro** [comment]
Should be fixed now in 1.8.9 and 1.9.4.
