### ISSUE TITLE
Compacting Drawer + AE2 severe dupe glitch [1.7.10]

### ISSUE THREAD

**Issue by LezChap** [jaquadro/StorageDrawers#293]
Mod versions:
Storage Drawers 1.9.8
AE2 rv3-beta-6
(tested with clean Forge instance with NEI also included)

Steps to reproduce:
1. Set up two Compacting Drawers on a Drawer Controller.
2. Set up a Storage Bus on the Drawer Controller in a small AE network.
3  Using a Terminal, insert any compactable item into the AE Network (Gold Ingots or nuggets work well).
4. Close the AE Terminal.  One of the Compacting Drawers will be empty, but have the Gold Nuggets/Ingots/Blocks on display in the 3 slots.  The other Compacting Drawer will have a gold block for every ingot/nugget you inserted into the Terminal (tested with full and partial stacks).  Inserting more Blocks/Ingots/Nuggets into the AE Terminal after the dupe will put them in the Empty Compacting Drawer, which will allow you to pull them out and clear that Drawer from being set to the item/displaying icons for gold.  Pull out the blocks you duped as well, and you can repeat the process.  

If both drawers are not completely empty and showing no icons, the dupe doesn't seem to work.  It also doesn't work if you only have one Compacting Drawer available on the Drawer Controller.  If there are 3 empty Compacting Drawers on the Controller, the third one seems to be ignored.  The arrangement/distance from the Controller of the Compacting Drawers did not seem to make a difference, though if a compacting drawer was recently placed/added, sometimes the first dupe attempt failed on the first try.

The above also works if you insert the items via an ME Interface, but using an ME Import Bus and a chest to add items to the ME Network (and store them in the Storage Drawers) seems to work properly and doesn't dupe anything, if that helps you narrow the source of the problem down.

**Comment by Darkosto** [comment]
Can confirm and I'm looking to, hopefully, include this in the next update of Sky Factory 2.5. Is this something you'll be able to take a look at?

Thanks!

**Comment by jaquadro** [comment]
Yeah I'll try to reproduce it.  I just got back from travel though so haven't been able to respond to issues.

**Comment by Darkosto** [comment]
No worries! Just making sure you were able to check it out :) Thanks for the reply!

**Comment by LezChap** [comment]
Just wanted to add I reproduced this running Forge 10.13.4.1614, not that I think that'll make a difference.

**Comment by jaquadro** [comment]
Apologies over how long this took to fix.  May and June have been unusually busy months.

Fortunately it wasn't deeply rooted in AE2 or SD.  Just in the glue code between them.  This is fixed in 1.9.9, and it also shouldn't populate more than one compacting drawer at a time.
