### ISSUE TITLE
[1.9-3.1.7] Unable to left-click items out of drawer in creative

### ISSUE THREAD

**Issue by OhiraKyou** [jaquadro/StorageDrawers#295]
Minecraft 1.9.4
Forge 1.9.4-12.17.0.1951
Storage Drawers 1.9-3.1.7

It was previously possible to click items out of drawers in creative. In 1.9-3.1.7, left-clicking is ignored in creative.

**Comment by jaquadro** [comment]
Unfortunately Forge inserted an event I was using into a very bad spot in the player controller.

It's a complicated workaround.  I can restore the ability to extract items with left-click, but you're also going to get a shower of block destroy particles each time you do it, just like the earliest versions of the mod on 1.7.10.  Don't think I have any good way around that.

**Comment by OhiraKyou** [comment]
At least there's still also item frames for this. I forgot that you could pick items from frames in creative until I saw a video in which someone did. So, don't worry too much about it.

**Comment by jaquadro** [comment]
This is fixed in 3.1.10.  It still has the caveat I mentioned with the particles, but that should be minor compared with not working at all.
