### ISSUE TITLE
[1.8.9+] Storage Drawers' Redstone Upgrade emit a strong redstone signal but do not update adjacent blocks

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#296]
![2016-06-06_14 46 58](https://cloud.githubusercontent.com/assets/8670392/15822410/e4bdfaa4-2bf5-11e6-8b0c-59ea0ff47cf7.png)
![2016-06-06_14 47 03](https://cloud.githubusercontent.com/assets/8670392/15822411/e4bf8dec-2bf5-11e6-8c87-b6b279a3a590.png)

When placing redstone next to a block that adjacent to a Storage Drawer with Redstone Upgrade, the redstone will not get updated to the Storage Drawer's amount of storage.

https://github.com/Tuhljin/Automagy/issues/47#issuecomment-223698787

**Comment by jaquadro** [comment]
Bug exists back to 1.7.10.  Fixed in 1.7 and 1.8 dev, will also get into 1.9 shortly.  Will be fixed in the next release.

**Comment by jaquadro** [comment]
Fixed and available in all three game version.
