### ISSUE TITLE
WAILA + Storage Drawers malfunction

### ISSUE THREAD

**Issue by B0bbyD0llar** [jaquadro/StorageDrawers#297]
i have installed:
MC: 1.9 Forge: 12.16.1.1938 Storage Drawer: 3.1.6 WAILA: 1.7.0B2
if i look at an Storage Drawer WAILA show only "Storage Drawer" instead the content and the amount of this drawer. WAILA integration is activated. What can i do?

**Comment by jaquadro** [comment]
WAILA integration is not active in 1.9 yet.  I will try to make sure it's re-activated in the next 1.9 release.

**Comment by B0bbyD0llar** [comment]
That would be great. Thanks a lot for your good work.

**Comment by Drehverschluss** [comment]
Indeed that would be more than great hehe

Going through the chest just by the picture is a bit a pain right now :)

**Comment by Renadarain** [comment]
Hi :)

Is there any chance of this being reimplemented in the 1.9.4 version?

Thanks,
Renada

**Comment by jaquadro** [comment]
This is available again in 3.1.8.  Note I am only maintaining the latest 1.9 version: 1.9.4.

**Comment by Renadarain** [comment]
Thank you for the update :)

Regards,
Renada
