### ISSUE TITLE
[1.9.4] Drawer upgrade trim doesn't display

### ISSUE THREAD

**Issue by HieronGaming** [jaquadro/StorageDrawers#298]
Using StorageDrawers-1.9-3.1.7.jar and Forge 12.17.0.1963.  The drawer does not show or indicate the upgrade on the trim.

**Comment by jaquadro** [comment]
Storage upgrades no longer change the trim, as of MC 1.8+.  Always felt this looked pretty hideous and tied basic storage upgrades to your tolerance for extra bling.  It also has unclear meaning when you can stack the storage upgrades.
