### ISSUE TITLE
[1.9.4] Storage Drawers do not accept ore-dictionary items

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#299]
When manually inserting items in a storage drawer it will automatically convert it, this is all good and well but it does not accept ore-dictionary items insertion when using pipes, is this intended or could it be changed to work like right-clicking insert?

**Comment by Moustik2002** [comment]
Hi, encountering same thing here.

**Comment by jaquadro** [comment]
Could you please describe a particular setup where this is failing?  What mod, what pipes, what items that are failing to convert, etc.  Preferably with a screenshot.

I did a quick test with Neotech pipes and copper ingots from different mods.  They converted just fine via pipe.

**Comment by Xiaminou** [comment]
Ender IO's item conduit feeding into 3 modular storage (RF Tools) and a Storage Controller, Storage Controller being the highest priority has compacting drawers for each metal type from Substratum. The Copper Ingots are from Industrialcraft and will not go into the Storage Controller, they will go in the modular storage instead.
![2016-06-23_15 37 15](https://cloud.githubusercontent.com/assets/8670392/16309275/71549e26-3968-11e6-8b66-ec545856865d.png)
![2016-06-23_15 37 23](https://cloud.githubusercontent.com/assets/8670392/16309276/7155fbe0-3968-11e6-967f-b844743b43ea.png)
![2016-06-23_15 37 25](https://cloud.githubusercontent.com/assets/8670392/16309277/71577fce-3968-11e6-88cf-617029da2149.png)
![2016-06-23_15 37 36](https://cloud.githubusercontent.com/assets/8670392/16309278/715752c4-3968-11e6-93c3-2bec7750d349.png)
![2016-06-23_15 37 45](https://cloud.githubusercontent.com/assets/8670392/16309279/71590916-3968-11e6-96db-3a14906ffbb3.png)

Simple tests:
![2016-06-23_17 34 00](https://cloud.githubusercontent.com/assets/8670392/16309421/f61d7c40-3968-11e6-9594-d9de46aa1a08.png)
![2016-06-23_17 34 03](https://cloud.githubusercontent.com/assets/8670392/16309418/f6119740-3968-11e6-95bf-4b08a0ce4fb1.png)
![2016-06-23_17 35 37](https://cloud.githubusercontent.com/assets/8670392/16309420/f611e420-3968-11e6-881c-227cf85d95ac.png)
![2016-06-23_17 35 38](https://cloud.githubusercontent.com/assets/8670392/16309419/f6117936-3968-11e6-92c8-3a5b02410a6d.png)
![2016-06-23_17 37 26](https://cloud.githubusercontent.com/assets/8670392/16309491/3342c5ee-3969-11e6-8305-bc245195596d.png)
![2016-06-23_17 37 28](https://cloud.githubusercontent.com/assets/8670392/16309492/334cbb26-3969-11e6-8759-09fd2da2a265.png)

Works only when inserting directly into the Compacting Drawer, inserting into the Drawer Controller will not convert Ore Dictionaries and therefore is not working.

**Comment by Xiaminou** [comment]
Actually Ender IO pipes won't work even if you pipe directly in the Compacting Drawer:

![2016-06-23_17 52 34](https://cloud.githubusercontent.com/assets/8670392/16310057/4da883fe-396b-11e6-8a85-48d229ae7b9f.png)
![2016-06-23_17 52 36](https://cloud.githubusercontent.com/assets/8670392/16310058/4dbbad62-396b-11e6-951a-a10f48ae1f4c.png)

**Comment by jaquadro** [comment]
Got around to verifying this.  The majority of transport systems (I've tested hoppers, NeoTech, and ExtraUtilities2) seem content to try inserting items into each slot until they find a match.  EnderIO is probably examining the contents before making a decision to attempt insertion or not.

Which means sadly I need to revert to some of my ugly 1.7.10 tricks to get this to work.

**Comment by jaquadro** [comment]
This should now be fixed in 3.2.5
