### ISSUE TITLE
Shift right-clicking Drawers don't open GUI when off-hand has item and primary hand doesn't

### ISSUE THREAD

**Issue by Drullkus** [jaquadro/StorageDrawers#301]
Mod Filename - StorageDrawers-1.9-3.1.7

Modpack - FTB Unstable 4.0.7

I tried opening a drawer with steak in the off-hand and primary hand empty. When I tried opening the drawer, I attempted to eat the steak instead. Unsure if this is supposed to happen.

**Comment by jaquadro** [comment]
Fixed in 3.1.10
