### ISSUE TITLE
1.9.4 Creative Vending Upgrade can be removed by non ops

### ISSUE THREAD

**Issue by EchoDel** [jaquadro/StorageDrawers#302]
It is possible to access the UI of the drawer as a non op while it has the creative vending upgrade. The upgrade can then be removed from the drawer and placed in any other drawer, giving infinite of any items wanted.

**Comment by jaquadro** [comment]
This is fixed in 1.7.10 now (any player, op or otherwise, will need to be in creative mode to remove the upgrade).  It will be forwarded to 1.8 and 1.9 shortly.

**Comment by jaquadro** [comment]
Fixed and available in all three game versions.
