### ISSUE TITLE
Texture on the back of framed drawers is flipped

### ISSUE THREAD

**Issue by Prospector** [jaquadro/StorageDrawers#304]
As you can see, the block I have selected is the back of the drawer, and the texture is flipped compared to the block to the right which is correct.

![2016-06-19_21 43 14](https://cloud.githubusercontent.com/assets/6166773/16183486/301ff79c-3667-11e6-86e6-e9aaa14c63f2.png)

**Comment by jaquadro** [comment]
Fixed in the latest version of Chameleon.
