### ISSUE TITLE
[1.9.4] [3.1.9] Crash on Server Startup

### ISSUE THREAD

**Issue by Galaxy2Alex** [jaquadro/StorageDrawers#306]
Game is crashing on startup with pointing to Storage Drawers. My guess would be that it's something Forge related, however, I am not a dev. Only happens with 3.1.9, 3.1.8 works fine.

http://paste.ubuntu.com/17790880/

Thanks for everything!

**Comment by RealGrep** [comment]
Can confirm. Same here.

**Comment by Gepett0** [comment]
Same problem on this dedicated server.

http://pastebin.com/eL9wXweD

**Comment by kreezxil** [comment]
Confirmed here as well:

Issue:  storage-drawers-1.9.4-3.1.9 crashes dedicated Forge 1.9.4 build 1987 on startup

crash report:
https://gist.github.com/f26fa0148cd8c7923ee088b3d59e2d20

fml server latest:
https://gist.github.com/faff0152504272a1fa08d69bd79b33a2

**Comment by Xiaminou** [comment]
confirmed: http://pastebin.com/m8tt6SHf

**Comment by jaquadro** [comment]
Thanks, I've rolled back the release from CurseForge.  Will try again tonight.

**Comment by jaquadro** [comment]
Version 3.1.10 is up on GitHub and CurseForge and should be quite a lot less crashy.  Sorry for the bad release.

**Comment by SnowShock35** [comment]
Thanks for the fix @jaquadro :heart:
