### ISSUE TITLE
[1.7.10] Iron bars / Dark iron bars being stored as one another.

### ISSUE THREAD

**Issue by gillyobeast** [jaquadro/StorageDrawers#308]
version: 1.7.10-1.9.9
in FTB Sky Factory 2.5.3

hey, it appears that i can put iron bars in a dark iron bars (from ender io) drawer, and it count as such. it works the other way too. works in every drawer, including the natura ones

**Comment by jaquadro** [comment]
Sounds like they're both registered in the ore dictionary as iron bars and that's the end of it.  As far as the mod is concerned, they look equivalent.

You could blacklist the ore dictionary key that they register to using SD's MineTweaker API, or you could give iron bars and black iron bars their own extra ore dictionary key, which would also tell the mod to not treat them as equivalent.
