### ISSUE TITLE
[1.10.2] Disabling compacting drawers or framed drawers crashed forge

### ISSUE THREAD

**Issue by Rostepher** [jaquadro/StorageDrawers#313]
When using the most recent version of the StorageDrawers ([1.9.4-3.2.0](http://minecraft.curseforge.com/projects/storage-drawers/files/2314837)) mod and the Chameleon ([1.9.4-2.1.6](http://minecraft.curseforge.com/projects/chameleon/files/2314835)) library from curseforge and disabling the compacting drawers or the framed drawers it causes Forge (1.10.1-12.18.1.2011) to crash. I removed all other mods to ensure it was a problem with StorageDrawers, here is the [pastebin](http://pastebin.com/yJTnVMtu) of the crash log. Here is the [StorageDrawers.cfg](http://pastebin.com/qJh66bnN) config file that I am using.

**Comment by jaquadro** [comment]
Fixed in latest Chameleon (2.1.7)
