### ISSUE TITLE
ClassCastException on trying to render air. [1.9.4]

### ISSUE THREAD

**Issue by Claycorp** [jaquadro/StorageDrawers#314]
http://pastebin.com/MZAt4n62
I have a slight feeling this might have something to do with mods being removed while items were in the drawers.

**Comment by jaquadro** [comment]
Nope, that's not it.

Most frustrating, it looks like the physical state of the world is changing in the middle of executing one pass of the renderer.  E.g. I ask the world what block exists at the spot and it says "it's a drawer".  Then a bit further down I ask it again and it says "nope changed my mind it's air".

I'll see what I can do.

**Comment by jaquadro** [comment]
Try this one: https://github.com/jaquadro/StorageDrawers/releases/tag/sd-3.2.1

**Comment by Claycorp** [comment]
I'm not 100% sure how it's getting triggered. So I can't really test it in SSP and the crash is happening while on a server with 30+ people on per day... I could be just flying by someone's house then crash and be fine for hours.

**Comment by jaquadro** [comment]
I think it was a rare race triggered by someone breaking a drawer, or maybe related to a chunk loading or reloading.  By most unfortunate luck, the drawer was there when it started to render the items, and then it wasn't.

**Comment by Claycorp** [comment]
Makes sense. Thanks for the quick reply and possible fix! Sorry I can't really test it. I will make sure to update you on it when possible.

**Comment by jaquadro** [comment]
Going to assume this is fixed.
