### ISSUE TITLE
[1.8.9] Crash when disabling settings in "General"

### ISSUE THREAD

**Issue by SDXC** [jaquadro/StorageDrawers#316]
Maybe this applies to newer versions too:

When disabling some of the general settings (e.g: Enable Creative Upgrades), Minecraft crashes after restarting. It may be connected to a model rendering problem if a model is being disabled.

[crash-2016-07-17_15.42.28-client.txt](https://github.com/jaquadro/StorageDrawers/files/367859/crash-2016-07-17_15.42.28-client.txt)

**Comment by jaquadro** [comment]
Fixed in latest Chameleon for 1.8 and 1.9/1.10
