### ISSUE TITLE
[Feature Request/PR Suggestion] Less restrictive TileEntityController

### ISSUE THREAD

**Issue by Belgabor** [jaquadro/StorageDrawers#317]
For my mod [Drawers & Bits](https://github.com/Belgabor/DrawersBits) I'd like to implement an enhanced drawer controller. If possible I'd very much like to not have to reinvent the wheel, so would it be possible to open up some of the methods and variables from private to protected in the TileEntityController class so I can subclass it without unnecessary code duplication?

If you are amenable I'll see what I need and PR the changes.

**Comment by jaquadro** [comment]
Cool mod.  I'll be sure to check it out when I finally get around to playing with 1.10 and Chisels & Bits.

Sure, the controller TE can be reworked to be more amenable to extension.  Go ahead and submit a PR and I'll review it and maybe discuss some of those changes.

**Comment by Belgabor** [comment]
Sorry, it took me a while. I don't actually need a lot of changes, here's what I believe is sufficient:
https://github.com/Belgabor/StorageDrawers/commit/3441174b1ce5cdbdba2e1290e44cb4413f910796

**Comment by jaquadro** [comment]
I think this is okay, but there is a chance the internal workings of the controller will change.  I'll try to mention in advance if it happens.

**Comment by Belgabor** [comment]
That would be great.
I am aware of the danger and I warned people that my mod might break on your updates =)

Oh, do you want me to PR the changes or will you copy them into your code directly?

**Comment by jaquadro** [comment]
Go ahead and create the PR

**Comment by jaquadro** [comment]
Oh yeah, this is in the latest release.
