### ISSUE TITLE
Duping with rftools storage scanner and storage drawers.

### ISSUE THREAD

**Issue by RogueShadow** [jaquadro/StorageDrawers#318]
https://github.com/McJty/RFTools/issues/634

When the storage scanner tries to craft with storage drawers, it dupes items. Seemingly but not always apparently filling the drawer to capacity whatever that may be.

Unsure if this is storage drawers fault. Haven't been able to test it with some other method yet.

**Comment by Naosyth** [comment]
Also, this only happens if the drawer has > 1 stack of items in it

**Comment by jaquadro** [comment]
This was solved on the RFTools side.  Thanks for filing it on both projects.
