### ISSUE TITLE
crash using hopper into drawer controller

### ISSUE THREAD

**Issue by bdudek** [jaquadro/StorageDrawers#330]
i have a server crash when someone uses a hopper to input into a drawer controller 

crash report
http://pastebin.com/jggcZNpj

**Comment by ghost** [comment]
i got the same kind of crash in combination with enderio 

crash report 
http://pastebin.com/m8xM9ZwN

**Comment by namstor** [comment]
Same here with EnderIO as well

crash report
http://pastebin.com/BFeEJGJt

**Comment by jaquadro** [comment]
Sorry about that.  3.2.6 is up now which fixes this.
