### ISSUE TITLE
Items will not enter a new drawer once full

### ISSUE THREAD

**Issue by JoeSmith7498** [jaquadro/StorageDrawers#331]
Hi, this has probably been looked at before but couldn't find it anywhere.  When I put cobble or any other Item I have a large quantity of into my drawer controller it fills up to 256 of the item.  I can manually put the item in another drawer and it fills another 256 of that item but that takes a lot of time and my automated farms are beginning to produce a lot of items.  Is there anyway to automatically fill up new drawers?  Thanks

**Comment by GAJinWoo** [comment]
I have also encountered this problem. Here is a video that I made that shows the problem. https://www.youtube.com/watch?v=aAS3oeIvGn8

**Comment by GAJinWoo** [comment]
Did some testing and it appears that the 2x2 boxes are the problem. Using any other drawer seams to work for me

**Comment by jaquadro** [comment]
Should be fixed in 1.7.10-1.10.2 (never mind the unfortunate collision with the MC version number .. this is definitely for 1.7.10 only).

As far as I can tell, this wasn't an issue in the later ports.
