### ISSUE TITLE
[1.10.2] CraftTweaker Support

### ISSUE THREAD

**Issue by utoc** [jaquadro/StorageDrawers#335]
Hi!

I noticed in 1.7.10 you had MT support and after a [quick search](https://github.com/jaquadro/StorageDrawers/search?utf8=%E2%9C%93&q=tweaker) it seems like some of the code is still there.. is it meant to be functional at this point though?

Trying the following:

```
val basalt = <ore:basalt>;
basalt.add(<quark:basalt:0>);
mods.storagedrawers.OreDictionaryWhitelist.add(basalt);
```

And getting the error:

```
ERROR: tconstruct.zs:17 > No such member: storagedrawers
ERROR: Error executing tconstruct.zs: minetweaker/api/oredict/IOreDictEntryAny

```

Running StorageDrawers 3.2.6 on FML 2075

Thanks!

**Comment by jaquadro** [comment]
So the reason CraftTweaker support still hasn't shown up is they have no maven repository (that I'm aware of), and I didn't really want to make fetching their jar a build requirement.

All of the functionality that was provided through MineTweaker can now be set in the storage drawers config file.

**Comment by Adam-Kay** [comment]
Where/how?

[Current Config File](http://pastebin.com/9YsAC3G0)

I have no idea where to even make this modification. How could I change a compaction recipe, for example? 
Is there a guide anywhere?

**Comment by jaquadro** [comment]
After you update to the latest version, it should populate the config file with some default sections for that.  They can also be edited from the Forge config GUI.

I posted this as example in another issue, for adding compacting recipes for logs/planks:

```
registries {
  S:compactingRules <
      minecraft:log:0, minecraft:planks:0, 4
      minecraft:log:1, minecraft:planks:1, 4
      minecraft:log:2, minecraft:planks:2, 4
      minecraft:log:3, minecraft:planks:3, 4
      minecraft:log2:0, minecraft:planks:4, 4
      minecraft:log2:1, minecraft:planks:5, 4
   >
}
```

Each line is a compacting rule in the form: biggerMaterial, smallerMaterial, conversionAmount.  Items are in the form: domain:item:meta.

**Comment by jaquadro** [comment]
Well go figure, right after I add native config support, I find out that CraftTweaker recently setup a maven repo.  Sooooo CraftTweaker support is back in, along with native config.  Options for your options.
