### ISSUE TITLE
[Feature Request] Label-upgrade

### ISSUE THREAD

**Issue by accessdenied0** [jaquadro/StorageDrawers#336]
Hello @jaquadro ,

I might do a terrible request here but I always wanted to have a upgrade for your mod which shows the number of stacks (e.g. 2x64 +5) or the name of the Item/Block which is stored.

I'm aware there is actually a Level-emitter upgrade which shows the filling level in %, but in some cases it would be need to have an exact number. Also I know there is a compat to WAILA to get all the information you need, but it is sometimes to dependent. 

If the label isn't fitting or looks weird I can think of a toll like a monocle as alternative, which only shows the information like a "ghost label" if you directly look at the drawer. (this might also be the better solution in cases of 2x2 Drawers...)

I think this suggestion might be already made, but so far I looked through your issues I didn't found one.

If you don't like this idea or your never really wanted something like this just close it up,

Thank you for your time,

access_denied

**Comment by jaquadro** [comment]
This is now available in 3.5.0.  I was a bit torn on the direction to take, but I opted to add this in the form of another key.  That vastly lowers the barrier to using the feature, and makes it easy to toggle at will (since all keys are actionable on controllers).
