### ISSUE TITLE
[1.10.2] Compacting drawers not registering EnderIO nuggets when block or ingots used to fill drawer.

### ISSUE THREAD

**Issue by MrNinja93** [jaquadro/StorageDrawers#338]
Compacting drawers dont register both EnderIO nugget variants of metals if you insert either the ingot or block form of those metals to first populate a compacting drawer, if you use the nugget however it populates as it should.  

Left drawers populated with block form, center with ingot and right with nugget

![2016-09-04_03 22 27](https://cloud.githubusercontent.com/assets/21979276/18228647/35320f94-724f-11e6-8c21-a3770133d13b.png)

**Affected Versions**

Storage Drawers-1.10.2-3.2.6
EnderIO-1.10.2-3.0.1.101

**Comment by jaquadro** [comment]
Can you enable debug logging in SD's options, and then copy what gets printed to the console/log when you try inserting the ingot?

**Comment by MrNinja93** [comment]
Pastebin of the console log http://pastebin.com/f6vBcHLE

edit: cut out extraneous stuff and labelled what each was just in case.

**Comment by jaquadro** [comment]
Fixed in 3.2.7.  I'm sure there's a few others this will catch too.
