### ISSUE TITLE
Storage Drawer crafting error

### ISSUE THREAD

**Issue by ArminaHime** [jaquadro/StorageDrawers#342]
Hi, when I tried to craft a storage drawer in the Extra Utilities 2 mod crafting table my modpack froze and crashed with this report. Also when i try to load the world in which the crash happens it freezes and crashes again with the same outcome. I will also be submitting this to Extra Utilities 2. Thank you for taking time to help with this issue.

http://pastebin.com/EF0fEjyC

https://gist.github.com/anonymous/e557acdd4571b1b96ffc9b12beb22e12

rwtema/extrautilities#985

**Comment by jaquadro** [comment]
It looks like EU is not passing through an appropriate blockstate for the item.

At best, I could make this render invisible on my end.

**Comment by jaquadro** [comment]
Well I don't know if EU ever fixed the problem on their end, but this should avoid crashing in 3.3.0.  It may or may not render something that looks correct.
