### ISSUE TITLE
[1.10.3] Upgrade templates are uncraftable

### ISSUE THREAD

**Issue by Revemohl** [jaquadro/StorageDrawers#344]
That version fixed the issue regarding packed-up drawers being used for crafting, but... oops.

Just checked on a pack that had only NEI and SD, with brand new configs. No recipes at all for upgrade templates.

**Comment by jaquadro** [comment]
They're craftable, but now it looks like I need to write a whole NEI handler to get their recipes to show.

**Comment by Darkosto** [comment]
I just discovered this, too. Not to rush you, but do you have an ETA? I need to do an update to SkyFactory for this fix.

**Comment by jaquadro** [comment]
I've added the NEI handler for this in 1.10.4.
