### ISSUE TITLE
[1.10.2] [Bug] D-Sync issue when upgrading drawers

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#345]
Hello,

I believe I've found a bug for Storage Drawers for Minecraft 1.10.2, here are the details. . . 
### Important Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.1.2094
- Chameleon 1.10-2.1.7
- Storage Drawers 1.10.2-3.2.7
### Issue Description

When right-clicking a drawer with drawer upgrades, it will continue (to appear) consuming upgrades despite it being full. However, the items are not being deleted they just disappear until you update the inventory slot they're in. 
### Steps to Reproduce
1. Place a drawer down
2. Equip X amount of drawer upgrades (More than 5)
3. Right click them on the draw, even after it says there are no slots available (At this point they should appear to disappear.) 
4. Open your inventory and double click the slot they were in. (The X amount of upgrades that didn't fit into the drawer should reappear in the stack.)

**Comment by jaquadro** [comment]
Fixed in 3.4.2
