### ISSUE TITLE
[1.10.2] Crashing interacting with drawer

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#348]
I'm setting up a dev enviroment with Storage Drawers and a couple others mod but I can't interact with the Oak Drawers. The log say something related to the security system

Log: [pastebin.com](http://pastebin.com/H03cTf69)

**Comment by raoulvdberge** [comment]
This was actually caused by RS having an out of date version of the Storage Drawers API. This is fixed now, and can be closed.

@jaquadro Does the mod have a maven repo for the API?

**Comment by jaquadro** [comment]
There isn't.  I looked into it briefly and never figured it out.

I also thought the package-info stuff stopped this from happening?  Or maybe that doesn't apply in a dev environment.
