### ISSUE TITLE
[Bug] Game crashes when trying to add Environmental Tech Basalt to 1x1 storage drawer.

### ISSUE THREAD

**Issue by gkuba** [jaquadro/StorageDrawers#352]
When ever I try to add the Environmental Tech Basalt to a storage drawer of any type /  wood type it crashes to desktop with the following crash log. 

http://pastebin.com/im1gW0N3

**Comment by jaquadro** [comment]
The problem is fixed in code now.  It will be in the next release.

**Comment by jaquadro** [comment]
This should be fixed in 3.3.0.

**Comment by gkuba** [comment]
Thanks, we will give it a try.
