### ISSUE TITLE
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/jaquadro/minecraft/storagedrawers/block/tile/TileEntityDrawers

### ISSUE THREAD

**Issue by Zarepheth** [jaquadro/StorageDrawers#353]
After upgrading to the version 3.3.0 of Storage Drawers, MineCraft crashes during Forge's mod loading process.

[fml-client-latest.zip](https://github.com/jaquadro/StorageDrawers/files/560128/fml-client-latest.zip)

**Comment by jaquadro** [comment]
I'm guessing you have Drawers & Bits installed.  I didn't realize I caused a breaking change with this mod.  I'll let the author know.

**Comment by Zarepheth** [comment]
I have many mods installed, but "Drawers & Bits" is not one of them.
The crash log should list the installed mods - however, the only mod I saw on the Stack Trace was Storage Drawers. Since the stack traces often ended with "xxx... more" additional mods may be involved in the error.

**Comment by jaquadro** [comment]
D&B was what crashed my CurseForge install.

The log is implicating Chameleon.  Your Chameleon is out of date, so try installing the latest of that first.

**Comment by Zarepheth** [comment]
How did you slip in a Chameleon update without me noticing? Anyway, I've updated Chameleon and returned the updated Storage Drawers to service, but I won't be trying them out until tomorrow afternoon or evening (I need some sleep...)

**Comment by Zarepheth** [comment]
Well, the Chameleon update (from August) combined with the most recent Storage Drawers update (from Today) seemed to work quite well. I update Storage Drawers with today's update before playing this evening, so I did not see whether updating Chameleon alone was sufficient to fix the error.
