### ISSUE TITLE
Crash when putting Sulfur ore in drawer: NPE at OreDictRegistry.getModId

### ISSUE THREAD

**Issue by Lothrazar** [jaquadro/StorageDrawers#354]
I was trying to deposit "Sulfur" from the mod "Substratum"

It has the ore dict name "dustSulfur" 

http://pastebin.com/LGXhXCDv

**Comment by jaquadro** [comment]
Try version 3.3.0

**Comment by Lothrazar** [comment]
ok thanks, yeah the modpack might not have had the latest version
