### ISSUE TITLE
How to compile the Packs(BiomesOPlenty,Misc,Natura)

### ISSUE THREAD

**Issue by barecool** [jaquadro/StorageDrawers#356]
Hi 

Im having trouble compiling the Packs on your project, can you tell me how i can get them to compile with gradle. 

im trying to update them to 1.10.2

**Comment by Deshiba** [comment]
I'd like the use the BOP pack in 1.10.2 as well.

**Comment by jaquadro** [comment]
The existing pack projects are dead.  They are being replaced with a single dedicated mod to unify all the pack support.

That repoistory now exists here: https://github.com/jaquadro/StorageDrawersExtras, and it's far enough along that it's compilable with Natura drawers support.  I expect the first release within a week, maybe including BOP and Forestry and some misc variants as well.  Depends how much those mods changed.

**Comment by Deshiba** [comment]
Thanks for the reply.

**Comment by jaquadro** [comment]
https://minecraft.curseforge.com/projects/storage-drawers-extras The first release it out, with Natura/Forestry/BOP support
