### ISSUE TITLE
[bug]cant insert than 1 stack of itens on the drawer

### ISSUE THREAD

**Issue by Tsukiumy** [jaquadro/StorageDrawers#357]
version 3.4.0
forge 2118
after the last update, i become unable to insert more than a stack of itens on empty drawers, if it is already with more than a stack it works fine, but when empty, the bug happens.
made the test with just the mod and JEI and the bug still happens.
just as a note, only non upgraded drawers, just tested with upgrades, and it works normal.
note*: even after removing upgrades it works, but a never upgraded drawer only acepts one stack and make it seems like all the itens are put in the drawer, but after some inventory update, all itens return to the slots they are in previously
note**: one more test, if you tape it, break and replace, the drawer works normal
note***:just as a question, but its intended that removing upgrades from a drawer make it void all the itens that are in excess, shoudn't it makes the upgrade unremovable, i see that it wont destroy the itens if you are still in the gui, but after you leave, it updates the quantity.
ps: sorry for any english mistakes, not my main lang.

**Comment by Xiaminou** [comment]
https://youtu.be/V9Pj9rRNqzU

**Comment by Tsukiumy** [comment]
ty for the video of the bug, my internet realy sux for uploading :3

**Comment by jaquadro** [comment]
Thanks for the reports and video.  Took a little bit to understand what was going on, but I broke the drawers in a subtle way when doing all the performance improvements.

Fixed in 3.4.1.
