### ISSUE TITLE
1.10.2 Item duping? ft.  Forestry

### ISSUE THREAD

**Issue by wentehcoolest** [jaquadro/StorageDrawers#358]
Placing a survivalist tool will magically give you the broken type w/c can be recycled on forestry's carpenter. So I put the survivalist pick in a drawer it gives me the broken pickaxe.

Should I post this on forestry's side too?

**Comment by jaquadro** [comment]
After looking at it, I don't think you need to open an issue with Forestry.  When converting to Minecrafts "handedness", I unknowingly changed item removal process slightly.

This is fixed in source now; will be included in the next release.

**Comment by jaquadro** [comment]
Fixed in 3.4.1.
