### ISSUE TITLE
Invert shift behavior is broken (again?)

### ISSUE THREAD

**Issue by ZigTheHedge** [jaquadro/StorageDrawers#359]
Hello, guys!

B:invertShift=true
doesn't do anything in 3.3.0

**Comment by jaquadro** [comment]
It was part of a recent refactor.  Pretty sure it was still working when I checked.  SSP or SMP?

**Comment by afdw** [comment]
SMP with Sponge on server

**Comment by jaquadro** [comment]
Fixed in 3.4.2

**Comment by ZigTheHedge** [comment]
Fixed but not entirely. When server shuts down, but client doesn't, shift gets inverted back. 
How to reproduce:
1. Log in to the server
2. Shutdown the server (keep client opened)
3. Restart the server
4. Connect to the server
