### ISSUE TITLE
manual input in drawers seems to be broken

### ISSUE THREAD

**Issue by faceofcat** [jaquadro/StorageDrawers#360]
at least in the ftb infinity lite 1.10 pack using SD 1.10.2-3.4.0...
can't place more than one stack of any item in a drawer.

haven't tried drawer controllers or other ways to "automate" inputting items.

**Comment by jaquadro** [comment]
Was fixed last night in 3.4.1, give it a try.  The timing of the FTB launch locking in that version was unfortunate.

**Comment by faceofcat** [comment]
yes it was... sorry...

the new FTB works perfectly too.

thanks!
