### ISSUE TITLE
Startup crash in StorageDrawers-1.10.2-3.4.4.jar

### ISSUE THREAD

**Issue by MentalMouse** [jaquadro/StorageDrawers#363]
When I tried to upgrade from StorageDrawers-1.9.4-3.2.0.jar to  StorageDrawers-1.10.2-3.4.4.jar, I started crashing on startup.  Switching back let me start up without incident.

Crash report: https://www.dropbox.com/s/pnw1xsed806r5ma/Storage-Drawers-151116.txt?dl=0

**Comment by jaquadro** [comment]
Update Chameleon

**Comment by MentalMouse** [comment]
thanks!
