### ISSUE TITLE
NIE at server startup

### ISSUE THREAD

**Issue by xannor** [jaquadro/StorageDrawers#364]
I am getting a null item exception at server startup.

Crashlog:
https://gist.github.com/xannor/84710e94fe6417c61b639fed759d34e2

If you want the full log from the last run I can provide that as well.

**Comment by jaquadro** [comment]
Thanks, it was a stupid little oversight.

Try version 3.4.6.

**Comment by xannor** [comment]
If you mean 3.4.5, yes I just updated to it and the server starts now.

**Comment by jaquadro** [comment]
Yeah I confused it with 10.0.6.  Cool.
