### ISSUE TITLE
Buildcraft Robot Dupe with Storage Drawers

### ISSUE THREAD

**Issue by Sannity** [jaquadro/StorageDrawers#365]
Hello!
I've been trying out using build craft robots recently and I came across a dupe bug when the robot gets its item out of the storage drawer. To further test this i made a minecraft 1.7.10, forge 10.13.4.1614 world, with only Storage Drawers and Build craft Installed and made these two videos to show you:

Vanilla Chest(How it usually works): https://www.youtube.com/watch?v=vpzjWOPBP5I&feature=youtu.be
Storage Drawer(The Bug): https://www.youtube.com/watch?v=0Vu-LV7gsS8&feature=youtu.be

**Comment by jaquadro** [comment]
I tried recreating your setup (struggled might be the better term, since I have almost no working knowledge of Buildcraft).

When the lumberjack robot removed the axe from the 1x1 drawer, it didn't leave a copy in the drawer.  So as far as I can tell, not duping.  Tested with Buildcraft 7.1.18.

**Comment by Sannity** [comment]
Yes I also used Build-craft 7.1.18 and Storage Drawers 1.10.6. I setup a dropbox link to a save where i setup the bug 3 times and it is occurring in this world for me. I set them up exactly the same and pointed out that its not just the single drawer, it is any type of drawer. Tell me how this goes :)

Dropbox save file: https://www.dropbox.com/s/mdhj9xkcb7r74yy/Minecraft%20Bug.zip?dl=0

**Comment by jaquadro** [comment]
Yeah it was a difference in the gate configuration; kind of suspected it would be that.

Found the bug, hopefully the fix doesn't have any other side effects.  Fixed in 1.10.7.

**Comment by codewarrior0** [comment]
For the archaeologists:

The fix has a side effect of causing a Hopper to delete items each tick from the drawer above it under certain conditions. The hopper must be non-full, and it must have nowhere to store the item extracted from the drawer, which can be accomplished by filling the hopper with four full stacks of the item contained in the drawer plus a partial stack of any other item. The items are deleted when the hopper attempts to restore the original stack to the drawer's synthetic output slot, which has already been refreshed as a result of this fix.
