### ISSUE TITLE
Itemducts or transfer nodes into drawer controller stops after 1 drawer is full

### ISSUE THREAD

**Issue by TekkitLite** [jaquadro/StorageDrawers#367]
Hello I was piping into the drawer controller, and everything was going good until the drawer got full.   Then, the item duct refuses to pick up any more of that item, or the transfer node gets jammed.  Any way to fix this- to have it continue to imputed into the next empty drawer?  Using version 1.7.10-1.10.1

**Comment by jaquadro** [comment]
I think this was fixed in 1.10.2.  Latest version is 1.10.6.
