### ISSUE TITLE
Crash when launching server with custom configuration...

### ISSUE THREAD

**Issue by Adam-Kay** [jaquadro/StorageDrawers#368]
I was trying to get the Compacting drawers to recognize Coal → Tiny Coal (from Actually Additions) in the latest DireWolf20 pack for 1.10.2. I had updated Chameleon _(Chameleon-1.10-2.1.8)_ and Storage Drawers _(StorageDrawers-1.10.2-3.4.6)_ beforehand, and it seem I can't run the server without it crashing instantly.

[Crash Log](http://pastebin.com/kVuRQVNS)

[My current config file for Storage Drawers](http://pastebin.com/2DHG7j5h)

The main part in the config being this:
```
registries {
    # Items should be in form domain:item or domain:item:meta. [default: [minecraft:clay, minecraft:clay_ball, 4]]
    S:compactingRules <
        minecraft:clay, minecraft:clay_ball, 4
	minecraft:coal:0, actuallyadditions:itemMisc:10, 8
     >

    # List of ore dictionary names to blacklist for substitution. [default: ]
    S:oreBlacklist <
     >

    # List of ore dictionary names to whitelist for substitution. [default: ]
    S:oreWhitelist <
     >
    B:registerExtraCompactingRules=true
}
```

Where I was attempting to add the _coal_ and _tiny coal_ to the compression recipe.

___It should be noted that everything was working fine until I tried to add this.___

Is there something I've done horribly wrong or is this a bug?

**Comment by jaquadro** [comment]
Ouch, I accidentally referenced a scala class.  The fix is in the latest version of Chameleon, 2.1.9.
