### ISSUE TITLE
Damned "inverted shift" :D

### ISSUE THREAD

**Issue by ZigTheHedge** [jaquadro/StorageDrawers#370]
https://github.com/jaquadro/StorageDrawers/issues/359
Fixed but not entirely. When server shuts down, but client doesn't, shift gets inverted back. 
How to reproduce:
1. Log in to the server
2. Shutdown the server (keep client opened)
3. Restart the server
4. Connect to the server

**Comment by jaquadro** [comment]
Should be fixed in 3.4.7 (pending in CurseForge).  The setting wasn't being sent on subsequent world joins.
