### ISSUE TITLE
craft tweaker API? (mine tweaker fork)

### ISSUE THREAD

**Issue by granack** [jaquadro/StorageDrawers#371]
minetweaker has not been updated in a while, and the owner is directing people to a fork called [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker).
see [StanH's comment](https://minecraft.curseforge.com/projects/minetweaker3?comment=22)

If the only reason the Minetweaker API doesn't work for 1.10 is because Minetweaker isn't up to date, this could be a relatively easy fix to give back that very useful tool.

If it's gone because it was a pain to keep working and you don't want to support it anymore, then no worries.

**Comment by jaquadro** [comment]
It was actually added back to 1.10 branch last week (the only reason it didn't show up sooner is CraftTweaker did not have a maven repo set up).

Incidentally, I gave up on CraftTweaker about 2 days before finding out about the new maven repo, so all the the MineTweakable things also got exposed in SD's native config file.  Now you can use either method.

**Comment by granack** [comment]
@jaquadro You are awesome! thanks!
