### ISSUE TITLE
Crash when starting.

### ISSUE THREAD

**Issue by Zarepheth** [jaquadro/StorageDrawers#377]
I suffered a crash while Forge was processing mods into Minecraft. The crash log is implicating either the Chameleon library or StorageDrawers; since Storage Drawers was recently updated I suspect it is at fault.

The crash log is here: https://gist.github.com/Zarepheth/014c710c3305d0bfc38b58377069bf33.

**Comment by Zarepheth** [comment]
The same crash occurs whether using "StorageDrawers-1.10.2-3.5.5.jar" or "StorageDrawers-1.10.2-3.5.6.jar".
I'll have to go back to "StorageDrawers-1.10.2-3.4.7.jar".

**Comment by jaquadro** [comment]
Update Chameleon.

Probably I should figure out why the version check enforcement isn't working.  But yeah any time Chameleon is implicated in a startup crash it's probably because it's out of date.

**Comment by Zarepheth** [comment]
Typically, I use [Curse's](https://mods.curse.com/mc-mods/MINECRAFT?filter-project-game-version=1.10.2) "Recently Updated" sorting feature to see which mods have been updated since I last updated my mods (usually every day before playing). How did Chameleon get updated without me noticing?

I've downloaded "Chameleon-1.10-2.2.0.jar" and I'll try it out tomorrow.

**Comment by Zarepheth** [comment]
Sorry for the delay. When I next played mine craft with the updated chameleon mod (and yet another update to storage drawers) the launched successfully.
