### ISSUE TITLE
[Suggestion] Way to move drawer with items in it and change face direction

### ISSUE THREAD

**Issue by RedSnt** [jaquadro/StorageDrawers#378]
Title says a lot. I know you can use the dolly from Jabba from what I've read, but if you don't have that mod installed (as in my case at the moment) you're screwed. I do have cardboard boxes from Mekanism which can move the drawers just fine, but they (annoyingly so lol) remember the face direction. So that problem could be solved if I could just 'wrench' it like with a thermal expansion like wrench.

But honestly, an item from this mod which allowed moving the drawers would be the most optimal. But I can see that it would be hard (creatively so) to make an item that resembles the dolly which already exists in Jabba - which is why I'd be content with just the ability to switch the face direction.

**Comment by codewarrior0** [comment]
Which version are you on? In 1.7.10, you can use TE and EnderIO wrenches to rotate the drawers. But I agree, maybe there should be a built-in tool for rotating drawers so you don't have to depend on another mod.

EDIT: I believe the Packing Tape allows you to rotate drawers, but it uses up one of the tape's 9 uses.

**Comment by jaquadro** [comment]
I hate to add yet-another-wrench, but I'm open to tool suggestions.  Packing tape is an awkward way to deal with the issue.

But yeah packing tape has been in for a pretty long time now.  It was added in 1.6.0 in September 2015.  On one hand it's more annoying than a dolly to move one drawer a couple blocks over.  On the other hand, it's really handy for moving a whole bunch to a new house with minimal trips.

**Comment by RedSnt** [comment]
Ohhh my gaaawd. Welp, guess I should read the label on the tin more closely. Sorry for the bother, let's just pretend this never happened. 🏃
