### ISSUE TITLE
Framed Trim textures have gone missing and placed Framed Trim do not show what they've been "painted" with

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#379]
Framed Trim textures have gone missing and placed Framed Trim do not show what they've been "painted" with.
I haven't updated any mods today however when coming back to my house I noticed the Framed Trim I had placed that were "painted" rendered as basic framed trims and upon picking them up they were missing their icon. Actually come to think of it I did remove "Inventory Sorter" and "Item Scroller" because they were conflicting with AE2's terminals interactions but I doubt that has anything to do with it, right?

Here is the most recent log file: [fml-client-latest.txt](https://github.com/jaquadro/StorageDrawers/files/632312/fml-client-latest.txt)

Minecraft: 1.10.2
Forge: 2153
Mods: [list.txt](https://github.com/jaquadro/StorageDrawers/files/632315/list.txt)

**Comment by jaquadro** [comment]
Do you lose the texture if you put new ones down and then come back later?

It sounds like the TileEntity data was lost for those blocks.  I don't see anything in your log mentioning it, but if they're missing entirely rather than damaged, maybe nothing would appear there.  Have you noticed anything else funny in and around that chunk?

**Comment by Xiaminou** [comment]
all the Framed Trims I have have lost their textures and their icons, even the ones that were in the ME Network. Everything else seems in order, I have framed drawers which look just fine.

**Comment by Xiaminou** [comment]
Okay I just teleported back to my house and their texture is back somehow. Still no icons, and I completely forgot to mention I'm actually using a texturepack (f32) but I haven't touched it for a week or so and it's been working fine until now.

**Comment by jaquadro** [comment]
When you say missing icons, are you saying the icons of the framed trim render completely invisible?

Has this persisted through game restarts?  Does it happen if you don't load the texture pack?

**Comment by Xiaminou** [comment]
Here's a couple of screenshot of what it looks like, removing the teexturepack changes nothing. I haven't tried restarting minecraft without a texturepack thought (it takes like 10 minutes for me to change texturepacks)
![2016-12-06_19 16 24](https://cloud.githubusercontent.com/assets/8670392/20937752/96f5d87c-bbe8-11e6-9395-ed1f132a134b.png)
![2016-12-06_19 16 30](https://cloud.githubusercontent.com/assets/8670392/20937753/970b100c-bbe8-11e6-8d77-ec9f41f3e9e5.png)

**Comment by jaquadro** [comment]
That kind of render suggests a problem registering the item model.  Anything relevant in your client startup logs?

**Comment by Xiaminou** [comment]
Well the first log I linked had those lines:
`	Line 23528: [21:31:03] [Client thread/DEBUG] [FML/]: Item json isn't found for 'storagedrawers:customDrawers#inventory', trying to load the variant from the blockstate json
	Line 23529: [21:31:03] [Client thread/DEBUG] [FML/]: Item json isn't found for 'storagedrawers:customTrim#inventory', trying to load the variant from the blockstate json
	Line 23530: [21:31:03] [Client thread/DEBUG] [FML/]: Item json isn't found for 'storagedrawers:framingTable#inventory', trying to load the variant from the blockstate json`

**Comment by jaquadro** [comment]
Oh yeah.  That's actually normal though.  The models are generated by code.

**Comment by Xiaminou** [comment]
Can't find anything else that would be relevant, the logs are the same than the one I linked. I will have to try starting minecraft without a texturepack at some point, but that's for next time I restart minecraft.

**Comment by jaquadro** [comment]
I doubt it's related to texture pack based on the screenshots

**Comment by Zarepheth** [comment]
Since reverting from 3.5.9 to 3.5.8, I've noticed a similar problem. Framed Trim shows with the "unknown" texture (black and magenta squares) in Inventory, Just Enough Items (JEI), and the Framing Table. Once placed, they appear as they should; but it's sort of hard to know what they will look like before placing.

On a related note, since dropping back to 3.5.8 from 3.5.9; JEI no longer shows the Framed Trim recipe. If I have other Framed Trim in my inventory, I can press the JEI recipe key ([R] in my settings) to show the recipe and make more, but it doesn't show in the general item's menu.

**Comment by Xiaminou** [comment]
I think it doesn't show up in JEI because of the missing icon. When this happened to me I tried to find it the option  to show items with missing icons in JEI but couldn't find it.
Or am I going crazy? I remember an option to show/hide items with missing textures. Or was it only in NEI.
I guess the question is, do items with missing textures show up in JEI by default?

**Comment by jaquadro** [comment]
I'm not sure what to advise unless I'm able to run into it myself.  Dropping from 3.5.9 to 3.5.8 should have made no difference.

**Comment by Xiaminou** [comment]
It's a lead worth following though as I think I dropped from 3.5.9 to 3.5.8 too, if that was on of the crashing versions.

Edit: [Here](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2339627) is the changelog where they removed the option to hide missing textures, so I'm assuming now they show up?

I should also mention that I've recently come across a more or less similar bug with Ender IO, where their Pressurized Fluid Tank does not show up in JEI. And it does not have a missing texture.

**Comment by jaquadro** [comment]
If anything, this might have been a Chameleon problem.  Try 2.2.2.

There was a regression to the main model builder in 2.2.0.  I don't know for sure if it could cause this, but if you updated from an earlier version of Chameleon than that, it would be telling.

SD 3.5.10 is also available but it's just a properly compiled version of 3.5.9.

**Comment by Xiaminou** [comment]
Still happening with Chameleon 2.2.2 and SD 3.5.11.

**Comment by jaquadro** [comment]
I lost sight of this issue being specifically about trim and not drawers in general.

I noticed that the framed trim block was absent from the creative menu.  That may have also prevented its item renderer from getting registered, due to how Chameleon manages that.

Give 3.5.12 a try and let me know.

**Comment by Xiaminou** [comment]
Yup, it worked, well done.

![2016-12-14_12 04 07](https://cloud.githubusercontent.com/assets/8670392/21179873/5b8f09f2-c1f6-11e6-8744-d2f3d7b56955.png)
![2016-12-14_12 04 10](https://cloud.githubusercontent.com/assets/8670392/21179874/5b90b518-c1f6-11e6-8b7a-d73a77192349.png)

**Comment by Zarepheth** [comment]
I'll second that opinion; version 3.5.12 fixes the missing Framed Trim icon in Inventories and JEI.
