### ISSUE TITLE
[1.10.2] Using Controller Slave without a Controller causes a crash

### ISSUE THREAD

**Issue by DrParanoia** [jaquadro/StorageDrawers#380]
Hi there! Well the title says it all :D

Steps to reproduce:
1 - put some drawers
2 - place a Controller Slave near the drawers
3 - place a hopper on top of the slave
4 - place items into the hopper
5 - crash

Also you can do this:
1 - put some drawers
2 - place a Drawer Controller near the drawers
3 - place a Controller Slave in the system
4 - place a hopper on top of the slave
5 - place items into the hopper (items start transferring)
6 - remove the Drawer Controller
7 - crash

Hope that this information is helpful ^^

**Comment by jaquadro** [comment]
Are you on the latest version?  There was a slave crash that was fixed a while ago

**Comment by DrParanoia** [comment]
Oh! I am really sorry! Was using FTB pack 1.10 and it has Storage Drawers 3.4.4. Updated to 3.4.5 and it fixed the issue! :D I can't update past 3.4.5 though since it crashes on startup.

**Comment by jaquadro** [comment]
If it's crashing past that, you might need to look for a Chameleon update too

**Comment by jaquadro** [comment]
And Drawers & Bits, if you happen to be using that mod

**Comment by DrParanoia** [comment]
Updated Chameleon and now everything works with new Storage Drawers. thanks man! You are the best!
