### ISSUE TITLE
Crash 1.10.2 when opening world

### ISSUE THREAD

**Issue by MoonCutter2B** [jaquadro/StorageDrawers#384]
got a crash when I opened my 1.10.2 world.

log at:
https://dl.dropboxusercontent.com/u/58751759/crash%20Storage%20drawers.txt

- using StorageDrawers-1.10.2-3.5.9 on SSP
- have a very recent forge, but it looks like there is an even newer one. Will try that and update this issue with results.

edit: latest Forge 2185 didn't help 

edit 2 - reverting to prev version helps

**Comment by desvandev** [comment]
x2, I had the same crash.

**Comment by Xiaminou** [comment]
Yep looks like the latest version of storage drawer crashes. Just rollback to the previous one.
[crash-2016-12-10_17.46.55-server.txt](https://github.com/jaquadro/StorageDrawers/files/643908/crash-2016-12-10_17.46.55-server.txt)

**Comment by jaquadro** [comment]
That's really weird.  It must not have recompiled correctly.

**Comment by Xiaminou** [comment]
well there's only one way to find out.

**Comment by Zarepheth** [comment]
I'm suffering a similar error, but my crash log's stack trace differs from both of the above. In my case, the crash occurred as I teleported into my home (Journey Map's teleport feature). Prior to that no Storage Drawer blocks were present in any loaded chunks.

[crash-2016-12-10_13.18.17-client.txt](https://github.com/jaquadro/StorageDrawers/files/644001/crash-2016-12-10_13.18.17-client.txt)

On Curse, I see that the active version of Storage Drawers for Minecraft 1.10.2 has been reverted from 3.5.9 to 3.5.8.

**Comment by Xiaminou** [comment]
the error is the same, most likely the only reason you didn't crash as you entered the world is because there was no storage drawers loaded until you teleported back to your base which I assume has storage drawers.

**Comment by Zarepheth** [comment]
That's sort of what I'm thinking. My base has storage drawer blocks in the same chunk as my teleport destination. Even if they were a few chunks away, I'm sure they'd be loaded shortly after my arrival...

**Comment by Zarepheth** [comment]
Was it my imagination or did the Change Log on Curse state that Storage Drawers required Forge ...2188+?

I ask because Forge for Minecraft 1.10.2 is only up to ...2185. Although for Minecraft 1.11 it is at ...2189.

**Comment by jaquadro** [comment]
Only the 1.11 version would have said that.  I haven't specified a min for 1.10.2 for a while.

**Comment by jaquadro** [comment]
There was a bunch of funny business around that last release.  SD 3.5.10 and Chameleon 2.2.2 are out and I've tested them separately in a curse launcher pack.
