### ISSUE TITLE
Iron Blocks to Gold bars in Compacting drawer

### ISSUE THREAD

**Issue by mskoczen** [jaquadro/StorageDrawers#385]
I am using Version 1.1.3-1.10.2(beta) version of the Direwolf20 pack through the Curse launcher
If I take an empty compacting drawer and put iron blocks into it the ingots and nuggets are gold.
Allows easy conversion between Iron and Gold
![bugirontogold](https://cloud.githubusercontent.com/assets/2278274/21081608/83f97fea-bf7f-11e6-9c5c-870f005824c8.png)

**Comment by codewarrior0** [comment]
See #376

Update StorageDrawers to 3.5.8.

**Comment by mskoczen** [comment]
Sorry guess I missed that when checking.
Thank you
