### ISSUE TITLE
[1.7.10] Compacting Drawer Ore Dictionary Issue

### ISSUE THREAD

**Issue by CaiganMythFang** [jaquadro/StorageDrawers#386]
MODPACK : The Ferret Business
MOD VERSION : 1.7.10-1.10.7 (latest 1.7.10 version on CurseForge dated Nov 21st)

Greetings! You fixed this issue that was encountered in my pack before, but apparently one of the recent updates resurrected this ore dictionary bug with the Compacting Drawers. 

Items placed into compacting drawers find items that are in the same ore dictionary as it, that aren't part of the compacting recipe.

http://i.imgur.com/gEtouOD.png 

It doesn't appear to be doing it with as many items as it previously used to, but it still hits odd combos like that.

**Comment by jaquadro** [comment]
I just fixed an issue like this in 1.10.2.  I can backport that fix to 1.7.10.

I'm going to guess that you have a lot of added entries in your ore dictionary, which means with the fix you may find various valid compacting levels no longer work.  They'll need to be added to the ore dictionary whitelist in the mod.  Common ores are explicitly whitelisted already.

**Comment by CaiganMythFang** [comment]
Excellent, thank you! 

Yes, I use the ore dictionary heavily for pack mechanics.

**Comment by jaquadro** [comment]
Give 1.10.8 a try

**Comment by CaiganMythFang** [comment]
Yep, just tested it. The common metals work fine, and other items that were reported giving odd compacting combinations are fixed as well 

I already see the things that don't work anymore due to the whitelisting requirement. Thaumcraft magic tallow for example. This is perfectly fine.

Thanks again for the quick fix!
