### ISSUE TITLE
Compacting drawer won't lock and all current ones become unlocked

### ISSUE THREAD

**Issue by scalda** [jaquadro/StorageDrawers#387]
The compacting drawers will not lock with the key and all current locked compacting drawers in the world have become unlocked

Updated modpack from 1.4.0 - 1.5.1

Modpack - Hermitpack 1.5.1
Version StorageDrawers-1.10.2-3.5.8.jar

**Comment by jaquadro** [comment]
The drawers were actually still locked.  It was the rendering that was failing to appear.

Fixed in Chameleon 2.2.2.
