### ISSUE TITLE
Framed Drawer + Packing Tape = Disappearing Drawer

### ISSUE THREAD

**Issue by Helbereth** [jaquadro/StorageDrawers#388]
Placed a 2x2 Framed Drawer with a basalt texture, loaded it with items, used packing tape to seal it, then a silk-touch magnetic osmium paxel to break it for relocation.

When broken, the drawer vanished. It didn't appear on the ground, in my inventory or otherwise, and its contents vanished in the process.

To test it upon realizing what had happened, I loaded another 2x2 framed drawer of the same type with some cobblestone (not wanting to risk more valuable items), sealed it with tape and broke it with the same tool, thereby voiding a few stacks of cobblestone and the second drawer.

This has only happened with the framed drawers, as I've done the sealing and transporting trick with numerous compacting and 2x2 spruce drawers in the same world. It wasn't until I decided to get fancy and try to match the drawers to my decor that things went sideways.

**Comment by jaquadro** [comment]
What's your game version?

**Comment by jesmores** [comment]
Probably whatever is currently in FTB HermitPack, as per [this thread](https://www.reddit.com/r/HermitPack/comments/5hy8xu/the_amazing_vanishing_framed_drawers/).

**Comment by jaquadro** [comment]
Fixed in 3.5.11.
