### ISSUE TITLE
Storage Drawers' Redstone Upgrade emit a strong redstone signal but do not update adjacent blocks

### ISSUE THREAD

**Issue by Xiaminou** [jaquadro/StorageDrawers#389]
I had a similar issue back in 1.8.9 and seems like it's back. When inserting items in a Storage Drawer it will not update adjacent blocks and therefore it will not emit any redstone signal.

https://youtu.be/7EDiHvSjffs

![2016-12-14_16 50 16](https://cloud.githubusercontent.com/assets/8670392/21188991/744b0546-c21d-11e6-95c2-03ba444dd7f9.png)
![2016-12-14_16 50 23](https://cloud.githubusercontent.com/assets/8670392/21188992/744b89a8-c21d-11e6-8b83-5bd4f3421a60.png)

Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/jaquadro/StorageDrawers/files/652150/list.txt)

**Comment by jaquadro** [comment]
Drat.  Okay, just confirmed it.

On a total aside, those screenshots make me feel like I'm upside-down.

**Comment by jaquadro** [comment]
Fixed in 3.5.13.

(again)

**Comment by Xiaminou** [comment]
You know what, that's actually a very good point, I could slap those circuits on the ceiling instead, I keep forgetting you can place them upside down.
