### ISSUE TITLE
Missing framed texture on last version

### ISSUE THREAD

**Issue by Serico86** [jaquadro/StorageDrawers#390]
Missng texture on framed item but crafting work

![2016-12-14_22 55 17_ink_li](https://cloud.githubusercontent.com/assets/24575754/21203171/98020f3c-c251-11e6-8208-3a3dcb17e7c7.jpg)

**Comment by jaquadro** [comment]
What version?  I see them both present in my latest version of 1.10 and 1.11.

**Comment by Serico86** [comment]
MC 1.10.2 - 3.5.12... previous version (3.5.11) work perfect

3.5.13 version work... the issues are only for 3.5.12 version (i try this again)... no problem latest version fix all issues :D

**Comment by jaquadro** [comment]
Do they render if you place the block?  Is Chameleon fully up to date?

**Comment by Serico86** [comment]
all mods that i'm using are up to date.. i edited my latest post

**Comment by jaquadro** [comment]
I didn't change anything in .13 related to framed or rendering.  Weird fluke?  I guess if it's working I can close this.
