### ISSUE TITLE
half-sized drawer suffocation (3.5.6 regression)

### ISSUE THREAD

**Issue by flyser** [jaquadro/StorageDrawers#391]
When I upgraded from 3.5.5 to 3.5.6, the half-sized drawers started to cause suffocation when standing too close. This bug is still present in 3.5.13 (using forge forge1.10.2-12.18.2.2124).
Let me know if you need any more information.

**Comment by jaquadro** [comment]
Maybe a screenshot would help?  I tried putting various half-size drawers down and switching to survival mode, but I'm not getting any suffocation.

**Comment by flyser** [comment]
I recorded a quick video: https://www.youtube.com/watch?v=Wa7Bosi1dVk (I am playing on a multiplayer server in case that makes any difference)

**Comment by jaquadro** [comment]
Head-height.  Of course.  I'll dig around.

That lock icon bug you showed at the end was already fixed in a newer version.

**Comment by jaquadro** [comment]
Fixed in 3.5.14
