### ISSUE TITLE
[1.11] Framed drawers x-ray through blocks

### ISSUE THREAD

**Issue by sargunv** [jaquadro/StorageDrawers#392]
<img width="1136" alt="screen shot 2016-12-20 at 6 15 05 pm" src="https://cloud.githubusercontent.com/assets/1320357/21371628/62414c44-c6e0-11e6-866d-2212271c75fe.png">

**Comment by jaquadro** [comment]
Fixed in 1.10.2 (included in 3.5.15).

A roll-up of fixes for 1.11 should be out sometime this week.

**Comment by jaquadro** [comment]
Fixed in 4.0.3 for 1.11.  Also requires a Chameleon update.
