### ISSUE TITLE
[1.11] Items are cleared on break

### ISSUE THREAD

**Issue by sargunv** [jaquadro/StorageDrawers#393]
When I break a drawer with an axe, the drawer drops but all the items it contained disappear. They don't drop on the ground like from other MC containers.

Not sure if this is intentional for performance reasons, but it does feel off.

**Comment by jaquadro** [comment]
Were they framed?  Because there was a 1.10 bug related to that which hasn't made it to 1.11 yet.

**Comment by sargunv** [comment]
It happens with the basic drawer.

**Comment by jaquadro** [comment]
Fixed in 4.0.3.  Also update Chameleon.
