### ISSUE TITLE
Drawers causing render issues with other mods

### ISSUE THREAD

**Issue by simpson409** [jaquadro/StorageDrawers#394]
![2016-12-21_09 09 22](https://cloud.githubusercontent.com/assets/21246918/21382081/178d6636-c75f-11e6-9260-9a54a5f0e651.png)
![2016-12-21_09 15 42](https://cloud.githubusercontent.com/assets/21246918/21382083/1925eff4-c75f-11e6-97ba-802241946612.png)
orientation seems to matter, and causes either no issues or different issues

**Comment by codewarrior0** [comment]
Smells like alpha blending is being enabled somewhere instead of alpha testing.

**Comment by jaquadro** [comment]
I assumed this was related to #400.

But if not, this is where the lack of pushAttrib hurts.  Rendered items can also change state.

**Comment by codewarrior0** [comment]
Probably not related. I don't see the item counts here.

What gives it away is the rectangular "empty" area around the botania flower. With alpha testing, any pixels that don't pass the test are discarded, which means they never get to touch the depth buffer. With blending, even if the pixel has a zero alpha value, it still gets to touch the depth buffer, which means the depth buffer will have an "image" of a rectangular area around the flower, causing any pixels that would end up behind it to be discarded.

**Comment by codewarrior0** [comment]
Oh dear. It looks like a bug in Minecraft.

`RenderItem.renderItemIntoGUI` enables both alpha blending and testing, but only disables testing.

**Comment by jaquadro** [comment]
Well at least I can work around it.  But same idea to the above.  It's harder to police state so that any arbitrary entity will continue to see a "clean" environment.

**Comment by jaquadro** [comment]
This should be fixed in 3.5.17.
