### ISSUE TITLE
[Bug] Items/upgrades disappear when breaking framed drawers

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#395]
1.10.2, SD 3.5.7, DW20 pack 1.1.4
When breaking framed drawers sealed with packing tape, the drawers were turned into empty drawers (unsealed and empty). All the items and upgrades were lost. I've tried this with 2-drawer and 4-drawer pieces so far. Basic single drawers remained filled and sealed in inventory and placed correctly.

**Comment by jaquadro** [comment]
Update to the latest version.  Should be fixed.

**Comment by ghost** [comment]
Looking good. Thanks.
