### ISSUE TITLE
Show quantity (Quantity Key) on drawer causing issue

### ISSUE THREAD

**Issue by Fireztonez** [jaquadro/StorageDrawers#400]
Hello,
I have the latest stable release from Storage Drawer for 1.10.2 (v.3.5.16), and when I show quantity of item with the Quantity Key, I have a strange rendering issue. Is look like I can see through some blocks.
 The best way for help to understanding this issue is with screenshot I think, so:

With the quantity bug:
![drawer_issue](https://cloud.githubusercontent.com/assets/19277301/21573213/da889b86-ceaf-11e6-9787-1ab286840870.png)

Without quantity:
![drawer_issue_noquatity](https://cloud.githubusercontent.com/assets/19277301/21573232/f7caffea-ceaf-11e6-8c7f-3993003f7c50.png)

On the same arround, you can see through a door:
![drawer_issue_door](https://cloud.githubusercontent.com/assets/19277301/21573292/ca4eaf16-ceb0-11e6-9ce0-473168967db5.png)

**Comment by jaquadro** [comment]
This shouldn't be a big deal to fix.  I'm currently traveling though, so I can't look at it until early next week.

**Comment by codewarrior0** [comment]
Yep. Looks like glDepthMask is turned off and then never turned back on.

And it looks to me like there's no way to turn it off and then set it back to what it was before? This "GlStateManager" class doesn't seem to do a good job of actually managing state!

**Comment by jaquadro** [comment]
GlStateMapper was an ill-considered addition, and there's several GL aspects that can't be properly restored through it.

Historically in 1.7, many entities (including vanilla entities) were really sloppy about restoring their state, so you had to be defensive about setting up your state regardless.  Though it's polite to clean up after yourself.

**Comment by codewarrior0** [comment]
To clean up the state I usually use glPushAttrib (which the GlStateManager definitely does not handle correctly), but in modern OGL that's gone and you're expected to maintain your own state stack in client space.

Oh well. Quick-fix incoming.

**Comment by Fireztonez** [comment]
thank's for that reply, I'm not to sure if I realy understand wath is the GlStateMapper, but I gessing is a technology on OpenGL??

If you said you make a fix for that is perfect, thank's.

And, for sure, Happy new year for you 2!!

**Comment by Xiaminou** [comment]
So that's what was causing it. I have been wondering what was happening for a long time. Glad to see you guys are already on it.

**Comment by jaquadro** [comment]
Fixed in 3.5.17
