### ISSUE TITLE
[1.10.2] [Compatibility] Actually Additions Support

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#403]
Hi jaquadro,

Would it be at all possible to get support for Actually Additions Black Quartz? It's the same as regular quartz  (Which you have an exception for when it comes to the vanilla quartz.) I was wondering if that could be added for black quartz too. Perhaps @Ellpeck can do this from his end I'm not entirely sure but it would be great to see.

**Comment by jaquadro** [comment]
It can be added in the config with a new compacting tier rule.
