### ISSUE TITLE
Rendering crash MP Server

### ISSUE THREAD

**Issue by Bennyboy1695** [jaquadro/StorageDrawers#404]
I Have foamfix and optifine installed but theres no mention of them in the crash issues at all.

[crash-2017-01-08_12.52.36-client.txt](https://github.com/jaquadro/StorageDrawers/files/692099/crash-2017-01-08_12.52.36-client.txt)

**Comment by Bennyboy1695** [comment]
Any help on this would be great as this has just happened again after reseting the area on our server and also happening to players that don't have foamfix or optifine installed.

**Comment by jaquadro** [comment]
This was kind of crappy, but I've got a solution.  Should be fixed in 3.5.17.

**Comment by Bennyboy1695** [comment]
Can i ask what caused it ? Seeing as there was no storage drawers within render 😛

**Comment by jaquadro** [comment]
Something that needed pathfinding was interacting with a drawer and the TileEntity wasn't present.  

It created a chicken and egg problem where creating the tile entity triggered a pathfinding update which asked for a bounding box which asked for the tile entity which caused the tile entity to be created...

**Comment by codewarrior0** [comment]
Is it even right to create the tile entity on demand like that? Given that the server sends the blocks and tile entities in different packets, the client would get the blocks first, create the tile entity, then receive the real tile entity in a later packet.

**Comment by jaquadro** [comment]
I don't have a choice in the matter.  If you try to get a tile entity, the world will try to add it if it doesn't exist.  I couldn't find any independent check.
