### ISSUE TITLE
Is obsidian upgrade really supposed to be less powerful than iron?

### ISSUE THREAD

**Issue by cha0s** [jaquadro/StorageDrawers#405]
It seems a bit strange to me that in 1.10 the obsidian upgrade is the lowest tier. In previous version I believe obsidian was just below diamond. Was this intentional and if so, why? It seems like a bug.

**Comment by jaquadro** [comment]
It was intentional, because the usual case in modded Minecraft is obsidian is trivially obtainable and renewable.  Iron and gold didn't have much use outside of the first ... half hour of play?

But the low-tier obsidian upgrade adds bonus blast resistance in addition to the 2x multiplier.

**Comment by cha0s** [comment]
That's fair. It is pretty easy to get obsidian in a tinker smeltery. :)

I also didn't know about the blast resistance bonus.

Thanks for your time!
