### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by artificial-immersion** [jaquadro/StorageDrawers#407]
When I tried to build StorageDrawers from source I got the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'StorageDrawers-1.10'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

Am I doing something wrong?

**Comment by codewarrior0** [comment]
`cd ..; git clone https://github.com/jaquadro/Chameleon`

**Comment by jaquadro** [comment]
As codewarrior0 mentioned, Chameleon must be checked out into an adjacent directory.  This arrangement allows me to keep the projects separated but still easily construct an IntelliJ solution with all their sources incorporated.

**Comment by artificial-immersion** [comment]
Thank you a lot. That did it for me. Using mostly with the command line so probably would have seen that with an IDE.
