### ISSUE TITLE
[Kinda Bug] Void upgrades

### ISSUE THREAD

**Issue by scuria94** [jaquadro/StorageDrawers#408]
You can get 2 or more void upgrades in the same drawer. It should limit to 1 void upgrade per drawer

Modpack skyfactory 3

**Comment by codewarrior0** [comment]
Should limit redstone upgrades too, if they aren't already.

**Comment by jaquadro** [comment]
Other than being silly and occupying extra slots, are there any further consequences?

**Comment by codewarrior0** [comment]
I guess it only comes up when you're applying a lot of void upgrades to a lot of drawers.... which would happen in Skyfactory when you want to void all of the extras in a system that makes 20 different items from crushed cobblestone.

**Comment by jaquadro** [comment]
Fixed in 3.6.0.  Only normal storage upgrades can be duplicated, and only one upgrade from each "class" can be used at a time.
