### ISSUE TITLE
SkyFactory3 - Using Buider's wand to place limits drawer capacity to 1 stack.

### ISSUE THREAD

**Issue by Thumper00067** [jaquadro/StorageDrawers#413]
Actually, it says 1 stack, but you cannot place items into them.  I used a diamond builder's wand from Better Builder's Wand mod to place several 1x1 and 2x2 onto existing drawers.  They placed, but this is what they showed:
![2017-01-15_17 43 22](https://cloud.githubusercontent.com/assets/16456616/21967352/5d9e9448-db4a-11e6-960e-d558a3d26f43.png)
![2017-01-15_17 45 34](https://cloud.githubusercontent.com/assets/16456616/21967358/76074e26-db4a-11e6-80fb-41c1e6c31c48.png)

My son had me try [shift] + [right click] to see if it updated the capacity, but that was a no go.  I could see the gui, but when I left it it was still 1 stack.
So far breaking and placing by hand restores the drawer.
![2017-01-15_17 49 41](https://cloud.githubusercontent.com/assets/16456616/21967378/0a4432de-db4b-11e6-8eb6-2a90c36cec15.png)
![2017-01-15_17 48 25](https://cloud.githubusercontent.com/assets/16456616/21967380/0c9d7b08-db4b-11e6-8164-2aff3a27d4cf.png)

I am using the FTB launcher for SF3 on a machine running Ubuntu.  If you need to know more let me know.

**Comment by jaquadro** [comment]
Placing a drawer item in the world populates its TileEntity with several pieces of information including capacity.  I'll need to explore moving that initialization bit, since wands don't seem to execute it.

**Comment by jaquadro** [comment]
This should be improved in 3.7.4 / 4.2.4.

I've read that the ExU wands do not have the same problem, so I suspect better builders wands could do a better job with how they clone blocks.  With the above versions, they should at least get the type and storage quantity correct.  Other attributes like direction will probably be wrong.
