### ISSUE TITLE
[1.10.2] Compacting Drawers and the new compacted materials

### ISSUE THREAD

**Issue by Techokami** [jaquadro/StorageDrawers#418]
I mentioned this in-game last night on our server, but Compacting Drawers should be compatible with converting Nether Wart back and forth from Nether Wart Blocks, like with Sandstone. Similarly, Magma Cream compressing into Magma Blocks. Bone Blocks and Slime Blocks work fine out of the box, thankfully.

Keep up the good work mang 👍

**Comment by jaquadro** [comment]
Nether wart: yes.
Magma cream: no.  Justification is magma blocks are naturally occurring (in quite large quantity) rather than being manufactured blocks like quartz and nether wart, AND magma cream is a valuable potion regent dropped by a mob.

**Comment by Techokami** [comment]
Ah, makes sense. I was simply looking at it for the purpose of compressing Magma Cream for my network.

Also, what about red sandstone? I put an entry in the config file for our server a while back for it.

**Comment by mfriendc** [comment]
I was just about to suggest this, but your justification is understandable to me, I'm glad I looked it up first
