### ISSUE TITLE
[1.10.2] Drawers with sticks in them are 'chatty'

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#426]
I tested this in 2x2 drawers made of oak and dark oak. Not tested on any other drawer or material.
When those drawers have sticks in them and you take them out, there is a message in chat that says:

> BlockName [tile.basicDrawers.name].blockID [basicDrawers], metadata [2]

**Comment by codewarrior0** [comment]
This is a feature of another mod, I believe it's ExtraUtilities? It turns the stick into a "block inspector" tool.

**Comment by ghost** [comment]
I don't have extra utilities in my modpack, but I'll check to see if there is one that could cause this.

**Comment by ghost** [comment]
You are right, left clicking with a stick does that. Not sure which mod it is though; hopefully I can disable it...rather annoying.
Thanks.
