### ISSUE TITLE
Storage drawers don't update their redstone signal when removing items via a drawer controller

### ISSUE THREAD

**Issue by freshstrangemusic** [jaquadro/StorageDrawers#438]
MC Version: 1.10.2
StorageDrawers version: 3.6.0

This may be related to [issue 340](https://github.com/jaquadro/StorageDrawers/issues/340)

**Comment by freshstrangemusic** [comment]
For what its worth, the item is being removed via EnderIO item conduits.

**Comment by jaquadro** [comment]
While I don't see anything in the changelog that specifically fixes this, I can't reproduce it in either SP or MP.  Tested with EnderIO (SP) and AE2 (MP) on 3.7.7.

Feel free to re-open if you can provide more information around reproducing it.
