### ISSUE TITLE
Storage Drawers 4.2, Minecraft 1.11, Botania 1.9.342 [Compability]

### ISSUE THREAD

**Issue by knord1** [jaquadro/StorageDrawers#443]
Comapability issues.

Storage Drawers are not behaving correctly with Botania installed.

Drawers are rotated incorrectly.
Locked/void drawer info is not shown.
Right Click to insert places a block in the world before inserting in drawer.
shift-right click to show content of drawer only shows max a stack amount of 64.

Forge *.2233
Minecraft 1.11.2
Storage Drawers 1.11.2-4.2.0
Chameleon 1.11.2-3.0.2

**Comment by knord1** [comment]
Seems to not happen with Forge 13.20.0.2255

**Comment by jaquadro** [comment]
Based on description, this was probably a Botania tile throwing an exception when loading TileEntity data in a chunk.  Since this supposedly resolved, I'm not going to dig further.
