### ISSUE TITLE
[Suggestion] Drawer Replace Tool

### ISSUE THREAD

**Issue by Zaikyu** [jaquadro/StorageDrawers#447]
It would be nice to have a way to swap out a draw style without having to empty the drawer and remove the upgrades. Maybe a tool to just Swap out a drawer with one in your inventory. Basically I just want to be able to change my Oak Drawers to Spruce Drawers without having to find a place to store my 133k cobblestone while I have to break and replace

**Comment by codewarrior0** [comment]
We already have one! Just make a Spruce Trim and shift-right-click it onto your Oak Drawers to change them to Spruce Drawers.

I just wish it worked for Framed Drawers too...

**Comment by Zaikyu** [comment]
I see I see, Alrighty then. Didn't know that.
