### ISSUE TITLE
The One Probe Compatibility

### ISSUE THREAD

**Issue by Lethann** [jaquadro/StorageDrawers#448]
Any chance of getting better compatibility with The One Probe? Basic drawers show total contents but not like Wailia that shows stack sizes, upgrade limits, etc. Compacting drawers are not showing anything about their contents either. 

Their public API stuff is here: https://github.com/McJty/TheOneProbe/tree/master/src/main/java/mcjty/theoneprobe/api

**Comment by ghost** [comment]
You can install the [one probe addons](https://minecraft.curseforge.com/projects/top-addons). It adds compatibility for some mods including Storage Drawers.

**Comment by Lethann** [comment]
Ah, thanks. I didn't realize there was an addon for it.
