### ISSUE TITLE
Bug when storing heads (and wool)

### ISSUE THREAD

**Issue by agentgoblin** [jaquadro/StorageDrawers#45]
When I store mob's heads in drawer, I have bug. Place one type of head (e.g. zombie head), then try place another head (e.g. skeleton skull) to same cell. Drawer cell contain only zombie heads. It's bad - I lost all Enderman heads from EnderIO after one missclick.

Minecraft ver. 1.7.10
Forge ver. 10.13.2.1277
Storage Drawers ver. 1.2.1 (also work in 1.2.0)

How to reproduce bug:
1 Place in drawer cell head type A;
2 Place in same drawer cell head type B;
3 Extract heads type A:
4 Let's cry, you lose heads type B. :(

Screenshots:
http://tinypic.com/view.php?pic=2lmnbtf&s=8

**Comment by agentgoblin** [comment]
And with wool same problem. One colored wool can be placed in cell with another color.

**Comment by jaquadro** [comment]
I think it's actually an ore dictionary problem.  I have to blacklist some entries because they represent a category rather than a specific object.

**Comment by jaquadro** [comment]
This is fixed in 1.2.2.  It was an ore dictionary problem.  Any wildcard entry will be blacklisted by default now, which should catch anything I missed or that other mods might have added.
