### ISSUE TITLE
Compacting Drawer Status

### ISSUE THREAD

**Issue by meeshabeez** [jaquadro/StorageDrawers#459]
Hi there, I tried searching for this, but wasn't able to find any topics on the matter, so I apologize if this has been raised before (I'm new to posting here).

My server just upgraded Storage Drawers to version 3.5.16 > 3.6.1 and since then I've been having an issue with the compacting drawers.  Namely, the status upgrades are not showing up on the compacting drawers now.  I haven't really changed anything, just logged in and saw that the status weren't showing up.

Is there something I should be doing differently?  Thanks!

**Comment by jaquadro** [comment]
Confirmed the bug in my test world

**Comment by jaquadro** [comment]
Fixed in the latest builds.
