### ISSUE TITLE
Compatibility with HWYLA (the new WALIA) for 1.11+

### ISSUE THREAD

**Issue by NovaViper** [jaquadro/StorageDrawers#460]
Hey, could you add support for HWYLA, which is the forked version of WALIA updated for 1.11.2?

**Comment by bkindig** [comment]
I 2nd this.  I tried to use HWYLA last weekend and was disappointed to find that it wasn't supported.

**Comment by NovaViper** [comment]
Yeah, I'd thought it would be supported since it is the forked version of WAILA

**Comment by jaquadro** [comment]
If it's fully API-compatible with WAILA 1.10, then I just need to uncomment some integration code.

**Comment by codewarrior0** [comment]
Looks like it is. I uncommented that code and did a quick test build - only change needed was changing a `stack == null` into a `stack.isEmpty()`.

**Comment by bkindig** [comment]
codewarrior0, thank you for figuring it out.  I'm not too familiar with GitHub.  How can I get the changes you implemented?  Do you need to build and commit or..?

**Comment by NovaViper** [comment]
@bkindig You go and fork the repository, then commit the build to your newly forked repository, then create a pull request with the original repository (Comparing the original branch to your branch)

**Comment by bkindig** [comment]
Thank you.  I will give it a try.  I hope I don't mess anything up.  

I'm much more comfortable with TFS.  Would you say the concepts between TFS and Git are mostly the same?

**Comment by NovaViper** [comment]
@bkindig I'm not familiar with TFS, sorry!

**Comment by jaquadro** [comment]
This is now enabled in the latest 1.11.2 build.  The sneaker change is that the mod ID changed (all IDs that used upper-case letters, including Storage Drawers, had to switch to all-lower IDs).
