### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by surfersmurf** [jaquadro/StorageDrawers#461]
Hi, I have a storage drawer on top of a cobble gen (Tier 4) from Tiny Progressions and after a few minutes it crashed my game.

https://pastebin.com/8u2tstpW

**Comment by Xiaminou** [comment]
Same problem, server crashes within the first minute after it has finished loading.
Crash Report: [crash-2017-04-03_16.03.43-server.txt](https://github.com/jaquadro/StorageDrawers/files/890286/crash-2017-04-03_16.03.43-server.txt)
Environment: Server
Minecraft: 1.10.2
Forge: 2254
Storage Drawers: 2.6.3
Mods: [list.txt](https://github.com/jaquadro/StorageDrawers/files/890282/list.txt)

**Comment by Xiaminou** [comment]
Downgrading Storage Drawers  to 2.6.0 and Drawers & Bits to 0.35 seems to fix the issue.

**Comment by jaquadro** [comment]
Damn.  I guess it's time to try pulling the trigger.

I've pulled the 3.6.3 version from Curse.  Please play around with version 3.7.0, which I've marked as a beta release.  This removes all of the legacy IInventory support.  It's possible it will stop interacting with some mods, if those mods never updated to the new inventory handling system Forge introduced in 1.8.x.

I had intended to keep supporting IInventory for 1.10, but it makes things a lot harder to reason about, and fixing one bug can lead to massive failures like this without careful consideration.

**Comment by jaquadro** [comment]
Closing this out since I haven't heard any new major problems about the 3.7.0 beta.
