### ISSUE TITLE
[Suggestion] Add the ability to remove upgrades

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#462]

**Comment by codewarrior0** [comment]
Hold Shift and right-click on a drawer to remove upgrades.

**Comment by ghost** [comment]
@codewarrior0 Oh, I had no idea you could do that. Thank you so much!

**Comment by ghost** [comment]
It doesn’t work. It seems as though you can remove the latest upgrade after opening the drawer for the first time after installing the upgrade, but after that, you can’t remove any upgrades.

As you can see in the below screenshots, the upgrades are greyed out; I cannot take them out of the drawer.

![storage drawers can t remove upgrades](https://cloud.githubusercontent.com/assets/25916106/24746456/751e5b54-1ab9-11e7-9632-ccc0f21fc6d3.png)

**Comment by BrianEdmonds** [comment]
I've never had any trouble removing upgrades. Note that upgrades will be
greyed out, and unremoveable, if they are required to hold all the items
in the drawer. Empty the drawer out below the upgrade's threshold, and
they remove fine.

**Comment by ghost** [comment]
Oh, I didn’t think about that. I’m stupid.

Thanks.
