### ISSUE TITLE
Compacting Drawer reports as full when it contains >2 stacks of the item

### ISSUE THREAD

**Issue by tterrag1098** [jaquadro/StorageDrawers#47]
We were hoping to use the compacting drawers as ingot storage on our LP network, but once they contain 2 stacks of ingots it will no longer take more items from automation. Not sure exactly how you want to approach this.

**Comment by tterrag1098** [comment]
We are on 1.2.2 by the way, not sure if anything like this was added in 1.2.3

**Comment by jaquadro** [comment]
None of the drawers are compatible with LP currently.  I do have an issue open with them, but I need to write the compat layer.

**Comment by tterrag1098** [comment]
Alright, thanks. Any news on #46? :D

**Comment by jaquadro** [comment]
Just a note, the latest dev branch of Logistics Pipes has Storage Drawers support.  I don't know what a release will come out, but the support should be there when it does.

**Comment by 1n5aN1aC** [comment]
This was fixed long ago, and LP has actual integration now, as well as we've had quite a few actual releases to Curse, so everyone should be on a version that supports StorageDrawers by now.

**Comment by jaquadro** [comment]
Thanks for the update!
