### ISSUE TITLE
[BUG] Compacting Drawer destroys items if almost full and a higher tier item is inserted

### ISSUE THREAD

**Issue by bothie** [jaquadro/StorageDrawers#470]
Steps to reproduce:

Just place a lone Compacting Drawer, configure it for some item type (i.e. Cobblestone), fill it completely to state 1024/0/0 (1024 Double Compressed Cobblestone). Take out one Cobblestone (1023/8/8) and try to insert a Double Compressed Cobblestone.

Expected result:

a) Either the Compacting Drawer should reject the item,
b) or the Compacting Drawer should allow for temporary overloading (1024/8/8) in order to prevent item loss, either visibly (actually showing 1024/8/8) or invisibly (showing 1024/0/0 but still storing the extra 0/8/8 until stuff gets removed).

Actual result:

The Double Compressed Cobblestone will be consumed by the Compacting Drawer, but it only fills up to 1024/0/0 again. Taking out either Cobblestone, Compressed Cobblestone or Double Compressed Cobblestone reveals, that the overflown Cobblestone is actually lost.

**Comment by jaquadro** [comment]
What version?

Sounds like a bug that was fixed on 1.7.10 a long time ago, but maybe it surfaced again?  It's supposed to reject.

**Comment by jaquadro** [comment]
Fixed in latest releases for 1.10.2 and 1.11.2

**Comment by ghost** [comment]
I'm encountering this issue in Project Ozone 2 2.3.0 with either their default StorageDrawers-1.7.10-1.10.8 and the latest StorageDrawers-1.7.10-1.10.9.

For me this happens with Magneticraft's Sulfur and Sulfur Block (3x3 Crafting).

You can easily trigger this by taking one Sulfur out -> 1024 Blocks, 9215  (1024*9-1) Sulfur
But then it allows you to insert another full Block -> 9216 Sulfur. The other 8 Sulfur are gone.

It should be noted that both of them have oredict entries and there are other non-Block Sulfur versions in this pack.
