### ISSUE TITLE
Storage Drawers/Refined Storage drawer controller not staying connected to crafting grid

### ISSUE THREAD

**Issue by flak4321** [jaquadro/StorageDrawers#472]
Issue Description:

I have a Refined Storage system up and running in the FTB Beyond mod pack for 1.10.2.  The issues begin when I go to the Mining Dimension from Aroma1997's mod. I go, I mine, I return and I enter my crafting grid. Poof, my storage drawers do not register in the inventory. Oh, and the drawer controller is present in the main Controller's GUI. Note: This inter-dimensional travel is also how to reproduce, which I can do at will.

Secondary Notes:

The mod pack is fully up to date so far as I can tell. I'm playing single player and not on a server (my laptop is doing everything lol). The crafting grid maintains connection to everything when I shut down, leave the chunk of my dwelling while staying in dimension, and even when i go to the Nether. Grid is powered by a small reactor from the extreme reactors mod.

I attempted a quarry in the mining dimension with an RFTools Builder Block and the dimensional issue appears to also block items and energy (even after cutting off my Enderman farm) from flowing through my Ender I/O Dimensional Transceivers. This may be unrelated, but I felt it worth mentioning. 

Workaround:

I found I can force the drawer contents to show in my grid by breaking both the Controller and the Crafting Grid and replacing them.

**Comment by codewarrior0** [comment]
Seems to be related to https://github.com/raoulvdberge/refinedstorage/issues/370 (ref'd from https://github.com/raoulvdberge/refinedstorage/issues/1065) - fixed in the 1.11 version but not yet backported.

**Comment by jaquadro** [comment]
If the problem only shows up with RS's grid, with the drawer controller works correctly with other systems, then it's probably on RS.

**Comment by flak4321** [comment]
Thank you both for your prompt replies! 

jaquadro, Sorry if this thread seems misplaced. Took me a while just to get signed up and couldn't find the page I had started on nearly a week later. I'll see if I can find a better place for it.

**Comment by jaquadro** [comment]
Posting it here is fine.  When there's an interaction issue and the origin is not certain, posting the issue on both projects (and cross-linking the issues back by mentioning the URLs) will give you the best chance of a resolution.

Looks like you're stuck on this one, though.
