### ISSUE TITLE
How do I connect a Slave to a Controller?

### ISSUE THREAD

**Issue by Evergetic** [jaquadro/StorageDrawers#473]
I have a setup where my drawers are all upstairs but processing is downstairs. But rather then having multiple pipes coming together in 1 controller, I wanted a slave (thinking that it would pick up the controller within x range). I also tried putting a pipe in between and even a transfer node. Below is an image of how I currently have it (for testing how it works). I'm playing on skyblock 3 btw.

![2017-05-01_01 10 01](https://cloud.githubusercontent.com/assets/8708435/25568787/4e3736d6-2e0b-11e7-8fb6-388ff2693b23.png)

**Comment by codewarrior0** [comment]
The slave must be connected to the controller using a line of drawer trims or drawers - the same way drawers are connected to the controller.

**Comment by jaquadro** [comment]
Correct, you need to use the "trim" blocks (which can also be framed trim if you want a style that fits better).  They're basically pipes for drawers, as long as you're within controller range.
