### ISSUE TITLE
What Java Crashed With

### ISSUE THREAD

**Issue by YoMamaJames** [jaquadro/StorageDrawers#474]
I was putting some saplings into one the 2 by 2 Storage Drawers and keeps crashing with java.lang.tileentitynotfound/exception. I am currently running Storage Drawers 1.10.2 version 3.6.1 on an unmodified FTB modpack.

Please fix this issue and if the issue is already fixed, what version of it is the fixed version?

**Comment by YoMamaJames** [comment]
Here is my crash report: https://pastebin.com/AyKZ4aR4

**Comment by jaquadro** [comment]
Sounds like the TileEntity might be damaged.  Can you destroy the block and replace it?

**Comment by jaquadro** [comment]
I put in a check that should at least avoid that crash, available in 3.7.5.  Still sounds like the underlying tile is corrupt.

**Comment by YoMamaJames** [comment]
Alright Thanks :)
