### ISSUE TITLE
Controller slaves do nothing.

### ISSUE THREAD

**Issue by tofof** [jaquadro/StorageDrawers#482]
Storage drawers 1.10.2-3.7.4

Controller slaves are enabled in config.
Controller drawer range is 12 as default. 

Drawer connected by solid unbroken line of adjacent trim blocks to all relevant drawers, such that all blocks in the unbroken chain are within the range specified. Waiting at least 5 seconds between any connections and deposit. No relevant drawers are full.  Compacting and regular drawers behave the same.  Breaking and replacing chain parts or controller itself produces no change in behavior. Basic drawers vs framed drawers changes nothing.

Controller chooses drawer containing the same item if it's 12 blocks away, as expected, 
Controller does not choose drawer containing the same item if it's 13 blocks away, as expected. If handed items by enderio / actuallyadditions / integrated dynamics-tunnels it deposits them into an unlocked empty 12-or-less if available. If right clicking directly on controller, doesn't accept item.  All as expected.
Place slave at 6 blocks away. Controller still does not choose drawer containing the same item, at distance 13 from the controller / 6 from the slave. **Not as expected.**
Place slave at 13 blocks away. Controller still does not choose drawer containing the same item. As expected.
Place solid unbroken chain of slaves - 14 of them (under controller .... 12 .... under drawer). Controller still does not deposit items the 13th drawer. **Not as expected.**
Place additional controllers. No individual controller can place items farther than 12 away from its own location, regardless of slave/trim/drawer/controller topology. **Not as expected.**
Use concealment or locking key on controller. Regardless of topology, change propogates to 12 blocks away and no farther. **Not as expected.**

**Comment by codewarrior0** [comment]
The slave does not extend the range for connecting drawers to the controller. The slave only acts as additional faces of the controller for automation purposes.

**Comment by jaquadro** [comment]
There's a surprising amount of misinformation floating around on what the slave does.  There's no blocks currently that extend controller range.

**Comment by tofof** [comment]
Ah. Ok, disregard this then. Might want to clarify the language in the wiki about slaves allowing you to "attach more devices to a controller than can be physically accommodated, strongly prefer using a Controller Slave for these extra connections".  I definitely took 'physically accommodated' to mean more physically distant.

**Comment by Shirkit** [comment]
I also thought one could increase the range of the controller by using Slaves, the Wiki could have a PS saying that's not possible to increase the range.

**Comment by nalivai** [comment]
It definitely used to increase range of controller in 1.7 version of MInecraft, and I was sure it remains the same for the new versions. Oh well.

**Comment by jaquadro** [comment]
It didn't.  Lots of people claimed it did, and there was one statement in the documentation that was a bit ambiguous and could be interpreted that way, but it didn't.

It's something that's been brought up a lot though, so I do want to address it with a proper solution.

**Comment by jaquadro** [comment]
If you have control of the server though, you can globally increase the range of the controller in the config.
