### ISSUE TITLE
Drawers Face not showing until using a Key

### ISSUE THREAD

**Issue by m4rcs** [jaquadro/StorageDrawers#483]
I uploaded a small video that show the bug: https://www.youtube.com/watch?v=A3_m-Dbr5mo

I'm using MC 1.11.2 with Forge 2300 on a server with StorageDrawers 4.2.6 and Chameleon 3.1.0.

I hope someone can help me fix this bug.

**Comment by jaquadro** [comment]
Video link does not work

**Comment by m4rcs** [comment]
Sorry fixed.

**Comment by gammler115** [comment]
Same Bug. I have accacia Drawers which are also rendered like an oakwood-trim.
It is also fixable if you pull out all items of one slot.
But if you log out/ log the bug reappears.

**Comment by jaquadro** [comment]
This feels like a client desync issue, where the client isn't getting the TileEntity for the drawer, so it renders in its default state (oak color, facing one direction).

I've only seen this happen when there were certain Pam's Harvestcraft blocks in the same chunk, which were throwing exceptions when reading the TileEntity data on the client, preventing the remaining blocks in the chunk from properly loading.

Do you have Pam's HarvestCraft in your pack?  And either way, can you post a client log?

**Comment by m4rcs** [comment]
Yes, it was a HarvestCraft Bug. I removed the HarvestCraft blocks in proximity and the Bug was gone. Thanks for the help.
