### ISSUE TITLE
[1.7.10] permission/protection issue with forge essentials

### ISSUE THREAD

**Issue by X-Coder** [jaquadro/StorageDrawers#484]
Hi, I like your mod very much, but I have a little issue when I use forge essentials to protect the left click on a storage drawer. The protection is not working and it still gives me items on a protected storage drawer.

I reported the [issue on forge essentials](https://github.com/ForgeEssentials/ForgeEssentials/issues/2267) too. Maybe you can take a look / have an idea whats going wrong?

**Comment by jaquadro** [comment]
The "personal key" was added to make up for this problem.  It might have been solved more definitively in later versions, but the way the left click handler works in the 1.7.10 version of the mod seems to defeat all of the protection mods.
