### ISSUE TITLE
Glitchy GUI on 1.10.2

### ISSUE THREAD

**Issue by Sora-Canstavia** [jaquadro/StorageDrawers#485]
Hi there,
Some of the people on my server have noticed a slight issue with the drawers GUI, when they open it with item stacks greater than 127 the number displaying how much is in it disappears. 
drawer with 127 ingots
![127](https://cloud.githubusercontent.com/assets/28876886/26328963/fec1f030-3f3c-11e7-83c0-4d71e24e40b6.png)
same drawer with 128 ingots
![128](https://cloud.githubusercontent.com/assets/28876886/26328979/0c59abb6-3f3d-11e7-8dba-16afa98faa2f.png)

the issue isn't present for items in compacting drawers which have nugget variants, but is there in compacting drawers for items which don't have nugget variants.

One of the people on my server says that when he hits 128 his number turns negative.

I Hope that I Have set this up correctly and that those images attach correctly, I Have never used GitHub before...

**Comment by jaquadro** [comment]
Are you on the latest version of the mod?  This was supposed to have been fixed recently.

**Comment by Sora-Canstavia** [comment]
ah, just checked the version of the mod we're using and we're using "StorageDrawers-1.10.2-3.7.1"
I have to do maintenance on the server on Saturday so I Will update it then, thank you for the quick reply and sorry about the time wasting ^^; I Should have checked the mod version first
