### ISSUE TITLE
Storage Drawers+Refined Storage 

### ISSUE THREAD

**Issue by crazdxD** [jaquadro/StorageDrawers#486]
So on my ftb beyond server that i play with my friend, we have a Refined storage set up that is connected to all of our storage drawers via the controller. The problem is that what was currently on our grid before we connected the 2 did not move into our drawers. So we have more that 32 stacks in the storage but only 1 stack in a drawer. Are the items supposed to automatically move to the drawers or do we have to do it manually? Also the external storage does have a higher priority over the disk drive.

**Comment by codewarrior0** [comment]
Refined Storage will not automatically move items. You'll have to use the Disk Manipulator to empty your disks one by one to move the contents into the drawers.

**Comment by crazdxD** [comment]
Ahh, I see thank you very much

**Comment by crazdxD** [comment]
Oh, any good way that this can be automated?

**Comment by codewarrior0** [comment]
Not that I know of, but you only have to do it once after setting up your drawer bank. After you set the external storage to high priority, any items that go into RS will end up in the drawers if possible.

**Comment by BrianEdmonds** [comment]
> You'll have to use the Disk Manipulator to empty your disks one by one

Or use an Exporter. That's what I usually do.
