### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Siriuo** [jaquadro/StorageDrawers#487]
**Issue Description:**

Not sure if the issue is due to storage drawers or enderio. Hopefully the crash report will help. See EnderIO Issue Reference: https://github.com/SleepyTrousers/EnderIO/issues/4229

**What happens:**

EnderIO Conduits sometimes connected to storage drawers are causing the server to crash upon player login.

**What you expected to happen:**

Server not to crash

**Steps to reproduce:**

1. Log Into Server
2. Server Crash

**Affected Versions**

Storage Drawers: 1.10.2-3.7.4 - 3.7.6
EnderIO: 1.10.2-3.1.186 - 190
EnderCore: 1.10.2-0.4.1.66
Minecraft: 1.10.2
Forge: 12.18.3.2297

**recent log file where the issue was present:**

https://pastebin.com/dysBFmwR

**Comment by jaquadro** [comment]
Do you know what was stored in that drawer?

The crash looks easy to fix, but something still looks wrong with the underlying data.

**Comment by Siriuo** [comment]
I will make a copy of the server and try and get this information by removing EnderIO. I will let you know what I discover.

**Comment by Siriuo** [comment]
Okay so it appears the items stored in the compacting drawers are Mystical Agriculture blocks and essence. Hope this helps.

If you need me to check anything else please let me know.

**Comment by jaquadro** [comment]
This should at least stop crashing in 3.7.7.  It's likely this particular drawer won't have a useful behavior with your current setup.  I'm interested to know if manual input/output and hopper input/output work, for each of the used slots.

I probably need some more logging to make better progress on the underlying issue.

**Comment by Siriuo** [comment]
Thanks for the fix. Looks like it resolved the server side crash however the client is now crashing. I have managed to get a crash log which can be found at https://pastebin.com/4z6Va3wR

Hope this helps. If you need any further logs please let me know.

**Comment by jaquadro** [comment]
You need to update Chameleon.

I don't know why the dep check isn't working; I really need to just spend the 30 minutes to figure that out.

**Comment by Siriuo** [comment]
Of course I knew that... All seems to be working. Thanks for your help. Keep up the great work with StorageDrawers :)
