### ISSUE TITLE
idea: Portable Compactor

### ISSUE THREAD

**Issue by tahg** [jaquadro/StorageDrawers#488]
This would be an item you keep in your inventory.  It would automatically compact any items that have a reversable recipe in your inventory (eg, coal, redstone, gems, compressed cobble), in the same way the Compactor Drawer works.

**Comment by bookerthegeek** [comment]
That is very.... Lag intensive. I would look into how blood magic does that woth their compression sigil.

**Comment by codewarrior0** [comment]
@bookerthegeek Would you know the name of the mod that adds upgradeable backpacks, where one of the upgrades is a compacting upgrade?

EDIT: It's [Iron Backpacks](https://minecraft.curseforge.com/projects/iron-backpacks)

**Comment by tahg** [comment]
Well, obviously I didn't search hard enough for existing mods.  Something for 1.11 remains to be seen though.

**Comment by jaquadro** [comment]
Thanks for the suggestion, but I think this is better left to other mods (like aforementioned Iron Backpacks).
