### ISSUE TITLE
Drawers face wrong way and no picture. 1.11.2

### ISSUE THREAD

**Issue by FuuNoKamiOka** [jaquadro/StorageDrawers#489]
When I loaded up my world earlier today the drawers were facing the right side and there was no picture on the front indicating what was inside and Waila showed nothing. I tried breaking them and putting them back down but nothing happened. They were facing the right way, but there was still no image or Waila info.And, once I went out of the game and back in they were back to facing the right again. This only just started to happen. Not sure what the issue is.

**Comment by jaquadro** [comment]
Post a client log.  See also #438 -- are you using Pam's Harvestcraft?

**Comment by FuuNoKamiOka** [comment]
I am not. Only things I put in the barrels were vanilla blocks and basalt from Environmental Tech and Chisel. Pam's is not in the modpack.

Here is the log. I think I did this right. haha https://pastebin.com/Fyny5AnZ

**Comment by jaquadro** [comment]
I don't see anything interesting in the log, but it definitely looks like a client desync.  Try looking at your log right after you load your world (preferably while you're by the drawers).  If you see anything about exceptions, post the log.

**Comment by FuuNoKamiOka** [comment]
Okay, I started playing again and nothing is wrong. Not sure what the issue is but it might be fixed? For now I just don't know.

**Comment by jaquadro** [comment]
If you see it again, just jump on the log then.  Could have been some weird fluke, but as it stands, I don't have enough here to investigate.
