### ISSUE TITLE
[1.11.2] Crash when placing drawers (Tesselating block model exception)

### ISSUE THREAD

**Issue by MadByteDE** [jaquadro/StorageDrawers#490]
[Here is the relevent crash message](https://gist.github.com/MadByteDE/507ef6abcbd4d57f6cffecc4d39fd9c3)

Mod Version: 1.11.2-4.2.7
Forge Version: 13.20.0.2300
Windows 7 64 Bit
Java 1.8.0_25

**Comment by jaquadro** [comment]
This can be fixed by updating Chameleon to latest

**Comment by MadByteDE** [comment]
alright. thanks and sorry.
