### ISSUE TITLE
Issue with drawers look

### ISSUE THREAD

**Issue by Husky306** [jaquadro/StorageDrawers#494]
Similar to #450. Maybe the same issue. I use different wood for drawers and they worked perfectly fine. I could put stuff inside, upgrade etc. But after restarting the game SOME of the drawers change look to, what I think, default - oak wood and missing icons. Also, some, different drawers change facing directions. Sometimes those that worked fine for several games become like this. Doing things that would change the look (switching upgrades, removing all or putting new items) fixes it but really, I would have to reset them every time I enter my world. Lastly, other drawers seem to work fine. All of my drawers of the same Y level (second from the floor) are fine. In one room 1st and 3rd Y-levels are fine, in another most are glitching. In another base ALL of them work fine. For now. Also, some of my chests become invisible too. It may have something to do with it. 

So... MC 1.11.2
forge 13.20.0.2313
Optifine 1.11.2 HD_U_C1
Chameleon 3.1.0
Got 18 mods, including IC2, Forestry, Botania, Journeymap, Harvestcraft, Biomes oPlenty... if that helps
Resource pack Default Improved and Drawers addon. KUDA shaders.

I tried running without shaders, without resource pack, updated most things, changed most video options that might have something to do with textures. I know it's a long shot but I would REALLY love to find a solution. I love the mod. For the first time I don't need a mile long wall all covered with chests, with 20 chests for seeds and 40 for dirt. And if these drawers can store eggs and ender pearls (I didn't try these yet) just the same, in number, not stacks, I would kiss you! ...No, no reason to collect ALL ender pearls from the end-grinder, I'm just a hamster. I need MOAR of everything!!! =D

**Comment by jaquadro** [comment]
Do you have any harvestcraft blocks near them (say, within 30 blocks or so)?

**Comment by Husky306** [comment]
I sure do, I store mostly Harvestcraft crops. They take most space. Some of the always working drawers hold these and show the icons right. 

Ok, I just tested it. You're right, I had Market, Ship-bin, Presser and Apiaries nearby. They all seem to cause that. It's fixed now. The Well works fine though. I guess I'll have to make a kitchen far far away XD

Pam refused to coop and make mods compatible? ;) 

Ok, thanks a bunch! Great mod, I really enjoy it ^__^

**Comment by jaquadro** [comment]
Pam has a bug with some of her machine blocks.  They throw an exception when loading TileEntity data on the client.  If there are other TileEntity blocks in the same chunk that are still waiting to be processed (like drawers), they will be skipped as a result.  That's how you end up with a drawer in its "default" configuration.  It's still correct on the server, but couldn't load on the client.
