### ISSUE TITLE
Drawer Controllers not working

### ISSUE THREAD

**Issue by BRampage26** [jaquadro/StorageDrawers#496]
placed a drawer controller into a series on connected draws and it worked fine, however i realized i placed in wrong location and some draws were out of range. the problem occurred when breaking and replacing in a spot so that all draws would be in its 12x12 range. it no longer would allow me to deposit items. when trying to discover the problem i placed a new controller/new drawer together and worked fine but when i broke the controller and replaced next to the exact same draw it would no longer work. breaking and replacing drawer did nothing to fix it however if i used a newly crafted draw it would work fine however i don't particularly feel like going and replacing around 180 drawers because of this problem

**Comment by jaquadro** [comment]
Are you on 1.10.2?  See the last comment in #425

**Comment by jaquadro** [comment]
I may have a fix for this.  Please try the latest 1.10 or 1.11 version of the mod (see resolution in #425).
