### ISSUE TITLE
[1.11.2] Client FML modid lowercasing warn during inject

### ISSUE THREAD

**Issue by t3f** [jaquadro/StorageDrawers#497]
Client warning print over modid lowercasing.  Just a warning so not critical, but figured i'd post for tracking.

> [08:34:33] [Client thread/DEBUG] [FML/]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (com.jaquadro.minecraft.storagedrawers.StorageDrawers) - loading
> [08:34:33] [Client thread/WARN] [FML/]: ****************************************
> [08:34:33] [Client thread/WARN] [FML/]: * The modid StorageDrawers is not the same as it's lowercase version. Lowercasing is enforced in 1.11
> [08:34:33] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:147)
> [08:34:33] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:130)
> [08:34:33] [Client thread/WARN] [FML/]: *  at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
> [08:34:33] [Client thread/WARN] [FML/]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> [08:34:33] [Client thread/WARN] [FML/]: *  at java.lang.reflect.Constructor.newInstance(Unknown Source)
> [08:34:33] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:90)...
> [08:34:33] [Client thread/WARN] [FML/]: ****************************************
> [08:34:33] [Client thread/ERROR] [FML/]: Unable to construct net.minecraftforge.fml.common.Mod container
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
> 	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:90) [ModContainerFactory.class:?]
> 	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:106) [JarDiscoverer.class:?]
> 	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
> 	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
> 	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
> 	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:414) [Loader.class:?]
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:554) [Loader.class:?]
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233) [FMLClientHandler.class:?]
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440) [bes.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) [bes.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.IllegalArgumentException: The modid StorageDrawers is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
> 	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:148) ~[FMLModContainer.class:?]
> 	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:130) ~[FMLModContainer.class:?]
> 	... 20 more

**Comment by jaquadro** [comment]
Are you sure you didn't accidentally load the 1.10.2 version of the mod?  My IDs were lowercased when I ported to 1.11, because it's required to load now.
