### ISSUE TITLE
Drawer Controllers do not accept itmes from hopper duct anymore.

### ISSUE THREAD

**Issue by Draskh** [jaquadro/StorageDrawers#498]
Today I planned to built my new storage room on server but I just reconized that the controller did not accept item from hopper duct. It does not matter if the drawers are locked or not. Several Months ago everything worked fine.

**Comment by Draskh** [comment]
I am using version 1.10.2 and the recommended version of forge. I also tested single player but same result.

**Comment by Draskh** [comment]
I testet several versions. The version 3.6.2 for 1.10.2 was the last version it worked. I also noticed that I cannot put items in the front of the drawer controller.

**Comment by jaquadro** [comment]
See the last comment in #425.

**Comment by jaquadro** [comment]
See resolution in #521 

Hopper Ducts didn't start supporting the Forge IItemHandler capability (introduced in MC 1.8) until MC 1.11.  You will need to stay with 3.6.2 if you want to keep using hopper ducts with the drawers.
