### ISSUE TITLE
Support plank styles from other mods

### ISSUE THREAD

**Issue by jaquadro** [jaquadro/StorageDrawers#5]
Example:
- Biomes O' Plenty
- Highlands
- Natura
- Twilight Forest

See: Bibliocraft

**Comment by InkDragon** [comment]
Not sure how you implement it currently but there was a discussion of such things over on the bibliocraft github of an easier way to acquire textures so that all plank types are automatically supported like they are in agricraft.

https://github.com/Nuchaz/BiblioCraft/issues/231

**Comment by jaquadro** [comment]
The problem isn't getting the icons, but the fact that I've transformed all of them quite a bit from their vanilla versions.  I don't have a good answer for that.

**Comment by hron84** [comment]
Temporary solution: allow non-supported planks to make oak drawers. Most mods I saw can handle unknown / unsupported planks in this way.

**Comment by jaquadro** [comment]
How many people are looking for a catch-all recipe vs. wanting the actual finish of the other wood?

**Comment by InkDragon** [comment]
I'd like the actual finish of woods if possible. If needed I can do the images for some of them.

**Comment by hron84** [comment]
@jaquadro for example, i play with Regrowth modpack. Since you can only get saplings via Witchery mutandis, there is a chance you do not get any usable vanilla sapling (the quest accepts Dark Oak sapling too but you need 4 Dark Oak sapling to grow a dark oak tree) and Dead Woods produce only finite amount of wood. In these cases catch-all recipe is useful even if I would be much more happy with the correctly colored drawer. In my current world for example I'm out of any supported wood and only have ExtraBiomesXL saplings and woods. Since I have only one sapling from jungle and because of derpy sappiness (sometimes Jungle/Birch does not drop any saplings) I wouldn't want to risk the precious instance of my saplings - but EBXL planks aren't work.

**Comment by codewarrior0** [comment]
I'd like to make drawers out of greatwood planks, even if they come out as oak drawers. I had to go out of my way to find some vanilla trees just to use for drawers after setting up a greatwood farm.

**Comment by jaquadro** [comment]
I implemented a catch-all in 1.4.0-alpha1 to do this, but it depends on the planks being registered to plankWood.  If greatwood is not, then I'm going to need a wood registry.

**Comment by jaquadro** [comment]
Also want to say that since I've started using Biomes O' Plenty in my new server, I'm increasingly interested in having some of those wood types.  I don't think I can get away from huge amounts of manual labor to make it happen though.  Or maybe a day to write an image processing tool that could give me 90% of the texture content I need.

Even though Bibliocraft has moved away from its "Bibliowoods" model, that's probably what I'll have to adopt in this case.

**Comment by codewarrior0** [comment]
I can craft oak drawers using Greatwood in 1.4.0. Nice!

**Comment by hron84** [comment]
@jaquadro thanks for implementing this. I know well catch-all things are usually very far from ideal - but easy to implement and easy to remove after you made your hard work to get better wood-handling. Having something is much better than nothing. :-) Again, thanks for your great assistance in this issue.

**Comment by codewarrior0** [comment]
Just tried crafting Trim blocks using Greatwood. Didn't work, had to use oak.

**Comment by jaquadro** [comment]
I've added the fallback recipes for trim in 1.4.4 (also fixed bad fallbacks for the half-versions).

**Comment by codewarrior0** [comment]
Thanks!

**Comment by jaquadro** [comment]
I've taken a necessary step towards supporting more wood styles.

![drawertool](https://cloud.githubusercontent.com/assets/852988/7669250/664f3fc4-fc36-11e4-82fb-8eeeb2256482.png)

The most laborious part remains creating the underlying base and trim textures.  I went through all of the planks in Biomes O' Plenty and to my dismay relatively few of them were vanilla recolors, which is more work to try and extract a texture.

But now that I have the base textures and an export tool, I need only create the new mod package that adds the new block variants.

**Comment by hron84** [comment]
Nice work!

**Comment by jaquadro** [comment]
The first content pack available is for Natura.

http://minecraft.curseforge.com/mc-mods/230642-storage-drawers-natura-pack

**Comment by InkDragon** [comment]
Thank you so much! I'm so happy to see the natura pack

**Comment by jaquadro** [comment]
There are now packs for [Biomes O' Plenty](http://minecraft.curseforge.com/mc-mods/230832-storage-drawers-biomes-o-plenty-pack) and [Erebus](http://minecraft.curseforge.com/mc-mods/230862-storage-drawers-erebus-pack).

If Erebus seems an odd choice, the author provided me with most of the texture assets I needed.

**Comment by InkDragon** [comment]
Erebus is a lovely choice! Only other mod I know that has added support for them is ExtraTiC. Maybe they will add support for your gardenstuff mod?

**Comment by jaquadro** [comment]
The Erebus author also uses Garden Stuff and did inquire, mainly for the window boxes.  That requires a little more work on my end before it can be supported.  But either one of us could provide the remaining compat.

**Comment by InkDragon** [comment]
Not sure if you will use this or not but I've done images for Plant Mega Pack Bamboo blocks.

https://www.dropbox.com/sh/5qr3cev0fmrf9mh/AAC0KX_EvDza3NG2ZOe3bRima?dl=0

**Comment by jaquadro** [comment]
Did you do those all by hand, or did I put a copy of the generator tool somewhere?

**Comment by InkDragon** [comment]
The generator tool is the erebus texture files here on github. 

The base/trim textures I used are an edited and simplified version of the natura silverbell texture from here as well.

I take it you didn't mean to share the generator.

**Comment by jaquadro** [comment]
Oh, it's meant to be shared, but I didn't think I had checked it in yet.

**Comment by InkDragon** [comment]
Oh cool ^.=.^ in that case I may work on some more textures if you don't mind me doing so.

**Comment by jaquadro** [comment]
You mentioned you used silverbell as the base for all the textures.  It's a good strategy for planks that are a recolor of the vanilla planks.  Not all modded planks fall into that category. For the non-standard planks, I've been tailoring the base textures to use their underlying features.  Examples:

Erebus: Mossbark, Cypress, Marshwood, Bamboo, Rotten, Varnished
Natura: Bloodwood, Hopseed, Redwood, Tigerwood
BOP: Cherry, Dark, Hellbark, Mangrove, Redwood, Willow
