### ISSUE TITLE
Crash Using Drawer Controller

### ISSUE THREAD

**Issue by CWW256** [jaquadro/StorageDrawers#50]
Ender IO alloy smelter connected directly to drawer controller which is connected to 2x2 drawer. Alloy smelter is set to push output to drawer controller. Smelting vanilla iron or gold works fine and ingots are placed into drawers no problem. Smelting ferrous dust produces ferrous ingot but it is not automatically put into drawer even though there are already some ingots in drawer. Ingot just sits in alloy smelter output slot. Crash comes when you try to add an ender io item conduit between the alloy furnace and the drawer controller. Setting item conduit to pull from alloy smelter and push into drawer controller crashes with this http://pastebin.com/z2hD3kgu.

Additionally, the world can not be loaded as you crash again on reload.

While testing to reproduce this crash I was able to produce another crash by setting an alloy smelter directly next to a drawer controller and then setting the alloy smelter to pull from the face touching the controller. (Which you have to scroll through to get to push so its basically a guaranteed crash). http://pastebin.com/4U4rPn02

Edit Update: In additional testing, even vanilla ore processing is crashing. Although it seemed to work sometimes in my original world it is consistently crashing in my test world.

**Comment by jaquadro** [comment]
Thanks, I'll check this evening.  I had a feeling stuff like this would crop up with the new blocks, hence the unusual alpha release (though CurseForge says 0 downloads.  Odd.)

**Comment by jaquadro** [comment]
I couldn't test with EnderIO specifically, but I did find a problem with the inventory code that would probably explain that crash.

I've put up a second alpha, please test and tell me if this solves the issue: http://minecraft.curseforge.com/mc-mods/223852-storage-drawers/files/2229460

I also added a config entry to disable the drawer controller.  That will stop the block from being registered, so flip it off if there's a problem and Forge will yank them out of your world.

**Comment by CWW256** [comment]
Tested both cases (ender io machine pushing output to controller, and conduit pushing out to controller) and had no crash. Was also able to place ender io machine directly next to controller with machine set to push and did not have crash. So the problem seems to be fixed.

In testing I discovered what may be a new problem though.

You are able to extract items from a drawer with ender io conduits from back or sides. In the mod description it says that it not an option, although I am not sure if that is working as intended.

Also, placing any drawer (1x2, 2x2, normal, or compact) then trying to break it in creative mode, plays the breaking animation but the block remains there. Leaving creative then breaking it works fine. However, breaking a drawer controller works as expected in creative. (Not sure if I should open this as a different issue.)

**Comment by jaquadro** [comment]
The description is out of date.  Sides have been valid insert/extract targets for a while.

The creative behavior is unavoidable.  If you hit any side except the front face, then the block should break.  Otherwise, the drawer is interpreting left click as trying to extract items.  The particles are hardcoded into the creative click behavior, so I can't shut them off.
