### ISSUE TITLE
[1.12] Rendering In world / Item issues

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#500]
Hi jaquadro,

Another bug for you...

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.0.2326
- Chameleon 1.12-4.0.0
- Storage Drawers 1.12-5.0.2

### Issue Description

The framed drawers as well as the framing table are either rendering weirdly in item form or not at all and placing any of the framed drawers in world causes an immediate crash which then will continue to crash you if they happen to enter your view.

### Issue Media

![](https://ss.blamesnow.co.uk/2017/06/1497514167-29b1610a.png)

- [https://pastebin.com/fayBhHXf](https://pastebin.com/fayBhHXf)

**Comment by SnowShock35** [comment]
**Update:** It appears the crash bug happens for any of the drawers.

**Comment by jaquadro** [comment]
I wonder if the jar didn't obfuscate correctly?  Or maybe something could have changed in Forge in the last 12 hours.

**Comment by SnowShock35** [comment]
Closed via 70034548b4035c27b1e58b2edd116023ff78d57a
