### ISSUE TITLE
1.12-5.0.3 - Crash when placing drawer.

### ISSUE THREAD

**Issue by MisterShawn** [jaquadro/StorageDrawers#501]
https://gist.github.com/sdaddy/a108d6bd3e3dd3070e801229b6f157d0

Forge: 14.21.0.2331

**Comment by mcdodge34** [comment]
I can relate to this crash, here's the report, I'm using several updated mods for 1.12 and using forge 2331

https://pastebin.com/JS0jYJqh

**Comment by jaquadro** [comment]
Does 1.12-5.0.4 work?

**Comment by MisterShawn** [comment]
That's a negative.

https://gist.github.com/sdaddy/04abe7d426fa9135471c5a71c5e045a2

**Comment by jaquadro** [comment]
I've now replaced the file on curse with one that looks like it's compiled correctly

**Comment by MisterShawn** [comment]
Success! However, I noticed that left clicking takes two items instead of one. I can create a new issue if you'd like.

Thanks for such an amazing mod. I can't wait for rest of the items to be implemented. Keep up the great job!

**Comment by jaquadro** [comment]
Does it always happen, or just when you have an empty hand?  For the later, I think I investigated and couldn't see a way around it.

**Comment by mcdodge34** [comment]
I had this issue since 1.7.10 version for taking 2 items at a time, never ever figured out what could be the cause of this, sometimes I take 1 item out, sometimes 2, same when I get stacks out, and I replaced mouse and keyboard multiple times already so I know its something else.

**Comment by MisterShawn** [comment]
It's every time. I've always had trouble accidentally grabbing two with an empty hand, but now it seems it's doubled. If my hand is empty and I click and hold it'll grab 4 items and 2 if clicked quickly. If I have something in my hand and click quickly or click and hold it'll grab 2 items. I can't seem to get only get 1 item at all.

**Comment by jaquadro** [comment]
The empty hand thing will probably still be a thing, but the rest looks like a bug in the Forge patch.  Attached issue: https://github.com/MinecraftForge/MinecraftForge/issues/4031
