### ISSUE TITLE
Storage Drawers causing Minecraft 1.12 to crash on load

### ISSUE THREAD

**Issue by QueenKawani** [jaquadro/StorageDrawers#502]
I have  installed Storage Drawers and Storage Drawers extra for 1.12 via Twitch.

Upon loading, my minecraft is crashing with the following error message:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Storage Drawers (storagedrawers)

I receive this error with or without any other mods.  I started getting this error yesterday.

I am running forge 14.21.0.2322, Chameleon 1.12-4.0.0 and Storage Drawers 1.12-5.0.3

Any help appreciated
Thank you

**Comment by MisterShawn** [comment]
That's a relatively old version of Forge. The current version definitely loads with Forge 2331, but has a nasty crash when placing down a drawer. See https://github.com/jaquadro/StorageDrawers/issues/501

**Comment by jaquadro** [comment]
Definitely update Forge (I practically need to pull down the new one daily).  General crashing should be fixed in the (re-uploaded) 5.0.4 now.

**Comment by jaquadro** [comment]
This is probably identical to #506 (same Forge version in both cases).  Update Forge.
