### ISSUE TITLE
[1.12] Compacting Drawers miss behaving

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#503]
Hi @jaquadro,

Another, what I believe to be, issue for you. Here's the details;

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.0.2234 (Latest at current time)
- Chameleon 1.12-4.0.0
- Storage Drawers 1.12-5.0.4

### Issues Details

When placing either gold or iron ingots/blocks into the compacting drawers only the block/ingot is added and not the nugget. The only way  for the nugget to appear is if you add the nugget first. 

### Steps to Reproduce

1. Place down compacting drawer
2. Add Iron/Gold Ingot/Block
3. Result? 

### Issue Media

- Compacting Debug Log https://pastebin.com/iBEq139d

![](https://ss.blamesnow.co.uk/2017/06/1497775592-3e1b57a0.png)

**Comment by codewarrior0** [comment]
There's some debug logging you can enable for the compacting drawer which would be helpful. See the author's comment here:

https://github.com/jaquadro/StorageDrawers/issues/477#issuecomment-302274322

**Comment by SnowShock35** [comment]
@codewarrior0 Good idea, thanks for that :-) I'll get that log information right now

**Comment by SnowShock35** [comment]
Updated the post. Now with debug log under issue media. cc @codewarrior0 :-)

**Comment by jaquadro** [comment]
Yeah, something with the descending lookups broke with the recipe system changes.  Still need to dig into it.

**Comment by jaquadro** [comment]
Fixed in 5.0.5.

I had to adapt to the new ingredient system in 1.12.  On one hand, it's a bigger pain to parse through the ingredients to match.  On the other, I got to remove a massive amount of code.
