### ISSUE TITLE
Storage Drawers uncaught exception UnsupportedOperationException

### ISSUE THREAD

**Issue by RtHiaHB** [jaquadro/StorageDrawers#506]
Crash log at: https://pastebin.com/KZ5V0cfS

Happens during launch.

Running:
OS: Win 10
Java version: 8.0.1310.11
Storage Drawers version: StorageDrawers-1.12-5.0.4

If you need any more information, please let me know.

**Comment by jaquadro** [comment]
I can't even begin to understand how this stack trace managed to happen.  It's very strange.

**Comment by RtHiaHB** [comment]
LOL... well, if there's any guy who could find something that baffles programmers, it would be me. :)

Seriously, though, I tried it twice and got the same result.  I just downloaded the latest version of StorageDrawers a couple of hours ago from CurseForge.  I _think_ my Forge version is up to date--I just downloaded it yesterday, so it's up-to-date unless a version's been released in the last 24 hours.

Maybe there's a mod conflict?

Let me try it by taking out all of the other mods except Chameleon and SD and see if that helps.

**Comment by RtHiaHB** [comment]
Nope, no luck.  The only library I need is Chameleon, correct?

**Comment by jaquadro** [comment]
I mis-read your logfile.  It looks like your Forge version is pretty far out of date (relative to the pace of changes in 1.12).  You may need to update it near daily until it's out of beta.

**Comment by jaquadro** [comment]
Also the current version of Forge is 14.21.0.2334.  The one reported in your log is 14.21.0.2322, which is from 1 week ago.

**Comment by RtHiaHB** [comment]
Oh, boy.  That's embarrassing and frustrating simultaneously. I didn't even know it was possible to feel both things at the same time.

It's working fine.  I'm closing this issue.  Thanks for your help.
