### ISSUE TITLE
[1.12] Latest Forge broke... stuff.

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#508]
Hi @jaquadro,

So it appears with your attempt to fix both #503 and #505, you also managed to somehow make it worse.... Only kidding, Forge has just made changes since 14.21.0.2334 (what you're building against) and the latest version 14.21.0.2339. 😛 

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.0.2339
- Chameleon 1.12-4.0.0
- Storage Drawers 1.12-5.0.5

### Issue Details

See #505 for redstone upgrade issue.

Compacting Drawers will now crash if you attempt to click on them with items

### Issue Media

- Crash Report for Compacting Drawers crash https://pastebin.com/Gdh5c3VX

**Comment by jaquadro** [comment]
Oops, that was my bad.  The IDE grabbed the wrong Arrays and I didn't notice.

**Comment by jaquadro** [comment]
Should be fixed in 5.0.6
