### ISSUE TITLE
Missing recipe for large (1x1) drawers

### ISSUE THREAD

**Issue by qchronod** [jaquadro/StorageDrawers#51]
According to NEI with the newest build of your mod, the large single drawer cabinets do not have a recipe. However the 1x2 drawers shows two different recipes, one with a single chest and planks across top/bottom, and the other recipe with two chests and all the rest as planks. I would assume that the first recipe is actually supposed to be for the large drawers since there is only one chest in the recipe.

MC 1.7.10
NEI 1.0.4.90
SD 1.3.0

**Comment by jaquadro** [comment]
Thanks, that was a pretty derpy error on my part.  It's fixed in 1.3.1.
