### ISSUE TITLE
[Feature request] Auto lock drawers on block place when relative keys are in your inventory

### ISSUE THREAD

**Issue by ChickenDuck** [jaquadro/StorageDrawers#511]
Drawers get auto-lock on placement when you have the relative keys are in your inventory (or offhand?) 
Auto-lock feature can be toggled by sneak+right-clicking your key in the air or whatever is better.
Modifying your existing drawer network with active IO will be less hassle.

**Comment by ZeroInputCtrl** [comment]
This would be nice to have.

**Comment by BrianEdmonds** [comment]
I think having drawers autolock if you have the locking key in your
offhand while placing sounds like a nice idea. Just having the key in
your inventory should not be sufficient, IMO.
