### ISSUE TITLE
Rendering Bug for Drawers [1.11.2]

### ISSUE THREAD

**Issue by PessimisticBastard** [jaquadro/StorageDrawers#513]
<a href="http://imgur.com/MP8GDTN"><img src="http://i.imgur.com/MP8GDTN.png" title="source: imgur.com" /></a>

Unsure what could be causing this. Only mods interacting with the drawers are Refined Storage and Extra Utilities. Only started having this issue when I logged in again today. I thought it might have been a Refined Storage issue, but rolling back the mod version to what I had prior and using a backup from before I updated did not fix the issue.

Drawers hold the correct amount of items in them, but display only a stack when opened.

Forge: 13.20.0.2315
Storage Drawers: 4.2.9
EXU2: 1.4.4
Refined Storage: 1.4.18

**Comment by codewarrior0** [comment]
That looks like a HarvestCraft market or something in the foreground. See #432.

**Comment by PessimisticBastard** [comment]
Right, but for the past few days I've been storing Pam's stuff in the drawers, and I've not had this issue. I'll try moving it out of the chunk, and see if it fixes it. Weird if it does, though. Especially since some drawers are not being affected by the bug.

**Comment by codewarrior0** [comment]
Yes, it works to just store Pam stuff in the drawers. The bug happens when you place it in world as a block in the same chunk as the drawers.

The issue is on Pam's side.

**Comment by PessimisticBastard** [comment]
Well, if that's the case, I'll have to remember to never leave the market down again, or any Pam's block, near them when I'm not there. Guess I'll keep it in my inventory. Huh. That's going to cause issues trying to automate any part of Pam's...

**Comment by codewarrior0** [comment]
See also #494

**Comment by PessimisticBastard** [comment]
Well, it worked. You're 100% right. Well, alright then. Closing the issue. This was a problem back in Feb, and it's still not fixed on Pam's side?

**Comment by jaquadro** [comment]
It's been reported https://github.com/MatrexsVigil/harvestcraft/issues/258 and again https://github.com/MatrexsVigil/harvestcraft/issues/231.  It doesn't really look like it's been acknowledged, despite how pervasive the effects of this bug are.  I wouldn't count on a quick fix.

My advice would be to quarantine the affected HC blocks in their own chunks.  Any other TileEntity block runs the risk of getting messed up on the client otherwise.
