### ISSUE TITLE
[1.12] Ability to add Storage Upgrades when Downgrade is Present

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#519]
Hi @jaquadro,

Just a quick bug report/suggestion for Storage Drawers on Minecraft 1.12 (and or other versions if that applies). Here's the details:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2387
- Chameleon 1.12-4.0.2
- Storage Drawers 1.12-5.1.3

### Issue Description

When adding a storage downgrade to a storage drawer you shouldn't be able to add any storage upgrades as it therefore defeating the purpose of the downgrade. At least this is my view on it. You may think otherwise which is totally fine just seemed a tad odd to me.

### Issue Media

![](https://ss.blamesnow.co.uk/2017/07/1498898688-e070cf26.png)

**Comment by codewarrior0** [comment]
See #419 - mixing upgrades is intentional and allows finer control of the storage limit.

**Comment by SnowShock35** [comment]
Ah, My bad. Thanks for the heads up @codewarrior0 :-)
