### ISSUE TITLE
[1.12] In World Pick Block Cannot Determine Wood Variant

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#520]
Hi @jaquadro,

I believe I've found a bug in Storage Drawers for Minecraft 1.12. Here are the details:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2387
- Chameleon 1.12-4.0.2
- Storage Drawers 1.12-5.1.3

### Issue Description

When using the pick block hotkey in world on a storage drawer in creative the drawer is added to the inventory however, it lacks the data tag that stores the variant of wood that it therefore if you copy anything other than an oak drawer it will appear as the oak drawer. I imagine this is due to the fact that NBT data isn't copied to the picked block unless holding the CTRL key (Which does work if used). 

### Issue Media

![](https://ss.blamesnow.co.uk/2017/07/1498900071-e35c7deb.png)
![](https://ss.blamesnow.co.uk/2017/07/1498900100-d8fb0eb1.png)
![](https://ss.blamesnow.co.uk/2017/07/1498900129-44844ca3.png)

**Comment by jaquadro** [comment]
It's 2017 and I didn't even know there was a creative pick block key.

Fixed in dev, so it'll be in 5.2.2.
