### ISSUE TITLE
[1.10.2] update breaks translocators, hopper ducts...

### ISSUE THREAD

**Issue by tralce** [jaquadro/StorageDrawers#521]
In the most recent stable releases for 1.10.2, Translocators no longer will attach to Controllers or Slaves, and Hopper Ducts's Ducts and Grated Hoppers will not work with them either. I beg of you, please fix it.

**Comment by jaquadro** [comment]
Do vanilla hoppers work?  Or manual insertion?

**Comment by tralce** [comment]
Yes, I can use a normal hopper pointed into a Controller or Slave to fill
attached drawers with things, and also can use the normal right click
insertion on a drawer to insert items, and the double right on a controller
to empty my inventory as normal.

Prior to a couple SD updates ago, I had built an item sorting system that
used Translocators to put specific items into specific places -- junk
matching a filter into droppers that dumped junk into lava, a translocator
to send items to an automated furnace, and anything else into a Slave which
put all desired items into the drawer network.

Suddenly now the Translocators can't attach to the Slaves at all (I don't
think that Translocators had an update around this time either) and Hopper
Ducts' Grated Hoppers will attach but won't do anything, while the Hopper
Duct will not attach at all.

**Comment by jaquadro** [comment]
If these were working before updating to 3.7.0 or beyond, then the answer is probably that translocators, hopper ducts, and the like were never updated to work with Forge's IItemHandler interface that was introduced in 1.8.x.  Prior to the 3.7.0 version, I supported both IItemHandler and the older IInventory (from vanilla Minecraft) interfaces.

I didn't intend to drop IInventory support until 1.11.2, but a bug (probably some sort of dupe bug) surfaced that was too difficult to fix with all of that tangled up together.  In your situation, it might be more worthwhile to role back to the last 3.6.x release.

If that wasn't the version that broke it, I need specific version numbers.

**Comment by codewarrior0** [comment]
Apparently, Translocators for 1.10.2 will not be updated to support IItemHandler. The 1.11.2 version will, though. See https://github.com/TheCBProject/Translocators/issues/12

**Comment by jaquadro** [comment]
Hopper Ducts is a closed source mod, but a quick scan through disassembly shows that IItemHandler did not receive support until 1.11.2.

So, sorry, there is no resolution for these two mods, other then going back to 3.6.2.
