### ISSUE TITLE
[1.12.] Launcher Crash with OptFine 

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#522]
The Lauchner crashed if i want to start the 3 Mod together.
OptiFine or Storage Drawers alone works fine.

**Issue Information**
Minecraft 1.12
Minecraft Forge 14.21.0.2359 (Twitch / Curse Launcher)
Chameleon 1.12-4.0.2
Storage Drawers 1.12-5.1.3
OptiFine 1.12 HD U C3

**Comment by jaquadro** [comment]
Your Forge looks old.  Update that first.

**Comment by ghost** [comment]
Thanks, the Forge has need an update. Now it runs perfekt ;)

Thank you
