### ISSUE TITLE
placing storage draws crashes game ? StorageDrawers-1.12-5.2.0.jar 

### ISSUE THREAD

**Issue by 5kedone** [jaquadro/StorageDrawers#525]
here is crash report for you

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.12-2.337-full.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  AstralCore (astralsorcery-1.5.8.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/6/17 9:00 AM
Description: Unexpected error

java.lang.NoSuchMethodError: com.jaquadro.minecraft.storagedrawers.api.storage.IDrawer.isEnabled()Z
	at com.jaquadro.minecraft.storagedrawers.block.tile.tiledata.StandardDrawerGroup.syncSlots(StandardDrawerGroup.java:122)
	at com.jaquadro.minecraft.storagedrawers.block.tile.tiledata.StandardDrawerGroup.<init>(StandardDrawerGroup.java:32)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard$GroupData.<init>(TileEntityDrawersStandard.java:214)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard$Slot4.<init>(TileEntityDrawersStandard.java:76)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard.createEntity(TileEntityDrawersStandard.java:141)
	at com.jaquadro.minecraft.storagedrawers.block.BlockStandardDrawers.createNewTileEntity(BlockStandardDrawers.java:193)
	at com.jaquadro.minecraft.storagedrawers.block.BlockStandardDrawers.func_149915_a(BlockStandardDrawers.java:37)
	at net.minecraft.block.Block.createTileEntity(Block.java:1241)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:622)
	at net.minecraft.world.World.func_180501_a(World.java:340)
	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:647)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
	at com.jaquadro.minecraft.storagedrawers.item.ItemDrawers.placeBlockAt(ItemDrawers.java:42)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:471)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2248)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2014)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1801)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.jaquadro.minecraft.storagedrawers.block.tile.tiledata.StandardDrawerGroup.syncSlots(StandardDrawerGroup.java:122)
	at com.jaquadro.minecraft.storagedrawers.block.tile.tiledata.StandardDrawerGroup.<init>(StandardDrawerGroup.java:32)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard$GroupData.<init>(TileEntityDrawersStandard.java:214)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard$Slot4.<init>(TileEntityDrawersStandard.java:76)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard.createEntity(TileEntityDrawersStandard.java:141)
	at com.jaquadro.minecraft.storagedrawers.block.BlockStandardDrawers.createNewTileEntity(BlockStandardDrawers.java:193)
	at com.jaquadro.minecraft.storagedrawers.block.BlockStandardDrawers.func_149915_a(BlockStandardDrawers.java:37)
	at net.minecraft.block.Block.createTileEntity(Block.java:1241)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:622)
	at net.minecraft.world.World.func_180501_a(World.java:340)
	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:647)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
	at com.jaquadro.minecraft.storagedrawers.item.ItemDrawers.placeBlockAt(ItemDrawers.java:42)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:471)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2248)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2014)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['skedone'/224, l='MpServer', x=29.67, y=61.00, z=6.23]]
	Chunk stats: MultiplayerChunkCache: 413, 413
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (184,64,252), Chunk: (at 8,4,12 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 54206 game time, 54206 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 69 total; [EntitySquid['Squid'/10242, l='MpServer', x=12.39, y=56.33, z=-34.74], EntitySquid['Squid'/10244, l='MpServer', x=8.29, y=53.61, z=22.02], EntityItem['item.tile.stonebrick'/9990, l='MpServer', x=37.88, y=58.00, z=10.14], EntityZombieVillager['Zombie Villager'/10502, l='MpServer', x=28.50, y=22.00, z=-50.50], EntitySquid['Squid'/10250, l='MpServer', x=81.70, y=57.00, z=-51.06], EntitySquid['Squid'/10251, l='MpServer', x=83.49, y=52.25, z=-52.79], EntityCreeper['Creeper'/4878, l='MpServer', x=48.17, y=64.00, z=24.36], EntityCreeper['Creeper'/10007, l='MpServer', x=-19.50, y=29.00, z=31.50], EntityZombie['Zombie'/10775, l='MpServer', x=78.74, y=19.00, z=-35.51], EntityZombie['Zombie'/10776, l='MpServer', x=82.50, y=19.00, z=-37.50], EntityZombie['Zombie'/10777, l='MpServer', x=82.50, y=19.00, z=-35.50], EntityZombie['Zombie'/10778, l='MpServer', x=82.50, y=19.00, z=-38.50], EntityZombie['Zombie'/10016, l='MpServer', x=87.50, y=28.00, z=-43.50], EntityCreeper['Creeper'/10538, l='MpServer', x=93.50, y=39.00, z=58.50], EntityBat['Bat'/10029, l='MpServer', x=63.44, y=19.99, z=-39.22], EntityZombie['Zombie'/10559, l='MpServer', x=99.50, y=27.00, z=-45.50], EntityCreeper['Creeper'/10308, l='MpServer', x=61.50, y=24.00, z=-49.50], EntityCreeper['Creeper'/9808, l='MpServer', x=3.50, y=37.00, z=59.50], EntityBat['Bat'/10586, l='MpServer', x=-47.62, y=30.52, z=-14.20], EntityCreeper['Creeper'/10589, l='MpServer', x=25.50, y=14.00, z=16.50], EntitySquid['Squid'/10091, l='MpServer', x=-17.21, y=59.00, z=-48.96], EntitySquid['Squid'/10093, l='MpServer', x=-9.92, y=59.14, z=-43.48], EntitySquid['Squid'/10095, l='MpServer', x=29.30, y=54.61, z=73.18], EntityCreeper['Creeper'/10613, l='MpServer', x=103.50, y=34.00, z=54.50], EntityCreeper['Creeper'/10358, l='MpServer', x=88.46, y=31.00, z=47.79], EntityAncientGolem['Ancient Golem'/8059, l='MpServer', x=-14.78, y=27.00, z=17.63], EntityCreeper['Creeper'/10364, l='MpServer', x=61.50, y=21.00, z=-67.50], EntitySquid['Squid'/10109, l='MpServer', x=71.95, y=59.56, z=-25.46], EntityZombie['Zombie'/10621, l='MpServer', x=51.73, y=22.00, z=-55.50], EntitySquid['Squid'/10110, l='MpServer', x=72.54, y=60.54, z=25.82], EntityZombie['Zombie'/10622, l='MpServer', x=44.43, y=23.00, z=-55.09], EntitySquid['Squid'/10111, l='MpServer', x=76.87, y=61.36, z=18.40], EntitySpider['Spider'/10367, l='MpServer', x=62.50, y=21.00, z=-67.50], EntitySpider['Spider'/10629, l='MpServer', x=29.97, y=34.00, z=-51.35], EntitySpider['Spider'/10630, l='MpServer', x=27.50, y=34.00, z=-52.50], EntityCreeper['Creeper'/5772, l='MpServer', x=46.20, y=65.00, z=12.48], EntityCreeper['Creeper'/5775, l='MpServer', x=44.84, y=65.00, z=16.39], EntityCreeper['Creeper'/10639, l='MpServer', x=80.50, y=28.00, z=-39.50], EntityCreeper['Creeper'/5776, l='MpServer', x=51.83, y=64.00, z=9.82], EntitySkeleton['Skeleton'/10641, l='MpServer', x=38.50, y=21.00, z=-50.50], EntityAncientGolem['Ancient Golem'/10642, l='MpServer', x=20.50, y=39.00, z=-54.50], EntitySquid['Squid'/10131, l='MpServer', x=88.88, y=54.80, z=35.57], EntityBat['Bat'/10402, l='MpServer', x=100.58, y=34.69, z=51.41], EntitySquid['Squid'/10157, l='MpServer', x=20.02, y=52.23, z=43.31], EntitySquid['Squid'/10160, l='MpServer', x=16.94, y=46.20, z=39.65], EntityBat['Bat'/9402, l='MpServer', x=47.69, y=18.21, z=10.67], EntityCreeper['Creeper'/10683, l='MpServer', x=67.50, y=20.00, z=-32.50], EntitySquid['Squid'/10173, l='MpServer', x=-8.24, y=60.12, z=-9.19], EntityZombie['Zombie'/10686, l='MpServer', x=59.50, y=30.00, z=34.09], EntityZombie['Zombie'/10687, l='MpServer', x=59.50, y=30.00, z=34.70], EntityEnderman['Enderman'/6346, l='MpServer', x=45.39, y=65.00, z=6.49], EntityCreeper['Creeper'/10443, l='MpServer', x=47.50, y=19.00, z=-6.50], EntitySpider['Spider'/10445, l='MpServer', x=46.50, y=19.00, z=-5.50], EntityBat['Bat'/10709, l='MpServer', x=26.24, y=34.78, z=-48.39], EntityBat['Bat'/10710, l='MpServer', x=26.50, y=34.90, z=-50.00], EntityCreeper['Creeper'/9690, l='MpServer', x=107.50, y=16.00, z=-19.50], EntityBat['Bat'/10714, l='MpServer', x=109.33, y=35.11, z=81.18], EntityItem['item.item.rottenFlesh'/10463, l='MpServer', x=38.63, y=65.00, z=2.71], EntityPlayerSP['skedone'/224, l='MpServer', x=29.67, y=61.00, z=6.23], EntityZombie['Zombie'/10725, l='MpServer', x=-34.49, y=25.00, z=10.79], EntityCreeper['Creeper'/10727, l='MpServer', x=31.46, y=33.00, z=-39.19], EntitySkeleton['Skeleton'/10472, l='MpServer', x=-27.50, y=21.00, z=-58.50], EntitySkeleton['Skeleton'/10728, l='MpServer', x=26.50, y=33.00, z=-37.50], EntitySkeleton['Skeleton'/10729, l='MpServer', x=26.50, y=33.00, z=-37.50], EntitySkeleton['Skeleton'/10731, l='MpServer', x=103.50, y=24.00, z=-47.50], EntitySquid['Squid'/10221, l='MpServer', x=10.57, y=59.61, z=64.76], EntitySquid['Squid'/10222, l='MpServer', x=19.32, y=60.73, z=54.84], EntityCreeper['Creeper'/10489, l='MpServer', x=53.50, y=22.00, z=-59.50], EntitySkeleton['Skeleton'/7420, l='MpServer', x=46.90, y=65.00, z=6.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2360746728 bytes (2251 MB) / 5316411392 bytes (5070 MB) up to 5316411392 bytes (5070 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -Xms5G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2395 Optifine OptiFine_1.12_HD_U_C4 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2395.jar) 
	UCHIJAAAA	forge{14.21.1.2395} [Minecraft Forge] (forge-1.12-14.21.1.2395.jar) 
	UCHIJAAAA	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r113} [Actually Additions] (ActuallyAdditions-1.12-r113.jar) 
	UCHIJAAAA	astralsorcery{1.5.8} [Astral Sorcery] (astralsorcery-1.5.8.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJAAAA	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.0} [Chameleon] (Chameleon-1.12-4.1.0.jar) 
	UCHIJAAAA	chancecubes{1.12-3.0.1.197} [Chance Cubes] (ChanceCubes-1.12-3.0.1.197.jar) 
	UCHIJAAAA	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UCHIJAAAA	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.0} [Redstone Flux] (RedstoneFlux-1.12-2.0.0.1-universal.jar) 
	UCHIJAAAA	cofhcore{4.3.0} [CoFH Core] (CoFHCore-1.12-4.3.0.5-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.5-universal.jar) 
	UCHIJAAAA	cyclopscore{0.10.7} [Cyclops Core] (CyclopsCore-1.12-0.10.7.jar) 
	UCHIJAAAA	colossalchests{1.6.2} [Colossal Chests] (ColossalChests-1.12-1.6.2.jar) 
	UCHIJAAAA	jei{4.7.1.71} [Just Enough Items] (jei_1.12-4.7.1.71.jar) 
	UCHIJAAAA	cyclicmagic{1.5.9} [Cyclic] (Cyclic-1.12-1.5.9.jar) 
	UCHIJAAAA	darkutils{1.6.159} [Dark Utilities] (DarkUtils-1.12-1.6.159.jar) 
	UCHIJAAAA	movingworld{1.12-2.337} [Moving World] (movingworld-1.12-2.337-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-2.331-full.jar) 
	UCHIJAAAA	forestry{5.4.3.128} [Forestry] (forestry_1.12-5.4.3.128.jar) 
	UCHIJAAAA	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UCHIJAAAA	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.12-1.4.8beta1.jar) 
	UCHIJAAAA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJAAAA	embers{0.219} [Embers] (embers-0.219.jar) 
	UCHIJAAAA	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCHIJAAAA	endertanks{1.6.0.1} [EnderTanks] (endertanks-1.12.0-1.6.0.1.jar) 
	UCHIJAAAA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJAAAA	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.12-6.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.2.jar) 
	UCHIJAAAA	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.12-alpha-0.0.1.jar) 
	UCHIJAAAA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJAAAA	gbook{1.7.3} [Guidebook] (Guidebook-1.12.0-1.7.3.jar) 
	UCHIJAAAA	inventorytweaks{1.63+dev.98.684f99a} [Inventory Tweaks] (InventoryTweaks-1.63+dev.98.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	jeresources{0.8.1.14} [Just Enough Resources] (JustEnoughResources-1.12-0.8.1.14.jar) 
	UCHIJAAAA	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCHIJAAAA	megaquarry{1.3} [Mega Quarry] (MegaQuarry-1.3-1.12.jar) 
	UCHIJAAAA	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1.jar) 
	UCHIJAAAA	mysticalagradditions{1.2.0} [Mystical Agradditions] (mysticalagradditions[1.12]-1.2.0.jar) 
	UCHIJAAAA	notenoughwands{1.5.8} [Not Enough Wands] (notenoughwands-1.12-1.5.8.jar) 
	UCHIJAAAA	packingtape{0.7.3} [Packing Tape] (PackingTape-1.12.0-0.7.3.jar) 
	UCHIJAAAA	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	randomthings{4.0.1} [Random Things] (RandomThings-MC1.12-4.0.1.jar) 
	UCHIJAAAA	reborncore{3.2.3.83} [Reborn Core] (RebornCore-1.12-3.2.3.83-universal.jar) 
	UCHIJAAAA	thermalfoundation{2.3.0} [Thermal Foundation] (ThermalFoundation-1.12-2.3.0.3-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.0} [Thermal Expansion] (ThermalExpansion-1.12-5.3.0.4-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.3.0} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.0.4-universal.jar) 
	UCHIJAAAA	refinedstorage{1.5.7} [Refined Storage] (refinedstorage-1.5.7.jar) 
	UCHIJAAAA	rftools{6.10} [RFTools] (rftools-1.12-6.10beta3.jar) 
	UCHIJAAAA	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta1.jar) 
	UCHIJAAAA	roots{0.024} [Roots 2] (roots-2-0.024.jar) 
	UCHIJAAAA	scannable{1.4.0.5} [Scannable] (Scannable-MC1.12-1.4.0.5.jar) 
	UCHIJAAAA	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.0.jar) 
	UCHIJAAAA	simplytea{1.4} [Simply Tea] (simplytea-1.4.jar) 
	UCHIJAAAA	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.4.25.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.2.0} [Storage Drawers] (StorageDrawers-1.12-5.2.0.jar) 
	UCHIJAAAA	tammodized{0.13.3} [TamModized] (TamModized-1.12-0.13.3.jar) 
	UCHIJAAAA	theoneprobe{1.4.11} [The One Probe] (theoneprobe-1.12-1.4.11.jar) 
	UCHIJAAAA	thermaldynamics{2.3.0} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.0.4-universal.jar) 
	UCHIJAAAA	torchmaster{1.5.0.31} [TorchMaster] (torchmaster_1.12-1.5.0.31.jar) 
	UCHIJAAAA	totemic{1.12-0.8.10} [Totemic] (Totemic-1.12-0.8.10.jar) 
	UCHIJAAAA	uniquecrops{0.1.2} [Unique Crops] (uniquecrops-1.12-0.1.2.jar) 
	UCHIJAAAA	veinminer{0.36.0} [Vein Miner] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCHIJAAAA	veinminermodsupport{0.36.0} [Mod Support] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCHIJAAAA	voidcraft{0.21.1} [VoidCraft] (VoidCraft-1.12-0.21.1.jar) 
	UCHIJAAAA	waterstrainer{3.1.1} [Water Strainer] (WaterStrainer-1.12-3.1.1.jar) 
	UCHIJAAAA	xnet{1.3.4} [XNet] (xnet-1.12-1.3.4.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.12-2.337-full.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
AstralCore (astralsorcery-1.5.8.jar)
  
LoadingPlugin (RandomThings-MC1.12-4.0.1.jar)
  lumien.randomthings.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.165.1' Renderer: 'Radeon (TM) RX 480 Graphics'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.3.83
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12-forge1.12-14.21.1.2395
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.5.13474 Compatibility Profile Context 22.19.165.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.165.1
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by jaquadro** [comment]
Looks like a conflict with another mod that packed my API.  Try first without Refined Storage, and if it's not that, then need to figure out which mod in your list has an outdated API.

**Comment by 5kedone** [comment]
sure thing will try later i have just downgraded for now to one before

**Comment by rannday** [comment]
Same issue. Removing Refined Storage fixed the issue. 

StorageDrawers 1.12.-5.2.1
RefinedStorage 1.5.7

**Comment by jaquadro** [comment]
Ok.  Well I'm already working with RS now on the updated API so it should be sorted out within a couple of days.  Possible workaround is to rename StorageDrawers to "AStorageDrawers" or something, so it's before RS in the mod order.  Adding StorageDrawersExtras may further help boost it in the load order.

**Comment by 5kedone** [comment]
Can confirm the update of both kids now play nice together good work guys

nope i take it back same crash with latest version of both mods ? 
place draw and game go boom

**Comment by jaquadro** [comment]
Separate bug on my side I accidentally introduced in 5.2.2.  It's fixed in 5.2.3.

**Comment by 5kedone** [comment]
you having one of them weeks as well then too mate lol will load it up later and give it a go
