### ISSUE TITLE
[1.12] Move the Conversion Upgrade in the Creative Tab

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#526]
Hi @jaquadro,

I've a minor suggestion/request for the latest version of Storage Drawers for Minecraft 1.12. Here's the details:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2389
- Chameleon 4.1.0
- Storage Drawers 5.2.0

### Issue Description

In the creative tab you have all of the upgrades grouped together at the top of the list. All besides the conversion upgrade which I assume is at the bottom because of being a new addition. I feel like it would be  logical to move the conversion upgrade to the top of the creative tab so it's grouped with all other upgrades. This is not some major issue nor something of high priority. Just a finishing touch if you will.

### Issue Media

![](https://ss.blamesnow.co.uk/2017/07/1499373820-2e89ef7f.png)
![](https://ss.blamesnow.co.uk/2017/07/1499373836-4a2f81ab.png)

**Comment by jaquadro** [comment]
I think if you start a new world, it will be in the correct place.  It's a later addition so Forge has registered it after the others

**Comment by SnowShock35** [comment]
@jaquadro As yes, so it is. My bad. Thanks :-)
