### ISSUE TITLE
[1.12] Drawer GUI Title is Null

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#527]
Hi @jaquadro,

I believe I have found an issue in Storage Drawers for Minecraft 1.12. Here are the details of the issue:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2389
- Chameleon 4.1.0
- Storage Drawers 5.2.0

### Issue Description

All drawer inventories are supposed to have a title in the top left that indicates the type of drawer it is. However, in this version all of them just say `[null]` (as seen in the screenshots).

### Issue Media

![](https://ss.blamesnow.co.uk/2017/07/1499374491-9d13b621.png)
![](https://ss.blamesnow.co.uk/2017/07/1499374498-17b88c5c.png)
![](https://ss.blamesnow.co.uk/2017/07/1499374509-f0c3826c.png)

**Comment by jaquadro** [comment]
Fixed in Chameleon 4.1.1.
