### ISSUE TITLE
[1.12] Re-Add The One Probe Integration

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#528]
Hi @jaquadro,

I believe I have found an issue in Storage Drawers for Minecraft 1.12. Here are the details of the issue:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2389
- Chameleon 4.1.0
- Storage Drawers 5.2.0

### Issue Description

In previous versions of Storage Drawers, The One Probe mod was able to give more in-depth information about the drawers contents. However, as of this version that feature is no longer present. I imagine this is probably just due to the fact you're rewriting the mod. 

Also, if you decide to re-implement the integration could you have it so that when you shift over a drawer it shows you the installed upgrades and key status' too? Would be awesome additional information.

**Comment by jaquadro** [comment]
I never added explicit integration, so it's possible my changes broke what TOP was doing.  It might be worth doing a full integration tho.

**Comment by SnowShock35** [comment]
Yeah it would be awesome to see full support. There's docs for it here, should you need them https://wiki.mcjty.eu/modding/index.php/API_TOP-1.12 🙂

**Comment by jdarmst** [comment]
Any update on this @jaquadro ? Would love to see it.

**Comment by jaquadro** [comment]
Sorry, nothing to report yet.

**Comment by Seth0067** [comment]
+1 for this jaquadro, when you get to it.  Thanks in advance!

**Comment by Artemish** [comment]
I've worked on some TOP addons so I might be able to help. What kind of information used to be shown in the UI that isn't anymore?

**Comment by bgottfried91** [comment]
Main issue I've noticed is that TOP doesn't show item counts in drawers, which is very unfortunate*.

*At least not in a compacting drawer. Will test with standard storage drawer soon and edit if those do work.

Using TOP 1.12-1.4.22 as part of The Best of Both Skyblocks 2 pack from the Twitch launcher.

**Comment by SnowShock35** [comment]
What I believed to be a bug was actually just a configuration option that needed tweaking. My apologies. As such I'm going to close the issue.

**Comment by bgottfried91** [comment]
@SnowShock35 can you clarify which configs you changed (TOP or Storage Drawers) and what was changed specifically? I did a superficial look at the TOP configs when I noticed the compacting drawer not showing item count and didn't remember seeing anything specific to Storage Drawers in the TOP configs.

**Comment by SnowShock35** [comment]
Certainly @bgottfried91.

To get contents of compacting, framed drawers, extra drawers to show up by default you need to first open `theoneprobe.cfg` and find the 'S:showContentsWithoutSneaking' (Figure 1), and add the following three values:

```
storagedrawers:compdrawers
storagedrawers:customdrawers
storagedrawersextra:extra_drawers
```

... The end result should look like the below snippet (Figure 2). Finally, save and close your config and restart the game/load up the game. 

#### Figure 1
```
# A list of blocks for which we automatically show chest contents even if not sneaking [default: [storagedrawers:basicDrawers], [storagedrawersextra:extra_drawers]]
    S:showContentsWithoutSneaking <
        storagedrawers:basicdrawers
     >
```

#### Figure 2
```
# A list of blocks for which we automatically show chest contents even if not sneaking [default: [storagedrawers:basicDrawers], [storagedrawersextra:extra_drawers]]
    S:showContentsWithoutSneaking <
        storagedrawers:basicdrawers
        storagedrawers:compdrawers
        storagedrawers:customdrawers
        storagedrawersextra:extra_drawers
     >
```

**Comment by SnowShock35** [comment]
This gives you an idea of what it then looks like. https://imgur.com/a/NTzLz5K

NB: I have `I:needsProbe` set to 0.
