### ISSUE TITLE
[1.10.2-3.7.9] Compacting Drawer will match erroneous recipes, allowing for item duplication, if the item has a recipe where 1 item = 9 of itself.

### ISSUE THREAD

**Issue by JaSpr** [jaquadro/StorageDrawers#529]
Users can store eezo blocks/ingots from the Tinkers Alloying / TAIGA mod in a Compacting Drawer and then start pulling full ingots out of the "nugget" slot, thereby possibly multiplying their inventory of ingots by 9.  They can then put those ingots back in the "ingot" slot, and continue to endlessly duplicate their eezo ingots.

![screenshot](http://i.imgur.com/jaxRkbI.png)

# Versions
Pack: All The Mods 1, v3.00b
Minecraft: 1.10.2
Forge: 12.18.3.2316
Storage Drawers: 1.10.2-3.7.9
TAIGA / Tinkers Alloying: 1.10.2-1.2.6

TAIGA ticket: TeamFRM/TAIGA#147

**Comment by JaSpr** [comment]
This issue is caused because there is a recipe in the pack where 1 Eezo Ingot = 9 Eezo Ingot.  Obviously, that means the cause of this bug doesn't lie with Storage Drawers, however, I believe a check could be added to verify that none of the three slots can show an item that exists in another slot.

**Comment by jaquadro** [comment]
If you can put that ingot on a crafting table and get 9 back, it's probably not worth any further checking on my part.  The author or pack maker should be asked to fix the recipe.

**Comment by JaSpr** [comment]
I submitted a pull request and it was merged in, so the next release should have that resolved.  If there's no need to verify that one item in a compacting drawer isn't equal to another item, then this can be closed.
