### ISSUE TITLE
Placing multiple drawer controllers on top of each other causes server to crash.

### ISSUE THREAD

**Issue by ImKonor** [jaquadro/StorageDrawers#53]
When placing a drawer controller on top of another controller, it causes the server to crash.

Here is the crashlog: http://pastebin.com/X7aw8FK2

**Comment by jaquadro** [comment]
Did you test this on 1.3.2?  This is one of the things that was supposed to be fixed in that build.

**Comment by ImKonor** [comment]
We haven't tried that, as we're on a server that a load of people play on, changing a mod version would cause some confusion.

**Comment by jaquadro** [comment]
If you cannot update the mod (because you're bound to the Regrowth pack version or something like that), please disable (or ask your op to disable) the drawer controller block in the config.  There are unfortunately a couple crashers in 1.3.1.

**Comment by jaquadro** [comment]
Disabling the block will prevent it from being registered, which will cause Forge to remove any crashing instances of it from the server.

**Comment by ImKonor** [comment]
I have suggested that to the Admin, he said he will do so if the attempt to fix the problem doesn't work.

Thanks for the help.

**Comment by Saphrym** [comment]
Hi! I'm the admin of PurpleMentat's Regrowth server. I want to say thanks for the quick responses! You're awesome! And having that config in your mod is awesome too. ;)

**Comment by jaquadro** [comment]
Oh man, I don't want to be responsible for bringing that down!  Thanks, though.  I honestly don't know what will happen if that's turned off on the server and on on the clients, so at worst it may only be good for clearing a bad instance out of the world.  Hopefully there will be a pack update soon.

So who's going to tell PurpleMentat his smeltery output is broken now? :P

**Comment by Saphrym** [comment]
I told him. :P But changing that setting removed them all from the server. So I put it back afterwards and they are craftable again. So, working as expected. :)

**Comment by jaquadro** [comment]
Resolved in the last few builds and Regrowth 0.7.2.
