### ISSUE TITLE
crash when placing storage drawer next to controller but may be drawer itself(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [jaquadro/StorageDrawers#530]
Forge:1.12-2402
Storage Drawers: 1.12-5.2.2

Crash Report:
[crash-2017-07-08_22.33.58-client.txt](https://github.com/jaquadro/StorageDrawers/files/1132969/crash-2017-07-08_22.33.58-client.txt)

**Comment by Kris1432** [comment]
Can confirm that i'm getting it over here to. 

Forge: 2395
Version 1.12-5.2.2

Report:
https://pastebin.com/MU5R1uHu

**Comment by jaquadro** [comment]
Fixed in 5.2.3
