### ISSUE TITLE
Crash When Placing

### ISSUE THREAD

**Issue by crazyamri** [jaquadro/StorageDrawers#532]
Hi there.

I'm playing on my single world. somehow i got crash when trying to put drawer. never happen before. help please. i'll attach the crash log, maybe you can help me finding the source of crash?

thank you.

https://pastebin.com/embed_js/AhmkwH0w

**Comment by jaquadro** [comment]
Update Chameleon

**Comment by crazyamri** [comment]
yeah, just did. work perfect. thanks. 

p/s: on other note, does anyone know why some of modded machine/blocks invisible / facing other ways?

**Comment by jaquadro** [comment]
You have harvestcraft installed.  Do you have any harvestcraft blocks nearby?

**Comment by crazyamri** [comment]
no, i don't have harvestcraft. it's fine tho, not a big deal. just kinda annoying. thanks for the help.
