### ISSUE TITLE
[1.12] Localisation Completely Broken

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#533]
Hi @jaquadro,

It appears the latest update of Storage Drawers for Minecraft 1.12 has an issue. Here are the details regarding said issue:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2405
- Chameleon 1.12-4.1.1
- Storage Drawers 1.12-5.2.4

### Issue Description

All localisation is broken... I think you made a boo boo. 

### Issue Media

![](https://ss.blamesnow.co.uk/2017/07/1499602090-4117af42.png)

**Comment by jaquadro** [comment]
I think I may have gotten myself into a situation where fixing it in release breaks it in dev and vis versa.

**Comment by SnowShock35** [comment]
Oh dear :/ That's not good.

**Comment by jaquadro** [comment]
Yup.  "Fixed" in 5.2.5, but it's totally broken in my dev env now.

**Comment by SnowShock35** [comment]
Would  you like me to try see if it's just your dev environment and setup my own storage drawers dev env?

**Comment by jaquadro** [comment]
Maybe?  The problem seems to revolve around pack.mcmeta and lower-casing my lang files to match vanilla/other mods I've looked at.

Without the pack.mcmeta file, dev runtime is fine but release is borked.  With the pack.mcmeta file, it's the other way around.

**Comment by SnowShock35** [comment]
I'll give it a shot here in a sec and I'll let you know if I have any luck

**Comment by SnowShock35** [comment]
@jaquadro I had no issues in both dev and once built.

**Comment by jaquadro** [comment]
Finally figured this out.  The files were still uppercase in IDEA's /out/production.  Since Windows files are caseless, it didn't update the names even though the source files were all lower.
