### ISSUE TITLE
[1.12] Compacting drawers duplicating items when using Refined Storage/RFTools.

### ISSUE THREAD

**Issue by TheSaucyWelshman** [jaquadro/StorageDrawers#535]
I posted [this](https://github.com/McJty/RFTools/issues/1278) issue to RFTools earlier today but it seems something similar is happening with Refined Storage.

When I pull items from a compacting drawer from either a Grid from RS or the Storage Scanner from RFTools it doesn't pull the correct number of items from the drawer. 

With ingots it seems to only pull 7-8 from the drawer even though it gives you a full stack, if it's available. I tested Iron blocks with RS and it gave me 14 and left all 7 in the drawer.

Normal drawers seem to work as intended.

Forge: 14.21.1.2406
Storage Drawers: 1.12-5.2.7

**Comment by jaquadro** [comment]
Dang, really was hoping I'd ironed out all that crap by now.

**Comment by jaquadro** [comment]
Fixed in 5.2.8.  Compacting drawer wasn't applying the conversion factor on negative adjustment so ... massive dups.
