### ISSUE TITLE
compacting drawer problem

### ISSUE THREAD

**Issue by that1dog** [jaquadro/StorageDrawers#537]
I put 64 gold ingots into a compressing drawer and the drawer said I had 64 ingots as well as 64 blocks, instead of 7 blocks

**Comment by jaquadro** [comment]
Need more information.  Mod version, where you're getting the reading from, SP or MP.

**Comment by that1dog** [comment]
![screen shot 2017-07-11 at 9 42 16 pm](https://user-images.githubusercontent.com/30084317/28100843-e298ce12-6681-11e7-8ab4-67482f4d1b91.png)

mod version "StorageDrawers-1.12-5.2.8"
As shown in the image the reading comes from using the quantify key on the drawer.
I don't know what the difference is between SP and MP
I have no mods that affect the oreDict

**Comment by that1dog** [comment]
mod version "StorageDrawers-1.12-5.2.8"
I don't know what the difference is between SP and MP

**Comment by BrianEdmonds** [comment]
SP == single player, MP (I've usually seen SMP) == server multiplayer.
What modpack you're playing with could also be relevant, if it's not a
simple SD problem.

**Comment by jaquadro** [comment]
This is fixed in 5.2.9.  The trick was populating the drawer with the smallest item.
