### ISSUE TITLE
[1.11.2] Crash with Storage Controller & TD on chunk unload

### ISSUE THREAD

**Issue by Terpo** [jaquadro/StorageDrawers#542]
Forge: 13.20.1.2386
Thermal Dynamics: 2.2.5
Storage Drawers: 4.2.10

First before posting the log. I already talked King Lemming about the crash here:
https://github.com/CoFH/Feedback/issues/364

The actual log can be found here: https://gist.github.com/Terpo/770e7804b8dbeb9694c1786c085710a0

Because I knew which building causes this crash it took me a week with testing all servos to find out which creation causes this crash and I found it:

http://terpo.org/blog/upload/mc/bugs/2017-07-18_19.48.25.png

So, the golden servos are trying to pull from the drawer and these cause the server to crash. The crash does only happen if the area is loaded and the player is leaving the area. (changing dimension / leaving server). A few minutes after that the server crashes with the log above.

As KL added a check on his side I just want to inform you that sometimes your controller seems to return a null instead of a ItemCapabilityHandler.

If you need more info I'll be there :).

**Comment by jaquadro** [comment]
I don't really see how it's possible for the controller to return null.

https://github.com/jaquadro/StorageDrawers/blob/1.11.2/src/com/jaquadro/minecraft/storagedrawers/block/tile/TileEntityController.java#L728

The handler is created during object construction, and sticks around for the lifetime of the tile.

**Comment by Terpo** [comment]
I see, also the capability functions can't return null.... well. As I said, he did a fix on his side and as this problem only occurs for us when leaving the area it would be ok if servos stop working. No idea if a other mod could mess around with chunk unloading so that the controller gets unloaded earlier or something. 

As your controller seems ok I think it would be the easiest way to update my server and ignore it^^

**Comment by Terpo** [comment]
I close this as the problem hopefully got fixed on IE side (Coke Oven)
