### ISSUE TITLE
[1.12] Creative Storage upgrade not working on a compacting drawer

### ISSUE THREAD

**Issue by 016Nojr** [jaquadro/StorageDrawers#544]
Duplicate of #540 but this will contain more information.

The creative storage upgrade (For infinite storage) doesnt work on a normal compacting drawer.
In this example, It stopped on the magic number 1024, it's two stages and the final stage requires 4 of the "previous" item, therefor that is 4096. The item/block in this specific drawer is the Certus Quartz Crystal/Certus Quartz Block. However, when I have a storage bus connected to the drawer system, that "bypasses" the 1024 limit, but when I try extracting something (manually, by clicking), it drops enough items so it goes down to 1024 excactly.

Mod versions:
Forge: 14.21.1.2426
AE2: Unofficial
Chameleon: 4.1.3
Storage Drawers: 5.2.9

Custom modpack, but modlist can be provided if wanted.
Logs can also be provided if needed.

**Comment by jaquadro** [comment]
Thanks.  Fixed in 5.3.0.
