### ISSUE TITLE
Cobble is disapearing

### ISSUE THREAD

**Issue by NicosaurusRex99** [jaquadro/StorageDrawers#550]
SD version 5.2.9
Forge Version 14.21.1.2443
Charmelion 4.1.3
I am recording my LP and the only itemstack that seams to disapear is cobble. is this a prank or a bug?

**Comment by jaquadro** [comment]
Do you have TOP installed?  So far, it is the only cause I know of for disappearing items.  It's probably fixed in a newer release now.

**Comment by NicosaurusRex99** [comment]
That would be it!

**Comment by jaquadro** [comment]
Sorry, to clarify, I meant TOP Addons specifically.

**Comment by dragon3025** [comment]
What is TOP? I having the same problem.

**Comment by jaquadro** [comment]
TOP is "The One Probe".  But the actual mod at issue is "TOP Addons"

The issue report is actually a bit ambiguous though so if it's referring to just the visual stack vanishing, that's a bug fixed in SD 5.3.1.

**Comment by dragon3025** [comment]
That's cool, thanks.

**Comment by NicosaurusRex99** [comment]
@jaquadro so if i remove just the addons i will be fine?

**Comment by Nargath** [comment]
I had TOP Addons as well.
I believe the author put through a fix, and I've not seen this problem happen again

**Comment by NicosaurusRex99** [comment]
i removed it anyway

**Comment by jaquadro** [comment]
Yeah, a patch was merged in a few days ago and a new release probably put out.  Updating should make it safe again.
