### ISSUE TITLE
Actual Additions Rice Slimeball Comparability 

### ISSUE THREAD

**Issue by llloyd4** [jaquadro/StorageDrawers#555]
I was noticing that I can't make Packing Tape with the rice slimeballs from Actually Additions. Could you, please, add compatibility with them on this?

**Comment by codewarrior0** [comment]
Which version (and modpack) are you using? Packing Tape accepts any item from the oredict `slimeball`, which includes Rice Slimeballs and all the colored balls from TConstruct.

**Comment by llloyd4** [comment]
Umm, Unstable 1.12 1.05 heavily modified. I've been trying to keep the mods
up to date on my own to fix bugs and added a few extra.

**Comment by codewarrior0** [comment]
Since you have both JEI and AA, you can see both the oredict tags on the individual items and the "Accepts any:" tag in the crafting recipes. Can you double check that the Rice Slimeball is registered as `slimeball` and the Packing Tape recipe `Accepts any: slimeball`?

**Comment by codewarrior0** [comment]
I take it back.

This is a regression in StorageDrawers 5.x. The Packing Tape no longer uses oredict ingredients.

As a workaround, I think you can craft 9 Rice Slimeballs into a Slime Block, and then craft that again into 9 regular Slimeballs.

**Comment by jaquadro** [comment]
Oredict slime is back in 5.3.0

**Comment by llloyd4** [comment]
Sweet! Thank you!
