### ISSUE TITLE
Crossmod issue regarding compacting drawer

### ISSUE THREAD

**Issue by zlainsama** [jaquadro/StorageDrawers#562]
raoulvdberge/refinedstorage#1435

When emptying a unlocked compacting drawer, RS gets duped items, AE2 gets null?invalid? items.

Versions:
- refinedstorage-1.5.17
- appliedenergistics2-rv5-alpha-3
- StorageDrawers-1.12.1-5.3.0
- Chameleon-1.12-4.1.3

**Comment by jaquadro** [comment]
Fixed in 5.3.1.  I only tested RS, but I assume it probably fixes AE2, and AE2 was responding to the broken behavior in a different way.
