### ISSUE TITLE
Shift+Click and Shift+RightClick

### ISSUE THREAD

**Issue by rdaroba** [jaquadro/StorageDrawers#565]
Shift+Click and Shift+RightClick actually use the Sneak key binding and not the Shift key directly so if someone changes their Sneak movement key binding, that key will need to be used instead of Shift.

For instance, I change my Sneak key mapping to "z". To grab an entire stack, I must press z+Click instead of Shift+Click.

**Comment by jaquadro** [comment]
I updated the language in 5.3.1.
