### ISSUE TITLE
Botania Corporea System + Storage Drawers

### ISSUE THREAD

**Issue by syntax-error** [jaquadro/StorageDrawers#57]
When using Botania's Corporea Index to request items out of a drawer, if you request a full stack or greater, it only delivers a single stack of the item, and empties the drawer, even if you should have had items remaining beyond that one stack. If you request 63 or less, it works as expected.

Additionally, the item count appears to be counting up to one stack twice. I presumed that this is probably something akin to the corporea system's issue with JABBA, whereby the drawers have an outlet that only reports 1 stack of items, but, unlike JABBA, simultaneously also reports its entire contents.

I've posted this incompatibility on the Botania side of things, and Vazkii has replied that what I have presumed is pretty much right, and that she can't do much without making a special case.

Is there anything on your side that can ease this issue? Merely fixing the deletion of entire stacks of items would be a fine enough solution, bringing storage drawers to be in line with the limitations of JABBA when using corporea.

**Comment by jaquadro** [comment]
I didn't know Botania had something like this.

While I do have slot spaces reserved for reporting full inventory counts, they shouldn't actually be functional.  E.g., they should always be reporting that you cannot extract from them.  I will need to check that that's still the case, and see if Botania is honoring it.  I also can't rule out that there's just a plain bug somewhere...

Any time a transport system wants to deal with stacks larger than 64, either the system needs to work within the constraints of the inventory system and issue multiple requests, or special support will need to be written for deep storage inventories like this or barrels.  I export an API for this purpose.  JABBA piggy-backs off the DSU API from MFR.

**Comment by jaquadro** [comment]
Fixed in latest Botania.
