### ISSUE TITLE
Cannot Craft any StorageUpgrade

### ISSUE THREAD

**Issue by Anarchox** [jaquadro/StorageDrawers#572]
Hello,

i have the problem, that i can craft all Items but not the StorageUpgrade Items (2x,4x,8x,16x,32x)
I normaly play in survival mode, in creative the items are availble but also cannot craft it.

Using
Forge: 14.22.1.2485
StorageDrawers 1.12.1-5.3.2
Chameleon 1.1.2-4.1.3

**Comment by Brawnynn** [comment]
The recipe has changed from prior versions. I'm not sure when but it definitely left me confused when I came back.
The recipe is:
Stick | Stick | Stick
Iron | Template | Iron
Stick | Stick | Stick

Upgrade I uses Obsidian (this is also a change)
Upgrade II uses Iron
Upgrade III uses Gold
Upgrade IV uses Diamond
Upgrade V uses Emerald

Side note, is Obsidian really meant to be Upgrade I?

**Comment by jaquadro** [comment]
Oh yeah, the recipes did change, to cut the resource requirements in half.  Static documentation lying around may be out of date and I leave recipe documentation mainly to JEI now.

Obsidian was changed intentionally.  In modded MC especially, obsidian is a pretty trivial resource to renew, so there wasn't much point in the iron or gold tiers.  It might take you a couple more nights to get there, but then it doesn't matter anymore.

At the same time that obsidian was "nerfed", it did get a bonus effect to give your drawers obsidian-level blast resistance.
