### ISSUE TITLE
[1.7.10] Visual Glitch - Items hided 

### ISSUE THREAD

**Issue by NathanPB** [jaquadro/StorageDrawers#573]
Hello, i'm interacting StorageDrawers with Logistics Pipes (by Drawer Controller) and I got this inssue:
![2017-09-24_02 49 03](https://user-images.githubusercontent.com/18128642/30779879-ff8fdfce-a0d3-11e7-8225-73f486dac2d7.png)
This is not a problem with the resourcepack.

Thanks...

**Comment by NathanPB** [comment]
I'm idiot

**Comment by HeyZeer0** [comment]
I agree with u

**Comment by Eufranio** [comment]
same

**Comment by D4rknessKing** [comment]
nathan pls dont
