### ISSUE TITLE
Storage Drawers are missing their contents icons

### ISSUE THREAD

**Issue by Spydr331** [jaquadro/StorageDrawers#579]
This may be too specific a use case.

I recently grabbed a server world and saved it locally, on there I was using about 20 different 4 item drawers.  Earlier today the icons were on every drawer with no issue, but now the icons are all gone,  I can still focus on the drawer and see its contents but I cant cause the icon to appear. Tried taking things out and putting them back in but no luck.  

Any idea what would be causing this?

**Comment by mfriendc** [comment]
have you tried using the concealment key on it to see if it fixes the issue? maybe something weird is happening

**Comment by Spydr331** [comment]
so i turned off the game entirely and went back in and it was still happening, and then did it again and it worked.  i guess it worked itself out?

**Comment by codewarrior0** [comment]
Are you using Optifine? I've seen weird issues when locally playing a world that was originally a server world, and resolved them by removing Optifine.

**Comment by Spydr331** [comment]
I was just using the twitch launcher for skyfactory 3
