### ISSUE TITLE
Missing Mod

### ISSUE THREAD

**Issue by No-Fa** [jaquadro/StorageDrawers#600]
Every time I install the mod a message appears and it says that I am missing a mod.

**Comment by BrianEdmonds** [comment]
So you sensibly tried installing that mod, which didn't bother to name,
and the result was?

**Comment by 314kojioyama** [comment]
you need the Chameleon core mod for storage drawers. look it up on curse and download the version you need from the files list, it will say the version of Minecraft you are playing somewhere to the right in the list, that's the version you need.

**Comment by No-Fa** [comment]
Ok, thank you very much.

Sent from my iPhone

On Dec 22, 2017, at 2:21 PM, 314kojioyama <notifications@github.com<mailto:notifications@github.com>> wrote:


you need the Chameleon core mod for storage drawers. look it up on curse and download the version you need from the files list, it will say the version of Minecraft you are playing somewhere to the right in the list, that's the version you need.

**Comment by No-Fa** [comment]
Hello, I was looking for the chameleon core mod you mentioned but, unfortunately I did not find it. Is there anything else I can do?

Sent from my iPhone

On Dec 22, 2017, at 2:21 PM, 314kojioyama <notifications@github.com<mailto:notifications@github.com>> wrote:


you need the Chameleon core mod for storage drawers. look it up on curse and download the version you need from the files list, it will say the version of Minecraft you are playing somewhere to the right in the list, that's the version you need.

**Comment by 314kojioyama** [comment]
https://minecraft.curseforge.com/projects/chameleon/files go here. it is the chameleon mod versions. be sure to get the one you need for your minecraft version you are playing.
