### ISSUE TITLE
[Suggestion] Drawers should display quantity by default

### ISSUE THREAD

**Issue by AMartinie** [jaquadro/StorageDrawers#607]
I don't know if there's a legitimate reason behind this, and I don't see anything in the config to even allow you to change the default setting. I doubt there are many people who want to have to just out a key every single time they want to see the quantity of a new drawer. While itemstack is empty, display nothing. While not empty, display quantity. I decomped the mod and it seems pretty easy to commit. At the very least, I'd like the option to display quantity by default.

**Comment by jaquadro** [comment]
Performance (client-side) is the only reason really.  Drawers have a history of being spammed pretty heavily and it can add up.  Then again, I have the concealment key with the opposite default behavior.  It is at least worthy of an option, and easy to do.

**Comment by jaquadro** [comment]
This option will be included in the next release.

**Comment by AMartinie** [comment]
you're my hero. Appreciate it bud.
