### ISSUE TITLE
Enderman Heads Visible Through Everything

### ISSUE THREAD

**Issue by znxster** [jaquadro/StorageDrawers#621]
- Foolscraft2 (v2.7)
- Minecraft 1.10.2
- Storage Drawers v1.10.2-3.7.10
- p455w0rd's Things v1.10.2-2.2.32

When storing Enderman mob heads within a Storage Drawer they are visible through chests / blocks. This is specifically with Enderman heads, trying other mob heads (Creeper / Zombie / Skeleton) they do not do this. I guess the bug might be with p455w0rd's Things therefore?

See screenshot for demonstration: https://imgur.com/a/VHqje

Many thanks

**Comment by jaquadro** [comment]
If this only happens with the other mod present then sure.

But otherwise it's probably that the enderman heads set a funny render state and don't restore it, and I'm not watching to clean up after it.  There have been similar problems with other mob heads and items in the past.
