### ISSUE TITLE
ChiselsAndBits conflict

### ISSUE THREAD

**Issue by TechnicJelle** [jaquadro/StorageDrawers#629]
In my serverlog it says "[chiselsandbits]: Unable to determine blocks eligibility for chiseling" for some of the blocks in the mod.
I read up on the error (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49) and it seems it can't be fixed by @AlgorithmX2.
These are the blocks:
com.jaquadro.minecraft.storagedrawers.block.BlockDrawers attempted to load net/minecraft/client/particle/ParticleManager

**Comment by jaquadro** [comment]
Looks like this is a missing annotation.  Fix will be included in the next release.

**Comment by jaquadro** [comment]
Sorry, I waited longer than I intended to put out a release.  This fix is included in 5.3.6.
