### ISSUE TITLE
NullPointerException when CompactingDrawer is disabled

### ISSUE THREAD

**Issue by IcedReaper** [jaquadro/StorageDrawers#631]
Hello,

I get a NullPointerException when I disable the CompactingDrawer (compdrawers) in the StorageDrawers config. As soon as I enable it again MC starts again. Otherwise it crashes directly on startup.

Crash-Log: https://pastebin.com/8esakQ0X
MC Version: 1.12.2
Forge: 14.23.2.2624
Storage Drawers: 5.3.5

Thanks for looking into this issue and hopefully fixing it.
Cheers,
IcedReaper

**Comment by jaquadro** [comment]
This should be fixed in 5.3.6
