### ISSUE TITLE
Breaking a drawer from the front in creative doesn't break it

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#640]
When in creative, breaking a drawer from the front makes the breaking sound and makes breaking particles, but doesn't break the drawer. Breaking it from any of the other 5 sides works fine.

Minecraft 1.12.2 singleplayer
Forge 14.23.2.2629
Storage Drawers 5.3.5

**Comment by codewarrior0** [comment]
If the drawer could be broken from the front in Creative, how would you withdraw items from it?

**Comment by ghost** [comment]
Oops, yeah... haha, I derped. Sorry, issue should be closed.
