### ISSUE TITLE
Double-Right-Click on Drawer Controller does not update player inventory.

### ISSUE THREAD

**Issue by codewarrior0** [jaquadro/StorageDrawers#65]
Using version 1.3.9

After double right-clicking on the controller, all of the items it took still appear to be in the player's inventory. Clicking on one of the items, or opening a chest, updates the inventory.

**Comment by jaquadro** [comment]
Should be fixed in [1.4.0-alpha2](http://minecraft.curseforge.com/mc-mods/223852-storage-drawers/files/2235914).  After being bothered by this issue for months, I only now thought to go check JABBA.

**Comment by codewarrior0** [comment]
Looks fixed to me!
