### ISSUE TITLE
[1.12.2]Hardcore duping with drawers and bags(all)

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#654]
https://files.ilikepudding.de/whjvus5c3v.mp4

It works with all bags not only thermal

im playing on version 5.3.6

**Comment by JoeSGT** [comment]
Having the same issue with any bags type mods like IronBackpack/ Extra Utilities  Gold bag

**Comment by jaquadro** [comment]
Thanks I'll take a look this evening

**Comment by jaquadro** [comment]
Huh.  I had to watch that about 5 times before I got an idea what was going on.  Kind of like watching a magic trick.  I think the solution is to ensure items with stack-size 1 do not stack on break.

**Comment by codewarrior0** [comment]
My hunch was that the items' capabilities aren't being checked when deciding whether they're stackable.

**Comment by jaquadro** [comment]
I'm not sure I'm familiar with those capabilities.  In this case though, an item with a non-stackable capability really should report a stack limit of 1, so obeying that should be sufficient.

**Comment by jaquadro** [comment]
Fixed in 5.3.7.

Work's been exploding lately so I keep forgetting to check my issues list.  For these kinds of bugs feel emboldened to call me out on Twitter or Discord though.
