### ISSUE TITLE
Locked Drawers loose their locked item when looking inside them

### ISSUE THREAD

**Issue by ProxyPlayerHD** [jaquadro/StorageDrawers#664]
title says it, if you look inside a Locked drawer that has no items left (so it shows an item but has 0 of if inside) then it will delete that ghost item, which defeats the purpose of it being locked in the first place.

MC: 1.12.2
Forge: 14.23.4.2747
SD: 5.3.7

**Comment by codewarrior0** [comment]
Mind posting your mod list? A similar problem was found months ago that turned out to be the fault of TOPAddons, and the fault in that mod was promptly fixed.

**Comment by ProxyPlayerHD** [comment]
[Here](https://pastebin.com/m1Bmdbwb)

I wish Forge had a command where it just generates a text file with all mods listed alphabetically and with their version, basically what i did by hand except automatic.

**Comment by Daenara** [comment]
I have the same problem, though my items aren't deleted, they just aren't shown until I rejoin the server. Here is a copy of my modlist, if it is a mod problem it should narrow the problem down at least. 

Daenara
![image](https://user-images.githubusercontent.com/3619315/44862316-b6f07680-ac7a-11e8-82c2-a5ecffe8c74d.png)

**Comment by ProxyPlayerHD** [comment]
i also found out that they are not deleted but just invisible. trying to put other items in is very glitchy and relaoding the world fixes it and shows the locked item again until the drawer is again opened while empty

**Comment by codewarrior0** [comment]
It looks like the field names in [ItemStackHelper](https://github.com/jaquadro/StorageDrawers/blob/1.12/src/com/jaquadro/minecraft/storagedrawers/inventory/ItemStackHelper.java#L126-L129) aren't given with their obfuscated forms, which explains why this issue doesn't manifest in a dev environment. The resolution is probably to find the obfuscated names corresponding to those four field names, and replace the `ItemStack.class.getDeclaredField` and `setAccessible` calls with the respective calls to `ReflectionHelper.getPrivateValue`.
