### ISSUE TITLE
[Suggestion] Upgrade visual

### ISSUE THREAD

**Issue by DwarvenSteel25** [jaquadro/StorageDrawers#668]
Basically a simple idea I think, right now there isn't a ton of indication of how many/what kinds of upgrades are in a storage drawer, and yes you can look at the stack size and do the math or open the menu, but the point would be this would simply be slightly more convenient. 

I think the idea is too unrealistic to implement since the void upgrade already does almost this exact thing, so I assume the implementation of this, would be similar to that?

Btw sorry if this has been mentioned before, I did search the list before posting and I didn't see it,

**Comment by chimericdream** [comment]
I suggested almost the exact same thing in #617 along with a screenshot. If that's the same as what you're thinking, might not be bad to close this and comment there.

**Comment by DwarvenSteel25** [comment]
I knew I couldn't have been the first one to think of this idea, thank you very much I'll do just that.
