### ISSUE TITLE
InvertShift config option doesn't work

### ISSUE THREAD

**Issue by ZigTheHedge** [jaquadro/StorageDrawers#68]
Hey there! 
Awesome mod! Really! But I already got used to JABBA/Factorization functionality and tried to set "B:invertShift=true". But the Shift behavior seems to be stayed the same. I still have to Shift-click for getting a whole stack instead of just regular right-click. 
My current version is 1.3.7.

**Comment by jaquadro** [comment]
Could you try 1.4.0-alpha2?  http://minecraft.curseforge.com/mc-mods/223852-storage-drawers/files/2235914

I couldn't reproduce this when I tested it.  invertShift seems fine.  Have you checked its state in the options GUI?

**Comment by ZigTheHedge** [comment]
Just tried it in singleplayer and all works as expected. Is this a server-wide config?

**Comment by jaquadro** [comment]
Well, this setting really SHOULD be client-only.  I checked in a change, that will appear in 1.4.0, that should fix it.
