### ISSUE TITLE
Dark render of items

### ISSUE THREAD

**Issue by Sunekaer** [jaquadro/StorageDrawers#689]
Block like Stone, Cobblestone, Dirt renders without light in any drawers, but items like Rails, flowers, DE Cores doesnt have this problem.

Modpack: FTB Presents Stoneblock 2

No errors in log.
![image](https://user-images.githubusercontent.com/18720460/50730834-1691ed80-1157-11e9-91cc-789b6bbae29c.png)

**Comment by scotty9090** [comment]
Getting the same issue in Engimatica 2.

**Comment by TheVillain-Inc** [comment]
not sure why this was closed...I still get this problem. Its only doing it for 'blocks' not items. 

Rotten flesh, coal, ingots, diamonds are fine. 
Cobblestone, dirt, ores, wooden planks/logs however are affected. 

Not sure whats causing it, going away sometimes or looking at it from a different angle sometimes fixes it, or causes it to flicker. 


1.12, optifine.
