### ISSUE TITLE
Crash with Storage Drawers' Compacting Drawer and Minicolonies

### ISSUE THREAD

**Issue by pauloelr** [jaquadro/StorageDrawers#697]
As previous discussed here: https://github.com/ldtteam/minecolonies/issues/3443

There is a crash when trying to input an item on a compact drawer if you have Minicolonies installed together

**Comment by Fastjur** [comment]
Can confirm. Still having this issue: https://github.com/ldtteam/minecolonies/issues/3443

**Comment by jaquadro** [comment]
appears this was resolved on their end
