### ISSUE TITLE
Breaking storage drawers! 

### ISSUE THREAD

**Issue by tobyaskew1** [jaquadro/StorageDrawers#700]
So I’m an admin on a modded server that uses storage drawers. They are amazing, until someone accidentally breaks one. This is more of a suggestion than an issue, but I suggest maybe making it so if the drawers are locked they cannot be broken. The past month the server has crashed 3 times due to people accidentally breaking storage drawers with thousands of items in, resulting in a server rollback! I hope this is seen as I believe it would be really helpful and stop thousands of entities crashing the server!

**Comment by jaquadro** [comment]
The problem has been mentioned several times.  Maybe they should never drop items (implicitly always taped).  All solutions I can think of carry some flaw from a griefing standpoint, but in terms of accidents that might be best.

- Dropping all items: might crash the server, griefers can deliberately crash a server
- Keeping items in broken block: easy to steal lots of items, can more trivially carry lots of items
- Item drop limit: breaking drawers might void large numbers of items
- Locked drawers can't be broken: Not all drawers are locked, locking drawers can create impenetrable player barricades.

**Comment by codewarrior0** [comment]
For comparison, the Mass Storage blocks from GregTech 6 when broken will drop at most 512 items, voiding the rest. This is preferable to dropping all items since a crashed server usually results in lost items anyway.

The barrels from YABBA and the caches from Thermal Expansion retain all items when broken.

**Comment by jaquadro** [comment]
This design change has been made in the 5.4.0 release.  Drawers will keep their items and upgrades when broken.  The new behavior can be turned off in config, but it will be enabled by default.
