### ISSUE TITLE
Disable breaking Storage Drawers that have a massive amount of items while it isn't Taped

### ISSUE THREAD

**Issue by aaronhowser1** [jaquadro/StorageDrawers#706]
If a Drawer that isn't Taped breaks, it spews the items all over the ground. I just had to load a backup of my save because I broke a Drawer with several hundred stacks of Cobblestone in it. This would be very easy to abuse to grief servers, and is just a huge pain when done accidentally. I think you should make it so you can't break Drawers that have too many items in them to prevent this unless Tape has been used on it.

**Comment by Pultex** [comment]
Yeah there was one mod that had a condenser sphere, so when over a certain amount fell out of a chest it all turned into one item that was a black sphere.
When you picked it up all the stuff that could go into your inventory would and the rest stayed in the sphere.
Not sure what mod did that but would be nice to have that in this mod.

**Comment by aaronhowser1** [comment]
That was originally Equivalent Exchange 2 I think, and it's also in ProjectE

**Comment by jaquadro** [comment]
Is there any argument to be made for not just always dropping the drawer with its inventory still inside?  And ditch the packaging tape?

I thought there was some previous discussion about also capping what got dropped but it doesn't look like that was implemented

**Comment by jaquadro** [comment]
This has been addressed in 5.4.0 with a design change.  All drawers will keep their contents on breaking now (enforced by a default-on setting in the config).  You can still tape them, but it will be pointless.
