### ISSUE TITLE
Storage drawers setup problem

### ISSUE THREAD

**Issue by Xyrys** [jaquadro/StorageDrawers#71]
Hi,

Playing the regrowth pack.. Updated to your latest 1.4.0 version to try out the slaves.  Could you make it so the controller detects all drawers and slaves in the 24 x 24 area around the controller as long as they are connected via say the slaves ?? ie: use the slaves both as how they are designed.. Brilliant btw, and as a cable.

My intent was to create 2 separate banks of drawers replacing all my jabba barrels, and then have a series of pillars 3 high with super crafting frames on each face.  I can get the axis directly connected to the Controller working, but any to the left or right will not work.  This is of course keeping everything within the 12 block radius of the controller.  So you can make a cross shape 3 wide with the controller as the central block and it works fine with slaves running in all directions to connect all the drawers. 

However if you go further than 1 block out from the controller axis on the ends the controller will not see the blocks to connect to.

Thanks for your time,

Xy.

**Comment by jaquadro** [comment]
You may need to give me a screenshot; I don't completely follow.

The distance in 3D space is not as important as the shortest path between a block and a controller.  That is what is limited to 12 blocks.  So if you were to create a spiral out from the controller for example, you would not get very far away in terms of absolute distance.

While you can use slaves as a cable, and they are reasonably lightweight (compared to controllers), the wooden trim blocks do an even better job at being a cable.

**Comment by codewarrior0** [comment]
You could also say the controller's search area is like a diamond shape that fits inside a 25x25 cube.

**Comment by jaquadro** [comment]
Only if you lay out optimal paths.  But yes, that is theoretical bound.

**Comment by Xyrys** [comment]
The diamond shape explains what I am seeing.  If I get time I will post a picture of what I was trying to do.. Suffice it to say I ended up just making 3 banks of drawers each with a controller.  However if it was changed from a diamond to an actual 25x25x10(height) box, or if you could say link controllers that would be a fantastic addition.  Normally I would be using AE by now I must admit, but getting right into the whole storage drawers with super crafting frames..

I have run into a bug though.. Will post it in a new issue because it makes the game totally unplayable after about 10mins..  Although its not a memory leak per say.. more a log spamming leak..

**Comment by Xyrys** [comment]
Ok.. I see whats going on here.. Its a direct block limit rather than a range.  So if I want to hide the trims (which i tried and are awesome btw) and I go down 2 blocks then across 4 then up 2..  Thats 8 blocks not 4 as I was expecting since I thought it was within 12 blocks, not within and counting 12 blocks..

Is it possible to extend that range  ?  Since with the trims/slaves we can hide connections really easily.  Like pipes under the floor etc.  Not too big of course..  I am not looking for a pipe replacement, but If I could have one central controller and the walls lined with drawers  that would be awesome.

Also could the top face of the controller be made clickable for the double right click, so floor mounting would be more possible ???  Really love that feature.

**Comment by jaquadro** [comment]
The search code was changed in 1.4.6.  The controller will now find all drawers in a 25x25 cube centered on the controller as long as they have a connected path that's fully contained by that volume.  Path distance itself no longer matters.
