### ISSUE TITLE
[1.12.2] Omnifactory Tin has no Block/Nugget form - makes Ingot show in wrong field in compacting drawer

### ISSUE THREAD

**Issue by Ioandar** [jaquadro/StorageDrawers#720]
Omnifactory Tin has no Block/Nugget form 

This makes Ingot show in wrong field in compacting Drawer

StorageDrawers-1.12.2-5.3.8
Omnifactory 0.10

<img src="https://i.ibb.co/F6d4nGS/2019-06-19-13-44-54.png" alt="2019-06-19-13-44-54" border="0">

**Comment by jaquadro** [comment]
This actually isn't a bug.  The drawers don't have any discrete concept of blocks vs ingots vs nuggets.  Only reversible crafting patterns that follow a pattern for compressed items.

If the bug you're reporting is that it's not populating with tin blocks and nuggets from other mods, then it might be something weird with how the ore dictionary is setup.  Either the proper entries were not registered, or registrations are applied in a way that the mod can't safely determine equivalence.

**Comment by Ioandar** [comment]
okay, I just wanted to make sure it is not something in "my" beloved drawer mod :)

thanks for all the work you put in it! I love your drawer mod

I will check if it is something on omnifactory site. They changed quite a lot of recipes. Easy to have a typo. I close this here now
