### ISSUE TITLE
Items Flickering

### ISSUE THREAD

**Issue by Montero77** [jaquadro/StorageDrawers#724]
Hello!
I use the newest version of Storage Drawers for 1.7.10 with Forge, Ressourcepack and a Shader. It's irrelevant which Shader i use, the items in the Drawers are always flickering or just black shadows. The Ressourcepack is not the problem, without Shader everything is working fine.
I upload a screenshot so you can see what I mean:
![2019-08-14_22 47 31](https://user-images.githubusercontent.com/54121409/63055172-9e0dbf00-bee5-11e9-8c07-19cda1e1e26e.png)

Does anybody know, how to fix the problem? Just an other version or something in the settings?
Thank you!

**Comment by Montero77** [comment]
No solution?

**Comment by jaquadro** [comment]
Sorry, I don't have a solution for this.  The 1.7.10 rendering is immediate mode and I don't know how the shaders interact with it.
