### ISSUE TITLE
Crash With StorageDrawers on Server?

### ISSUE THREAD

**Issue by IchigoGames** [jaquadro/StorageDrawers#727]
when i add StorageDrawers i get this crash without it no crash it does not say the mod name in crash report but then i may be missing it. only happens on server.

Minecraft 1.14.4
Forge 28.0.93
StorageDrawers-1.14.4-6.0.0
Crash report https://pastebin.com/qVS5hR9x

**Comment by jaquadro** [comment]
Not really clear from the report, hopefully related to one of the other new server tickets.  Will try to sort out tonight.

**Comment by jaquadro** [comment]
Please see if 6.0.1 resolves this

**Comment by IchigoGames** [comment]
tested 6.0.2 seems to be fixed
