### ISSUE TITLE
[1.14.4-6.0.0] "Connection Closed - mismatched mod channel list" when joining server

### ISSUE THREAD

**Issue by KajesLorian** [jaquadro/StorageDrawers#728]
Minecraft Version: 1.14.4
Forge Version: 28.0.75
StorageDrawers-1.14.4-6.0.0

Mod installs and runs fine on client, mod installs fine on server, but unable to connect with server.

**Comment by henkelmax** [comment]
I have the same issue.
I am using Forge 28.0.101

**Comment by jaquadro** [comment]
No idea what that means but I'll dig into it tonight 🤔

**Comment by jaquadro** [comment]
Please see if 6.0.1 resolves this

**Comment by KajesLorian** [comment]
Client crashes upon startup.

"The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot get config value without assigned Config object present"

Crash Report: https://gist.github.com/KajesLorian/666d3a6908967491e13ef83091e1e5b5

Latest.log: https://gist.github.com/KajesLorian/19aef8310b961e8c4714c6371976d3e4

Debug.log: https://gist.github.com/KajesLorian/391b62b8e29d74afa8e7f85f8c204a56

**Comment by jaquadro** [comment]
Aww this horseshit again?  Really not digging the new config system.

Give 6.0.2 a try.

**Comment by KajesLorian** [comment]
That works, on both client and server. Thank you!
