### ISSUE TITLE
[1.14.4] Classloading Error on Dedicated Server

### ISSUE THREAD

**Issue by SilentChaos512** [jaquadro/StorageDrawers#729]
## Versions

- Storage Drawers 6.0.0
- Forge 28.0.100

## The Problem

A class in the mod is loading the `ISprite` class, which is client-only. Not sure which, the first mention is right after `BasicDrawerModel` is subscribed to the event bus (link to debug.log file below). While this does not cause a crash by itself, it does prevent many events from firing, so another mod can crash when trying to access game data that doesn't exist.

Can be reproduced with only Storage Drawers installed on a dedicated server.

## Links

- Log file: https://gist.github.com/SilentChaos512/d2a56a1d448e936b2b2740dc985bbab9#file-storage-drawers-debug-log-L125
- Discovered while working on [this issue](https://github.com/SilentChaos512/SilentGems/issues/400).

**Comment by jaquadro** [comment]
Damn, I even launched a debug instance but assumed all was well because it didn't crash.  Will take a look tonight.

**Comment by jaquadro** [comment]
Please see if 6.0.1 resolves this

**Comment by SilentChaos512** [comment]
Fixed in latest version, thanks.
