### ISSUE TITLE
[1.14.4] Must Remove Shield to Invoke GUI

### ISSUE THREAD

**Issue by Torhal** [jaquadro/StorageDrawers#732]
I'm not sure if this is a new issue or not since the 1.14.4 version is the first I've used, or if this is simply a limitation due to how shields function, but it's slightly annoying to have to remove the shield to show the GUI window (swapping obviously doesn't work since the main hand is no longer free).

**Comment by jaquadro** [comment]
It's standard behavior for having any item held in the off-hand.  When an item is held in the off-hand and you're sneaking, then block activation is bypassed (try opening vanilla GUIs when crouched and holding something, won't work either).

**Comment by Torhal** [comment]
Gotcha. I was hoping that wasn't a Minecraft limitation, but alas. Appreciate the info!
