### ISSUE TITLE
[1.14.4] WAILA Stack Limit Label

### ISSUE THREAD

**Issue by Torhal** [jaquadro/StorageDrawers#733]
Even with upgrades, the drawer will show `Stack Limit: 64 (x8)` in the WAILA tooltip.

**Comment by jaquadro** [comment]
As far as I can tell, the WAILA label is doing the right thing and taking the upgrades properly into account.

You did skirt into a bigger bug though, which is common slot calculation was not taking the configured base multiplier into account (which is 4 stacks, by default).

**Comment by jaquadro** [comment]
Check 6.0.1 and if the rendering looks wrong, please follow up with some specific examples/configurations.

**Comment by Torhal** [comment]
Ah, my mistake - I was looking at what I thought was a non-upgraded drawer and assumed the `(x8)` meant stack size with a limit of 8. I did a double-check and indeed, a non-upgraded drawer shows `(x1)` which I now know is the storage multiplier.

I'm glad I at least pointed you in the direction of an actual bug, though. :)
