### ISSUE TITLE
1.14.4-6.02 - Drawers can never again be stacked, once placed

### ISSUE THREAD

**Issue by elowanut** [jaquadro/StorageDrawers#735]
## Versions
**Storage Drawers**: 1.14.4-6.0.2
**Forge**: 1.14.4-28.0.102

## Expected Behavior
Starting with a stack of drawers, place one down, then break it. The (still empty) drawer should re-stack with its empty brethren.

## Actual Behavior
Once placed in the world, drawers are thenceforth un-stackable, I assume because they are "auto-packing-taped" by default, and this doesn't take into account their being completely emptied.

## Steps to Reproduce the Problem

1. Load up a forge modded version of minecraft with the Storage Drawers mod.
2. Start a fresh world, place down two drawers of your choice.
3. Break them with the appropriate tool, note their lack of stacking.

**Comment by jaquadro** [comment]
Should be fixed in 6.0.3, for any new broken blocks.
