### ISSUE TITLE
1.14.4-6.0.3 - Compacting Drawer is missing several formerly available recipes

### ISSUE THREAD

**Issue by elowanut** [jaquadro/StorageDrawers#738]
## Versions

- **Storage Drawers**: 1.14.4-6.0.3
- **Forge**: 1.14.4-28.0.104

## Expected Behavior

While using the Compacting Drawer, place in stack of gowstone dust. The expected result is that the drawer now contains a stack of the glowstone dust, and displays the icons for both dust and the full glowstone block on its front face.

## Actual Behavior
With a number of items, the Compacting Drawer behaves as a regular (non-compacting) drawer, where it used to allow conversion between different forms. The missing recipes are all the "semi-cheating" variety -- items that generally convert, but not as easily as dropping them into the crafting grid. What I've found to be missing is: glowstone, quartz, clay, brick, nether brick, snowball, nether wart, melon. All of these were present in 1.12.2. Conversion between Ice types would be nice, as well, although these weren't available in 1.12.2, since the crafting recipes didn't exist at the time.

I have tried (unsuccessfully) to add some of these recipes back in via the configuration files, using this format:

    S:compactingRules <
        minecraft:clay, minecraft:clay_ball, 4
        minecraft:glowstone, minecraft:glowstone_dust, 4
        minecraft:quartz_block, minecraft:quartz, 4		
    >

This doesn't seem to do anything.

## Steps to Reproduce the Problem

1. Load up a forge modded version of minecraft with Storage Drawers
2. Start a fresh world, place down a compacting drawer.
3. Right click with one of the above-mentioned items, notice they don't provide alternates on the compacting drawer interface.

**Comment by jaquadro** [comment]
Addressed in 6.0.5.  The set of 8 special rules are enabled again by default and can be toggled in config. 

Setting your own rules in config is supported again.  Syntax is basically the same, but it's in a TOML file instead of whatever syntax configs used to use.  There's an included example.
