### ISSUE TITLE
1.14.4-6.0.3 Storage Drawers don't break properly from the front, on creative

### ISSUE THREAD

**Issue by elowanut** [jaquadro/StorageDrawers#739]
## Versions

- **Storage Drawers**: 1.14.4-6.0.3
- **Forge**: 1.14.4-28.0.104
- **Creative** ONLY

## Expected Behavior

When breaking a storage drawer in creative, a single left click should break (and destroy) the drawer.

## Actual Behavior
The drawer can be broken as expected from all directions, *except from the front face.* When breaking from the front face, the breaking animation takes a slight, but noticeable amount longer, and then shows a "breaking" animation, while leaving the drawer in place. You cannot break any drawer from the front, no matter how hard you try. Hits from the other 5 faces break it as expected. This affects all drawers, but not Controllers, Slaves, or Trim.

## Steps to Reproduce the Problem

1. Load up a forge modded version of minecraft with Storage Drawers.
2. Start a fresh world in creative mode, place down any drawer.
3. Left click on the face of the drawer, notice it cannot be permanently broken. Then click on any other face, and break it normally.

**Comment by jaquadro** [comment]
Not a bug.  Drawers have never been able to be broken from the front in creative.  It's deliberate and allows them to be usable in creative mode.  Otherwise you could never extract from them.

**Comment by elowanut** [comment]
That makes sense, I suppose you would want to be able to stock them in creative. The only (minor) issue I can see would be in removing a middle drawer from a bank of drawers. I suppose you'd have to dig around to the back of the bank, or go through the drawers on the edges of the bank beforehand.
