### ISSUE TITLE
1.8-2.0.0alpha1 crashes server on startup

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawers#74]
"crashes on startup looking for missing class using Forge b1398 Dedicated Server"
server crash report: http://pastebin.com/EwmUwLPV
fml server latest log: http://pastebin.com/k4XeXzUg

**Comment by jaquadro** [comment]
Can you give this version a try? http://minecraft.curseforge.com/mc-mods/223852-storage-drawers/files/2236860

**Comment by kreezxil** [comment]
Great news that resolved the issue and I can now use the drawers on the server.

What's the eta on the controller module? Also, can I used pipes with the drawers as they are now? I ask because I have hopper ducts installed and at least two mods with item ducts, neotech and powerAdvantage.

**Comment by jaquadro** [comment]
It should be ok to use pipes (well, what few choices you have).  Controller will come back after merging the latest 1.7 changes back in.  Maybe a week.

**Comment by kreezxil** [comment]
Cool 😎 

-----Original Message-----
