### ISSUE TITLE
Interactive faces on (some tested) drawers are left/right swapped (6.0.1/2/3)

### ISSUE THREAD

**Issue by SkyeMors** [jaquadro/StorageDrawers#740]
Comparing the interactions and visual cues between any 2x2 and Compacting drawers (along with all screenshots provided on the mod page), it appears and functions as if the left and right interactive halves of all faces of drawers are swapped. Meaning that on the 2x2, 
Visually:
1 | 2
3 | 4
Interacts like:
2 | 1
4 | 3
and on the compacting drawers visually:
1 (block)
2 (ingot) | 3 (nugget)
but interactively:
1 (block)
3 (nugget) | 2 (ingot)

Blocks tested were the Compacting Drawers and Oak Drawers (2x2), though I believe it is the same for all blocks. They technically all work as intended, just have a flipped interactive face for some reason. Still entirely functional, if I remember right=left.

**Comment by jaquadro** [comment]
This one is annoying.  Several people have reported this.  Some say it's the E/W faces.  Some say it's the N/S faces.  I don't see it at all.

I have a vague suspicion this actually has to do with the map quadrant you're in (whether your X or Z coordinates are positive or negative), so I'll do a little more digging around that.

**Comment by jaquadro** [comment]
Can confirm slots are swapped on +x and -z quadrants.
![2019-09-12_01 17 41](https://user-images.githubusercontent.com/852988/64756013-3ace7700-d4fb-11e9-9418-a1eefd4158a7.png)

**Comment by jaquadro** [comment]
Got to the bottom of it, fixed in 6.0.4

**Comment by SkyeMors** [comment]
Can confirm- as of the current version, there is no face interaction issues- good job and thanks!!!
