### ISSUE TITLE
[1.14.4] can't craft upgrade

### ISSUE THREAD

**Issue by TheBlackReverand** [jaquadro/StorageDrawers#745]
Hello,

I use minecraft 1.14.4, StorageDrawers 6.0.5 and forge 28.1.0.

I try craft upgrade but I can't.
I can craft storage et upgrade template but no upgrade.

If I try with minecraft 1.12 and StorageDrawers 5.4.0 all work fine.

Thanks.

**Comment by ghost** [comment]
Same here.
I use minecraft 1.14.4, StorageDrawer 6.0.5 and forge 28.1.24.
Can't craft upgrades in crafting table.

**Comment by QuantumToasted** [comment]
I seem to be able to craft upgrades fine, but cannot use them at all. I'm not sure how to use them on drawers but I tried right-clicking, sneak-right-clicking, putting them in the crafting table, etc, to no avail. On 1.14.4, for 28.1.56, SD 6.0.5

**Comment by jcardii** [comment]
I had a similar problem, and then I discovered to shift-click on a placed drawer with both hands empty to open the upgrade UI. If this does not solve your problem, my apologies.
--
jcii

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15

(Upgrades could always be placed by opening the GUI (via empty hand), but once again they can be applied with right-click)
