### ISSUE TITLE
Dungeons, Dragons, and Space Shuttles mod pack - Framed drawers void items

### ISSUE THREAD

**Issue by Maikar23** [jaquadro/StorageDrawers#748]
The mod pack was updated recently so that when you break a storage drawer it keeps it's items with out needing to apply packing tape 1st. This works with all the drawers, but framed drawers. When breaking a framed drawer it drops 1 item and voids the rest. Though using packing tape on the drawer 1st till functions like it should.

**Comment by Semi0ne** [comment]
[1.12.2 Dungeons, Dragons and Space Shuttles]

Same modpack, same issue. Normal drawers keep items, framed drawers void them.

**Comment by F1ndail** [comment]
Project Ozone 3, 3.1.44, same issue.  Reported over there as well:

[https://github.com/Cazadorsniper/PO3/issues/671](url)

**Comment by jaquadro** [comment]
Fixed in latest release of 1.12.
