### ISSUE TITLE
[1.14.4] Crash when loading client with forge 28.1.39!

### ISSUE THREAD

**Issue by Gbergz** [jaquadro/StorageDrawers#752]
Title^ Game/Client crashes when trying to load mod on Forge ver: 28.1.39, whilst it worked fine on 28.1.20!

MC: 1.14.4
Forge: 28.1.39
Mod-Version: 6.0.5

Crash-log: [GistGithub](https://gist.github.com/Gbergz/86f4c17bbe6445b549962407722d6162)

**Comment by CursedWolf** [comment]
Same crash on Forge 28.1.68
Mod Version 6.0.4 Works on newest Forge :D

**Comment by hm-ysjiang** [comment]
In your crash report, L228, it says that the status of forbidden_arcanus-1.14.4-1.1.jar is ERROR
Maybe backup your world and remove the mod to check if the game starts properly?

**Comment by SystemtechCA** [comment]
I am having the exact same issue :

Crash Log : [https://github.com/SystemtechCA/Logs/blob/master/crash-2019-10-28_20.15.55-client.txt](url)

**Comment by SystemtechCA** [comment]
Ok i see in my dump, as you mentioned to Gbergz, that i had 2 other mods in error state.
I removed those and it seems to have fixed my issues. 
Thank you.
