### ISSUE TITLE
Cannot get drawer controller back

### ISSUE THREAD

**Issue by Old-Man-D** [jaquadro/StorageDrawers#753]
When I try and move a drawer controller with a pickaxe, it just breaks and doesnt drop a block.  Is there a special tool I am supposed to use now?  I am using version 6.0.5 on forge 28.1.26

**Comment by melbellrocks** [comment]
Having the same behavior.  The drawer controller doesn't drop when I break it.

Storage Drawers - version 6.0.5

**Comment by RamenNoodles** [comment]
Drawer Controller and Controller Slave as well as all Trim do not drop when broke.  Used a diamond pickaxe and diamond axe.

**Comment by trevorjd** [comment]
Problem still exists with 6.0.5 and Forge 28.1.104

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
