### ISSUE TITLE
Log Spamming 1.4.0

### ISSUE THREAD

**Issue by Xyrys** [jaquadro/StorageDrawers#76]
Hi,

http://pastebin.com/4hE5qMYq

After you connect to game (happens in both SMP and SP), this spam starts and doesn't stop until I destroy the controllers.  The controllers in question are in the floor under the banks of drawers (I have 3 banks).  They are not connected to each other. 

If you have no reporting process open then it doesn't affect your game at all.  I only noticed because the other thread reached 5GB in size and was lagging out the game process.

It also is only throwing the error on the client side.  My server is running without any problems and game otherwise has a tick of 5ms.

This did not occur under version 1.3.4.  At least I never saw it or noticed it..

Xy.

**Comment by Xyrys** [comment]
Ok.. I found what causes this.
F7 spawn locations...  Which is from NEI I believe.

It is just the controller.. Checked every other block by placing one in the world and pressing F7 produces no spam or lag.  Placing the controller in the world starts the spam as soon as you press F7.

Xy.

**Comment by Xyrys** [comment]
Just as further info.. 

With say the FTB launcher log window open (which is a separate Javaw process) this spam causes the memory used by that process to increase to over 1.5GB in under 30 seconds, and was using 17% of the total processing..  (That's on a 4Ghz i7 with 32Gb memory)

Main minecraft process starts to lag horribly after only that long.

I checked 1.3.4 and it also exists in it.

Easy to reproduce.. get regrowth pack.  new game.. place controller on ground. press F7..

**Comment by Xyrys** [comment]
Just as an aside.. Its easily ignored since you can close the other offending process down and therefore it "isn't" happening..  It has no effect on the game.  I played a few hours today while testing with the console closed and there is no FPS decrease or lag etc.  The messages are just going to NULL.

However it did lead me to wonder as to the extent of spammed errors messages in logs that the normal user of say FTB would not realise is causing their whole computer to eventually lockup due to the rampant increase in load and memory usage.  Add in the hard drive thrashing its doing trying to write 1.6GB in under 30 seconds to the log file as well.

Game was almost impossible to play after about 3 mins while leaving the console window open.  Once closed, instant fixed game.

**Comment by jaquadro** [comment]
I can check if the TileEntity exists, and I will make that change.  Strictly speaking though, Optifine or whatever is calling that method where a block doesn't exist, and is assuming there won't be a problem with that.  They could probably handle it better.

**Comment by jaquadro** [comment]
Should no longer be a problem in 1.4.3.
