### ISSUE TITLE
Drawers with identical contents don't stack unless placed at the same coordinates.

### ISSUE THREAD

**Issue by TheDeviantCrafter** [jaquadro/StorageDrawers#771]
Breaking a storage drawer keeps its content now, but the broken items almost never stack, even when they have the same number of the same item inside and are made of the same material. This is a little annoying.

Looking at the NBT string of the item with `/ct hand`, it looks like coordinates are being stored in the NBT data:

```
<storagedrawers:basicdrawers>.withTag({material: "oak", tile: {Mat: "oak", Upgrades: [], Cap: 256, x: -236, y: 64, ForgeCaps: {"nuclearcraft:capability_default_radiation_resistance": {radiationResistance: 0.0}}, z: 508, id: "storagedrawers:basicdrawers.1", Dir: 5 as byte, Drawers: [{Item: {id: "rustic:log", Count: 1 as byte, Damage: 1 as short}, Count: 16384}]}})
```

`x: -236, y: 64, z: 508` are the coordinates that the block was placed. Placing the drawer somewhere else and then breaking it again changes these NBT tags to match the new location.

Placing two drawers with identical contents, upgrades, and materials DO stack if they're both placed at the same coordanates. This leads me to believe that storing the coordinates in the NBT data is the issue. This information doesn't appear to be important since it's overwritten when the block is placed again, so I'd recommend deleting those tags when the block is broken.

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
