### ISSUE TITLE
1.14.4 Incompatibility with Optifine rendering

### ISSUE THREAD

**Issue by TehFoxFire** [jaquadro/StorageDrawers#775]
[crash-2019-11-10_14.31.34-client.txt](https://github.com/jaquadro/StorageDrawers/files/3828987/crash-2019-11-10_14.31.34-client.txt)

**Comment by jaquadro** [comment]
This was probably not related to Optifine.  In your crash log, Building Gadgets errored during load, and causes other things to crash as Forge shuts itself down.
