### ISSUE TITLE
[1.14.4] Failure to check block state can be cast to BlockDrawers

### ISSUE THREAD

**Issue by noobanidus** [jaquadro/StorageDrawers#778]
Relevant line: https://github.com/jaquadro/StorageDrawers/blob/1.14/src/main/java/com/jaquadro/minecraft/storagedrawers/block/tile/TileEntityDrawers.java#L168
Crash report: https://gist.github.com/duely/84643675136dbcac6b1a6cbdfa08bb5b
Forge version: 28.1.90
Storage Drawers version: 6.0.5

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
