### ISSUE TITLE
[1.14.4] Trim doesn't drop block when broken

### ISSUE THREAD

**Issue by Ozzymud** [jaquadro/StorageDrawers#779]
1.14.4
StorageDrawers-1.14.4-6.0.5

Playing on the Devcraft server, dark oak trim (didn't test others) did not drop it's block when broken with an iron axe.

**Comment by Mantarri** [comment]
I'm having the same issue with spruce trim, I assume that the trim blocks don't have the drops configured correctly, I've also noticed that the drawer controller slave does not drop itself.

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
