### ISSUE TITLE
Tesselating Block in World 1.8-3.0.0 Alpha 4

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawers#78]
I used a teleport device to get back to my base and the client crashed with the following:
Client Crash Report: http://paste.ee/p/QoSvh
Client FML Latest: https://paste.ee/p/20aXF

The dedicated server reported nothing at all in it's console and also did not crash.

**Comment by jaquadro** [comment]
My biggest concern is that this is triggered by the TileEntity missing...

**Comment by jaquadro** [comment]
You can see if this build resolves your immediate problem: http://hocuspocus.taloncrossing.com/rii/StorageDrawers-1.8-2.0.0-alpha4.jar

**Comment by kreezxil** [comment]
Did anything change in that as I was already using that version and the file sizes matched.

**Comment by jaquadro** [comment]
Yes, I did not advance the version number for this, and the change was minor.

**Comment by kreezxil** [comment]
It doesn't "seem" to be an issue any longer.

**Comment by kreezxil** [comment]
It is most definitely not an issue with version 1.8-2.0.1. Thanks very much. :100:
