### ISSUE TITLE
Upgrading drawers requires opening the GUI

### ISSUE THREAD

**Issue by NielsPilgaard** [jaquadro/StorageDrawers#780]
I don't know if this is intended / changed in 1.14 but currently to upgrade drawers you have to shift right click them to open the GUI to insert the upgrades instead of just right clicking them with the upgrade in hand.

### Versions
- Forge 1.14.4-28.1.103
- Minecraft 1.14.4
- StorageDrawers-1.14.4-6.0.5

Original issue: https://github.com/NillerMedDild/Enigmatica4/issues/197

**Comment by jaquadro** [comment]
A lot of things moved around in 1.14 so small details like this were unintentionally dropped.  The 1.14 port was never fully finished, although I am going back and fixing a few things in that version with the 1.15 port addressed.

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
