### ISSUE TITLE
Crash when accessing Storage Drawer through Crafting Station

### ISSUE THREAD

**Issue by NielsPilgaard** [jaquadro/StorageDrawers#787]
Crashlog and video can be found here: NillerMedDild/Enigmatica4#240

First reported by @Darkere to the Crafting Station issue tracker, where the issue was found to be in Storage Drawers, please see this comment for details: https://github.com/Tfarcenim/crafting-station/issues/41#issuecomment-570332679

- craftingstation-2.1.3c.jar
- StorageDrawers-1.14.4-6.0.5.jar
- forge-28.1.109

**Comment by jaquadro** [comment]
I believe this is actually on the crafting station side, and the way that it handles inventory is not compatible with SD blocks.  They need to change how they handle inventory or find a way to exclude blocks like SD.

**Comment by jaquadro** [comment]
Handled on crafting station's side
