### ISSUE TITLE
Items got deleted when breaking the drawer

### ISSUE THREAD

**Issue by jk1895** [jaquadro/StorageDrawers#788]
I broke two full, non-upgraded framed drawers (two to be sure) and the items are gone. I lost over 4000.
Config is set to: keepContentsOnBreak=true

Version 1.12.2-5.4.0
Forge 14.23.5.2847

**Comment by darchitectlp** [comment]
Echoing this problem. Exact same version of Storage Drawers and Forge. Playing Enigmatica 2: Expert, if that helps. Thanks.

**Comment by UnduGT** [comment]
Same Problem with same Version in Stoneblock 2.

**Comment by jaquadro** [comment]
Sounds like it might be specific to framed

**Comment by jaquadro** [comment]
Fixed in latest release of 1.12
