### ISSUE TITLE
Duplication bug with Steve's Workshop

### ISSUE THREAD

**Issue by Silwing** [jaquadro/StorageDrawers#79]
There is a duplication bug with storage drawers. I have reproduced the bug with the newest version of Steve's Workshop (0.5.1) and Storage Drawers (1.4.4) from Curse Voice and nothing else installed. I do not know whether this is a bug in Storage Drawers or Steve's Workshop so I will post this issue on both issue trackers (Vswe/Production#26)

The setup is very simple. A production table with auto-transfer upgrade and a workbench module with auto-crafting upgrade. Besides the production table place a Drawer Controller from Storage Drawers and connect one or more drawers to the controller (placing them so at least one drawer touch the controller and all drawers touch at least one other drawer). Set the production table to auto-transfer to the side where the controller is placed. Place any crafting recipe in the workbench modules crafting grid and place enough items for the auto-crafter to craft at least one item. Now watch that item show up in EVERY input of the connected drawers and still staying in the output slot of the crafting module. Anything that can be crafted in a normal crafting table is then easily dupe-able. By placing multiple Transfer Capacity upgrades in the production table the duplication speed is increased as 6 upgrades will put up to a stack of items (assuming a stack is available in the output slot of the workbench module) in every connected drawer. The drawer has to be empty, otherwise nothing will happen. But with any mod capable of transferring items you can extract the items from the drawer controller and new items will then be placed in the drawers. I have attached screenshots of my setup.

![2015-05-09_13 28 03](https://cloud.githubusercontent.com/assets/186144/7549990/451f9c6e-f64f-11e4-9dcc-3aab9f42dee1.png)
![2015-05-09_13 27 38](https://cloud.githubusercontent.com/assets/186144/7549992/451feb6a-f64f-11e4-91c9-488a094846e1.png)
![2015-05-09_13 27 48](https://cloud.githubusercontent.com/assets/186144/7549989/451f32ec-f64f-11e4-89f2-0e018ed7cf14.png)
![2015-05-09_13 27 54](https://cloud.githubusercontent.com/assets/186144/7549991/451fe91c-f64f-11e4-8d8e-f2e259d0eb1f.png)

**Comment by jaquadro** [comment]
This looks like my bug, which I guess is a good thing because the other project doesn't look too active.  I'll have a release out in a little bit.

**Comment by jaquadro** [comment]
That said, there is an issue preventing the table from inserting into drawer inventories that will be more difficult for me to solve.

**Comment by jaquadro** [comment]
Fixed in 1.4.5 (including the bit about item insertion I mentioned).

**Comment by Silwing** [comment]
That was a quick fix! Thank you very much :)
