### ISSUE TITLE
Clear saved item with quantity 0 from locked drawer

### ISSUE THREAD

**Issue by retnikt** [jaquadro/StorageDrawers#792]
If I lock a drawer with items in it, then unlock it and take out the items, I can't put any other items in it except that one type. There seems to be no way to clear the saved item which has a quantity of 0. How can I do this?

**Comment by jaquadro** [comment]
Incidentally this has been bugging me for a few weeks and I have a fix queued for 1.14+.  You haven't specified which version you're playing on though.

Workaround: place same item back in, unlock drawer, remove item.

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15

**Comment by SirPrimrose** [comment]
Is there a chance this can also be fixed for the 1.12.2 version, or is that no longer supported?
