### ISSUE TITLE
[1.15.2] Recipe Optimization

### ISSUE THREAD

**Issue by NielsPilgaard** [jaquadro/StorageDrawers#796]
Hello!

I would like to suggest that you use the tag `forge:chests/wooden` as the chest ingredient in your recipes, so things like Ender Chests and Mekanism Personal Chests aren't valid options. Seeing JEI cycle through very different blocks is a bit misleading, imo. 
This is just a personal preference of course, feel free to reject it :)

**Comment by jaquadro** [comment]
Thanks.  The data pack system is still a thing I'm adjusting to along with all the nuances of categorization.

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
