### ISSUE TITLE
[1.14.4] Unknown condition type: minecraft:item_exists

### ISSUE THREAD

**Issue by Drunkender** [jaquadro/StorageDrawers#798]
When loading a world with storage drawers the storage keys do not exist because of errors.

https://pastebin.com/GdhUGKGA

Edit
Forge: forge-1.14.4-28.2.1-universal.jar
Storage Drawers: StorageDrawers-1.14.4-6.0.5.jar

**Comment by jaquadro** [comment]
They're soft errors.  It's because those items aren't actually re-added yet but the old recipe files are still present.

**Comment by jaquadro** [comment]
Fixed in latest 1.14 and 1.15
