### ISSUE TITLE
[1.12] Very odd visual behaviour, possible loss of items

### ISSUE THREAD

**Issue by NielsPilgaard** [jaquadro/StorageDrawers#801]
I'm experiencing some really odd issues with `StorageDrawers-1.12.2-5.4.1`, all drawers behave.. well odd. I made a video of it: https://youtu.be/OpeGXJnYpKI 

Latest log: https://gist.github.com/NillerMedDild/55d4e9100254fb80e87b70cc8498f778

**Comment by jaquadro** [comment]
That's really very odd.

There's nothing in the 5.4.1 changeset that touched anything that could be implicated in that, that I know of.  It's not something I'm seeing in my test world.

Does it happen in single player or multiplayer?  With or without mods?  It looks like an "extreme" version of the rotated drawer problem that has been reported in the past, where a client tile was getting deleted, or in this case maybe overwritten?  Are the items there if you log out of the world and back in?

**Comment by NielsPilgaard** [comment]
Hopefully this issue only exists in my test world then, I'll have another look this evening :)

**Comment by NielsPilgaard** [comment]
The issue did not persist through restarts, must've been a desync of some sort I guess, sorry about that.
