### ISSUE TITLE
[Request] Negative/space restriction upgrade

### ISSUE THREAD

**Issue by pjfranke** [jaquadro/StorageDrawers#81]
I suggested a similar idea to ProfMobious regarding Barrels, but thought I should throw it your way too now that I've come to realize how nice the drawers are, especially with the Controller block and Slave controllers.

There are times where it's nice to have an item in a drawer/barrel style inventory, where you can add and remove items without "opening" it like a chest.  However, I may only want so many of that item available, i.e: 1, 2, 4 stacks, etc.  Not the full capacity of a 1x drawer (32 stacks) or barrel (64 stacks).  The compact 2x and 4x drawers get closer, but you still need to block off the other drawers with other items, and if in an automation setup, filter those items to prevent them being pulled.

Therefore, in addition to the current capacity-increasing upgrades, I'd like to see a capacity decreasing upgrade.  Possibly made with metal/diamond/emerald/obsidian nuggets, instead of ingots/gems.  I haven't thought it through enough to know if a relative capacity would be best, or an exact capacity.  That is, 1/2, 1/4, 1/8, 1/32 vs 1 stack, 2 stacks, 4 stacks, etc.  Given that the drawer block capacities are 2, 4, 8, then 32 stacks per drawer, I suppose the fraction makes more sense.  It would allow the oddity of a 1/32 capacity upgrade being able to reduce the compact 2x2 to holding only 4 items per drawer.  Strange, mostly useless, but someone might find a use for a restriction that low.

**Comment by jaquadro** [comment]
It's a very strange kind of request, but I can sort of understand where it might be of use.

Storage Drawers exists because I wanted something more compact for holding, for example, computer parts which I would only have small numbers of.  Now, whether the drawers can store a lot or not is fairly irrelevant, except that the status indicator upgrades are useless if you plan on keeping small numbers.  Outside of WAILA integration, there are no other mechanisms for gauging the amount of items in drawers.

I'll consider the idea.

**Comment by Daenyth** [comment]
> whether the drawers can store a lot or not is fairly irrelevant

Specifically when using the drawers with Automagy's Inventarium, the drawer takes up storage slots based on its maximum capacity whether you use it or not

**Comment by jaquadro** [comment]
My thoughts came back to this feature after the Automagy integration was written, but I haven't got around to it yet.  I think there's a potential snarl at the lower end, but I'm not certain yet.

**Comment by uecasm** [comment]
I've made PR #419, which implements part of this. :grin: 

My motivating case was to use a 2x2 drawer as a way to store exactly one stack of 4 different items, and use a redstone upgrade to indicate when full.  (There's precious few mods that allow you to store a single stack, and AFAIK none of them let you generate a signal when full/empty.)

The implementation lets you raise this to 2 stacks or more if you like (via storage upgrades), but not to reduce it to partial stacks.

**Comment by pjfranke** [comment]
Thank you, it seems this has now been pulled in with https://github.com/jaquadro/StorageDrawers/commit/8dd83d36b53295c4499d362f00dbf36a9f3e4e93

I've tested now, and this works VERY satisfactorily.  Partial stacks was not a desire, but instead would have been a side effect of one method of implementation.

Dropping the base-size to a single stack, then allowing normal stack upgrades to increase this to 2, 3, 5, 8, 13, or any integer of stacks from a combination of those (i.e: 4, 6, 7 9-12, 14-31) is absolutely sufficient.  Thanks for the PR @uecasm, and thanks to @jaquadro for accepting it.  This issue can now be closed.

**Comment by kolatra** [comment]
You can close your own issue with the button next to the comment button. :)

**Comment by pjfranke** [comment]
Weeell, yeah, I knew that, since right next to the "Comment" button was the "Close and comment" button.  Usually I've seen the developers close an issue when they git push the commit (or accept the PR) that fixes it, as well as have a "Fixes issue #81" sort of message.  Oh well.

**Comment by jaquadro** [comment]
Closing issues is fine.  I have a habit of leaving them hanging open when I really shouldn't, anyway.
