### ISSUE TITLE
Front Texture of drawers gone

### ISSUE THREAD

**Issue by DasFantatier** [jaquadro/StorageDrawers#815]
Minecraft Version: 1.15.2
Forge Version: 31.1.0
Mod Version: StorageDrawers-1.15.2-7.0.2.jar

I placed all available drawers to show them in a room.
I noticed the spruce half 1x2 drawer front went missing when placing. (see screenshot)
![2020-04-03_17 31 15](https://user-images.githubusercontent.com/62701156/78379292-6a95b700-75d2-11ea-88f7-2a84867abfb2.png)

I tested it in single player and placed a few of them, some fronts are gone, some not.
Then i did the same on our server, creative and survival mode.
![2020-04-03_17 32 22](https://user-images.githubusercontent.com/62701156/78379383-91ec8400-75d2-11ea-8d13-93b1da14ca00.png)

Sometimes the front disappears when placing another block in front of the drawer.
I tested this with normal blocks, placing them one block in front of the half drawers - and the front was gone. 
![2020-04-03_17 39 27](https://user-images.githubusercontent.com/62701156/78379476-b7798d80-75d2-11ea-96cd-f95c385d7244.png)

This happens to all drawers i think - well it just can be seen on the half drawers.
Strangely this one spruce 1x2 half drawer on the wall haven´t had any block in front of it, the front was gone without any block in front of it.
After i set some blocks in front there, the drawer front face was back to normal.

Now all of them are looking fine again, but this bug is strange.

**Comment by dopuke** [comment]
same for me !

**Comment by Eldresh** [comment]
Seeing this bug on 1.16.5 Storage Drawers version 8.3.0, but the other player (connected via lan) does not. The only difference between us is I use Optifine (version: OptiFine_1.16.5_HD_U_G8) and BSL shaders and he does not, so I suspect it has something to do with either shaders or Optifine.

**Comment by jaquadro** [comment]
This is now fixed 1.16-onwards.  It may be different then what Eldresh is mentioning.
