### ISSUE TITLE
Compacting Drawer multiple recipes problem

### ISSUE THREAD

**Issue by BakermanLP** [jaquadro/StorageDrawers#82]
Hello,

I've got a small "problem". I want to use compacting drawers to compress (via ExtraUtilities recipes) Cobblestone, Gravel, DIrt and Sand. This is working for Cobblestone, Gravel and Dirt, but not for sand. There is a recipe to make 2x2 Sand to Sandstone and a 3x3 recipe to make compressed sand.

Can I fix that via mt script? Is there a way to force 3x3 recipes?

Thanks for reading

Michael (aka BakermanLP)

**Comment by jaquadro** [comment]
Not currently, but I've been meaning to expose it via MT.

**Comment by BakermanLP** [comment]
Would be a great addition. Thank you

Justin Aquadro <notifications@github.com> schrieb am Mo., 11. Mai 2015
15:46:

**Comment by jaquadro** [comment]
New MineTweaker API has been added in 1.4.6.  Adding a new compacting tier will replace any existing registrations using the given upper or lower item.  Registrations (should) override any inferred conversions from examining the recipe table.  Sand->Sandstone wasn't one of those - it was an explicit registration at the behest of my co-admin.

mods.storagedrawers.Compaction.add(<upperItem>, <lowerItem>, 4); // Third param is conversion rate; must be 4 or 9.

**Comment by BakermanLP** [comment]
Thanks, will try it today

Justin Aquadro <notifications@github.com> schrieb am Di., 12. Mai 2015
06:32:

**Comment by BakermanLP** [comment]
Thanks, works like a charm! For documentation issue and for other people:
mods.storagedrawers.Compaction.add(<ExtraUtilities:cobblestone_compressed:14>,<minecraft:sand>,9);

**Comment by Kenshij** [comment]
In an old drawer mod, it changes this in game, without config manipulation. It respects the place where you put the item. If you put a 1x compressed sand into the left down slot of the drawer, it searches from their possible recipes, so you end up that the 1x compressed sand will sit in the left down slot and sand became the input in the right down slot.
