### ISSUE TITLE
Storage Drawers blanking when locked and run out of items

### ISSUE THREAD

**Issue by Ratomas** [jaquadro/StorageDrawers#832]
Minecraft 1.15.2 
Forgecraft 31.1.77 
Storage Drawers 7.0.2
ModPack FTB Omnia 1.3.0

Every time the storage drawer runs out of an item when locked it blanks out like it is unlocked. It used to stay locked for that item only and now it just blanks and doesn't accept anything else until unlocked.

**Comment by dmtryzhkv** [comment]
why is this closed? i am having the same issue in 1.16.1, in a custom modpack. item image stays for a bit but it disappears after a while or when chunk isn't loading anymore. this ruins most automation stuff as i have to place items in the appropriate inventories all over again every time i log in.
