### ISSUE TITLE
Visual bug with grass

### ISSUE THREAD

**Issue by Reyls** [jaquadro/StorageDrawers#85]
StorageDrawers-1.7.10-1.4.7
http://imgur.com/m0fQnD4

**Comment by jaquadro** [comment]
Yes... I'm not sure how I'll solve this yet.  Changing the GL to fix the grass coloring also breaks the lighting, and I'm not sure how to fix it.

**Comment by Reyls** [comment]
I am not a pro, but could you copy parts of code from JABBA for icon rendering?;)

**Comment by jaquadro** [comment]
Jabba doesn't shade the blocks, which can make them more difficult to distinguish.

**Comment by jaquadro** [comment]
I did ultimately get to the bottom of this.  Grass finally renders with correct colors in 1.7.0, along with leaves and other grass-influenced blocks.
