### ISSUE TITLE
[Suggestion] Add config option to set render distance on drawers

### ISSUE THREAD

**Issue by Andyghandi** [jaquadro/StorageDrawers#853]
Hi, I love this mod very much. I love to easily interact with my items, which this mod does very well. But I am always running into lag issues when populating my world with drawers. This idea may have been presented before, but adding some kind of option to set render distance to the icons displayed on the drawers would be very useful I think. And maybe add a smarter way to not render the items if not looking directly at them (Like through a wall or the backside of the drawer). As big and as wildly popular this mod has been throughout modded Minecraft, this feature would make a great appearance. Many thanks for considering this idea. 

Im playing the modpack MC.eternal on 1.12.2

**Comment by jaquadro** [comment]
As of the latest 1.16 version, the blocks will avoid rendering labels if you're behind the block.  Vanilla also culls the blocks already if they're outside your view frustum.  That's probably about as good as we can easily get.

The latest version also has a render distance option now.
