### ISSUE TITLE
Client Log file Spammed "Unable to resolve texture due..."

### ISSUE THREAD

**Issue by ClaudiusMinimus** [jaquadro/StorageDrawers#854]
Starting at line 953 of my client log file (https://paste.ee/p/Ut9AM) a variation of the following is spammed to line 3388.
> [m[33m[14:25:04] [Render thread/WARN] [minecraft/BlockModel]: Unable to resolve texture due to reference chain trim->trim in storagedrawers:block/half_drawers_orientable

MultiMC version: 0.6.12-develop-1365
OS Linux Mint: 19.3
Java: 1.8.0_212, using 64-bit architecture
Minecraft: 1.16.1
Forge: 1.16.1-32.0.44
StorageDrawers-1.16.1-8.0.0

**Comment by drakray** [comment]
I too have this on 1.16.3, Forge 42, StorageDrawers-1.16.3-8.2.1.jar, some line with immersiveengineering though

EDIT: I'm using Faithful x32 and Faithful 3D, if it can help

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/122636547-73778900-d0af-11eb-9cab-1b68c1f683d4.png)
[latest.log](https://github.com/jaquadro/StorageDrawers/files/6295962/latest.log)

From #943

**Comment by leagris** [comment]
Same issue in 1.16.5
Forge 36.2.2
StorageDrawers-1.16.3-8.3.0

Using standard default textures
No rendering modification (no Optifine)

Log spam is still really annoying
