### ISSUE TITLE
Storage Drawers and Automagy - shows 2x quantity

### ISSUE THREAD

**Issue by robbcrg** [jaquadro/StorageDrawers#87]
Using storage Drawers with Automagi Inventarium shows 2x (double) the quantity that actually exists. Applies to all storage drawers and the controller.

I will also file a bug report with Automagi ....

**Comment by Ikabodo** [comment]
Tuhljin has talked about this issue in the [minecraft forum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2125369-tc4-addon-automagy-automation-and-logistics?page=38#c756).

"For the next release, I've added a new Inventarium contents provider class for ISidedInventory that uses canExtractItem (as well as getAccessibleSlotsFromSide). However, it will only show up to a stack's worth of an item from a single set of drawers even when multiple stacks are stored, even if the Inventarium is reading from a drawer controller. That's just how those blocks are set up.

I believe StorageDrawers has an API that could be used to get the true amounts but -- IIRC -- last time I looked, it seemed complicated and I didn't have time to go into it. I'll probably look at it again eventually, but if anyone wants it in faster and feels up to it, then feel free to build upon the Automagy API to tie it in (or PM me with some example implementation maybe if you've worked with SD's API before)."

**Comment by jaquadro** [comment]
I commented in the thread with some examples to look at for the API (though implementing the API itself is not necessary to avoid the double-accounting issue).

**Comment by jaquadro** [comment]
It looks like this is actively being worked on: https://github.com/Tuhljin/Automagy/blob/master/src/main/java/tuhljin/automagy/api/example/storagedrawers/ProviderForStorageDrawers.java

I will keep an eye on it.

**Comment by robbcrg** [comment]
Thank you, Thaumcraft, Automagy and Storage Drawers is a wonderful, and 
I think balanced combination.

**Comment by Ikabodo** [comment]
I've just installed both the mod-updates. I'll do some testing tonight. At first glance it seemed to work well. 

By the way. This type of collaboration between mod-authors is amazing. Great work!

**Comment by jaquadro** [comment]
All outstanding issues should be resolved with Automagy 0.24.1.

**Comment by robbcrg** [comment]
Updated both mods and confirmed it is working now. This is fantastic thank you both so very much.
