### ISSUE TITLE
Collision bug

### ISSUE THREAD

**Issue by Majestyc2k1** [jaquadro/StorageDrawers#88]
Ref: compact basic drawers 2X2

When these drawers are one block above the floor, the player can actually enter the drawers and take damage, similar to gravel falling on you. This does not happen if the drawer is on the floor, or two blocks above the floor.

**Comment by jaquadro** [comment]
1.7 or 1.8?

**Comment by Majestyc2k1** [comment]
1.8, sorry

**Comment by Majestyc2k1** [comment]
Where you able to replicate the bug?

**Comment by jaquadro** [comment]
Yeah, I was able to reproduce it, though I don't fully understand why at the moment.  It will probably be fixed by the next release.

**Comment by jaquadro** [comment]
Fixed in 2.1.3
