### ISSUE TITLE
No status upgrade I and II available on 1.15.2 7.0.1

### ISSUE THREAD

**Issue by N445** [jaquadro/StorageDrawers#882]
I don't have any craft available of status upgrade I and II on 1.15.2 7.0.1

why ?

How can I know the remaining free space

**Comment by krustymk** [comment]
second

**Comment by MAXIS05** [comment]
did they find a solution? I am on version 1.16.5 and the same thing happens, I also saw that the Trim blocks are not there

**Comment by jaquadro** [comment]
These have been brought back in the latest 1.16!
