### ISSUE TITLE
Placing any block in front of Half Drawers 2x2 creates an x-ray view

### ISSUE THREAD

**Issue by boyestrous** [jaquadro/StorageDrawers#883]
When placing blocks in front of half drawers 2x2, which only use the back-half of a block (horizontally), the drawer turns into an x-ray viewer. 

This is true for full blocks and also for other half drawers (when trying to make a corner).

![image](https://user-images.githubusercontent.com/13008046/96590681-effd6200-12ab-11eb-8b5f-4beb66b6b4bf.png)
![image](https://user-images.githubusercontent.com/13008046/96590707-f4c21600-12ab-11eb-9b5c-b7cc04a6cb0f.png)

**Comment by kcranky** [comment]
This is similar to issues 952, 944, 929, 924, 815

Because https://github.com/jaquadro/StorageDrawers/issues/815 is the oldest, could you please close this issue and add any useful information there?

**Comment by jaquadro** [comment]
Fixed in neweset 1.16 release
