### ISSUE TITLE
[1.16.3] Upgrades unable to be crafted

### ISSUE THREAD

**Issue by BadgerClaws** [jaquadro/StorageDrawers#886]
**Version 8.2.1 of Storage Drawers for 1.16.3 of Minecraft**

While the recipes for the upgrades appear in JEI, and you can even make the upgrade template, you cannot create the actual template.  [https://i.imgur.com/sOlLihf.png](Screenshot).

**Comment by kcranky** [comment]
Unable to reproduce
Are you still having the issue?
Have you tried on 1.16.5?
What other mods do you have installed?

**Comment by jaquadro** [comment]
This must have been fixed at some point, or it was never an issue .. could have been a pack or mod conflict issue
