### ISSUE TITLE
Suggestion: Add drawer recipes to the minecraft ricepe book when the player first obtains a chest

### ISSUE THREAD

**Issue by ThreePhases** [jaquadro/StorageDrawers#890]
I recently tried putting together a new modpack (for 1.16.3) without JEI, instead relying on Minecraft's now built-in recipe book. Unfortunately, I found out that StorageDrawers does not support this yet.

I'm not very familiar with the necessary mechanics but some kind of unlock criterium would have to be defined; for the basic drawers, I suggest when the player first crafts/obtains a chest. Other recipes could be unlocked once the player crafts/obtains their first drawer.

This would also be required before the mod can be used together with  the gamerule doLimitedCrafting.

Love the mod, though! Keep up the good work!

**Comment by jaquadro** [comment]
These have been added as of the latest 1.16 version
