### ISSUE TITLE
Storage Drawers allow light to pass

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawers#90]
No bug report files to give.

Place torch behind any storage drawer, turn out all other lights, enjoy your new storage drawer lantern.

**Comment by jaquadro** [comment]
They aren't solid blocks, so they will pass light.  Much like sunlight pouring through your roof made of stairs.

**Comment by jaquadro** [comment]
Seems I didn't keep up with vanilla changes and those things don't pass light anymore.  I will update the full blocks to block light, but the half-drawers will continue passing full light.

**Comment by jaquadro** [comment]
Full fix in 1.7.10 and 1.8 now.  All drawers block the passage of light.
