### ISSUE TITLE
Missing "Invert sneak" option in Minecraft version 1.16.4

### ISSUE THREAD

**Issue by Susjin** [jaquadro/StorageDrawers#900]
Playing the new DW20 pack, I found out that the ingame config for almost all the mods is disabled, so I looked for the config file in the Instance folder, found it, but there ins't a option for changing de sneak+leftclick action =(

I don't know if that is intended or not, but it's very frustrating everytime I click on a drawer

**Comment by jaquadro** [comment]
Looks like this was fixed in some version of 1.16 because it is there presently, in storagedrawers-client.toml
