### ISSUE TITLE
Storage drawer tanks performance wehn looking at it

### ISSUE THREAD

**Issue by Ingemaru** [jaquadro/StorageDrawers#906]
Storage drawer tanks performance wehn looking at it. If i look away i have 360~400 fps if i look at it i have 90 Fps.

**Comment by BloodshotPico** [comment]
Depends on how many of them you have in a specified area, it's the same with all entities, for example if you have a bunch of chests in an area it's also going to drop frames.

**Comment by Yourname942** [comment]
> Depends on how many of them you have in a specified area, it's the same with all entities, for example if you have a bunch of chests in an area it's also going to drop frames.

how many does this imply causes issues? (a dozen, a hundred, etc?) Thank you.

**Comment by pkkid** [comment]
I have a wall that's 10x4 with 4x4 drawers. So it's rendering 160 items across 40 blocks. It drops my fps from 110fps when looking away down to 30fps when looking at it. I never messed with a mod before, but I'm curious if some sort of client side caching of the front of the drawers could be done. Maybe only re-render the front face every 1s or something seems like it could greatly increase performance or eliminate the fps drop all together.

**Comment by jaquadro** [comment]
Caching the item labels would be great, but is outside of what I think I could figure out what to do with the render system.

As of the latest 1.16 version, it will be smarter about not rendering labels that you can't see (eg you're standing behind the block), and there is a render distance option in the client config.  Neither of these will be particularly useful for the "big wall of drawers" setup though.

There's also the concealment key that was added back earlier this year, though it's a clumsy band-aid at best.
