### ISSUE TITLE
Display bug : flying items 

### ISSUE THREAD

**Issue by sharle4** [jaquadro/StorageDrawers#916]
Hi, 
I have a diplay bug when i put some items in my 2*2 oak drawers : some items put are flying, as seen in the Screenshot below.
The mod version is 8.2.1 for 1.16.3
If i remove these items from the drawers, the flying items disapear or are replaced by others items already in the drawers.
Many thanks,
Charles 

![javaw_PnQVEC4UFe](https://user-images.githubusercontent.com/41182776/105022163-b6bec480-5a49-11eb-95e8-b339daee5add.png)

EDIT 1
This attached video is interesting : if I try to break the drawer, the progressive fracture of the bloc is displaying in the sky with the items.
https://youtu.be/i4yBAz8nX-k

EDIT 2
I noticed that some items display their clone in the sky wherever you put them, and some items are working fine without this bug. The buggy items i noticed are : any kind of torch, spider eye, glowstone dust, magma cream, sea lantern, ender eye, fireball, prismarine cristals, blaze rod and shroomlight

EDIT 3
Noticed something new : all bugy items are displayed in the sky in the same 4 location, see the video below. The number of items printed with the quantify key is also visible in the sky. If you go  upper than the buggy slots in the buggy drawer it dissapear and if you go further it dissapear too.
https://youtu.be/rm-jw5TQKYE

**Comment by CarliToes4** [comment]
This attached video is interesting : if I try to break the drawer, the progressive fracture of the bloc is displaying in the sky with the items.
https://www.transfernow.net/ddl/storagedrawers

**Comment by sharle4** [comment]
Soluce : it was my ressource pack :(
(New Default +)
