### ISSUE TITLE
Placing two half drawers against each other lets you 'wallhack'

### ISSUE THREAD

**Issue by FreneticScribbler** [jaquadro/StorageDrawers#924]
Like so: ![2021-01-30_21 46 40](https://user-images.githubusercontent.com/3331837/106410328-89571b00-643a-11eb-9bf2-e9281bdce402.png)

Version 8.2.2

**Comment by kcranky** [comment]
This is similar to 952, 944, 929, 883, and 815

Because https://github.com/jaquadro/StorageDrawers/issues/815 is the oldest, could you please close this issue and add any useful information there?

**Comment by jaquadro** [comment]
Fixed in newest 1.16 release
