### ISSUE TITLE
[1.16] Half-Drawers cull when there's a block in front of them, even though they themselves aren't full blocks

### ISSUE THREAD

**Issue by aaronhowser1** [jaquadro/StorageDrawers#929]
![image](https://user-images.githubusercontent.com/15698722/108619400-414c6800-73ea-11eb-86bd-f268fb516d35.png)

This is using `StorageDrawers-1.16.3-8.2.2`

**Comment by aofsupporter** [comment]
I noticed that this only happens when the drawer is facing west or south (player facing east and north to place the drawer).  Additionally, it culls the top face of whatever block it's on top of.

**Comment by kcranky** [comment]
This is similar to 952, 944, 924, 883, 815

Because https://github.com/jaquadro/StorageDrawers/issues/815 is the oldest, could you please close this issue and add any useful information there?
