### ISSUE TITLE
[Minor] Compacting draw logic is backwards

### ISSUE THREAD

**Issue by 04Slash** [jaquadro/StorageDrawers#931]
> List of rules in format "domain:item1, domain:item2, n".
> Causes a compacting drawer convert n of item1 into 1 of item2.

The config mentions it takes n of item1 and turns it into 1 of item2. In practice, "minecraft:oak_planks, minecraft:oak_wood, 4" turns 4 oak_planks into 16 oak_wood when it should be turning 4 oak_planks into 1 oak_wood.

![](https://i.imgur.com/FympMPG.png)

**Comment by Ackmard** [comment]
There's already a rule by default for clay, just follow that and it should work.

**Comment by 04Slash** [comment]
The problem isn't that I'm not able to make the mod do what I want. The issue is that the format mentioned in the config is wrong. Either the config should be changed to accurately reflect the proper format or the code should be changed to accurately reflect the config's description.

**Comment by kcranky** [comment]
This is the same as https://github.com/jaquadro/StorageDrawers/issues/917 
Do you mind closing this issue and adding your comment there?

**Comment by 04Slash** [comment]
That issue report explains the issue well enough. I can just close this. Thank you.
