### ISSUE TITLE
getInventoryName returns null

### ISSUE THREAD

**Issue by MatthiasMann** [jaquadro/StorageDrawers#94]
The drawer controller's getInventoryName currently returns null but should return a string which can be translated into a user displayable name.

**Comment by jaquadro** [comment]
The controller has no UI.  Is this for WAILA display purposes?

**Comment by codewarrior0** [comment]
I think it's for something like an ME Interface/Storage Bus.

**Comment by MatthiasMann** [comment]
When right clicking an EnderIO item conduit it will list the possible destination where items can be inserted.
This feature uses StatCollector.translateToLocal(inv.getInventoryName()) which will print "Chest" or "Furnace" for the vanilla tiles.

**Comment by jaquadro** [comment]
Quick test with AE2 shows it's using block names on the interface and not custom / inventory names.

Anyway fixed in 1.5.5 and tested with EnderIO.  Controllers and drawers alike will support anvil renaming as well.
