### ISSUE TITLE
Unable to craft upgrades.

### ISSUE THREAD

**Issue by MysticJona** [jaquadro/StorageDrawers#941]
We can craft the Upgrade template and only the upgrade template. But when trying to craft the upgrades we put in the recipe and nothing happens. We are using version 1.16.3 - 8.2.2

**Comment by kcranky** [comment]
Do you have any other mods installed?

**Comment by kcranky** [comment]
This seems to be related to https://github.com/jaquadro/StorageDrawers/issues/886
You are both running 1.16.3
Could you close this issue and add any other relevant information on that one?

**Comment by jaquadro** [comment]
Can't reproduce in the current version of 1.16.  Maybe it was a pack or mod conflict problem.  The recipes themselves also changed at some point to be a bit cheaper so that could be the issue if you weren't taking the recipe from JEI.
