### ISSUE TITLE
Log spam "Unable to resolve texture due to reference chain trim->trim in storagedrawers:block/full_drawers_orientable"

### ISSUE THREAD

**Issue by aaronhowser1** [jaquadro/StorageDrawers#943]
![image](https://user-images.githubusercontent.com/15698722/114383123-cdf5e580-9b52-11eb-9e5a-c16be19e3f7d.png)
It shows up 1236 times in my latest.log, after doing nothing but loading a world.

[latest.log](https://github.com/jaquadro/StorageDrawers/files/6295962/latest.log), too big for pastebin

**Comment by kcranky** [comment]
This is the same issue as https://github.com/jaquadro/StorageDrawers/issues/854
Please close this one and contribute there
