### ISSUE TITLE
Front of Half Drawers becomes invisible whenever a block is in front of it

### ISSUE THREAD

**Issue by niraqw** [jaquadro/StorageDrawers#944]
The front face of any Half Drawer doesn't render whenever a block is placed in front of it. 
![2021-05-12_03 51 12](https://user-images.githubusercontent.com/22210045/117963581-6b207700-b2d5-11eb-9fda-15ba425fd724.png)

This is in Storage Drawers 8.2.2 on 1.16.5 with Forge version 36.1.16.

**Comment by kcranky** [comment]
This is very similar to 952, 929, 924, 883, 815

Because https://github.com/jaquadro/StorageDrawers/issues/815 is the oldest, could you please close this issue and add any useful information there?

**Comment by jaquadro** [comment]
Fixed in newest 1.16 release
