### ISSUE TITLE
"status upgrade" 1.16.5 

### ISSUE THREAD

**Issue by MAXIS05** [jaquadro/StorageDrawers#950]
In version 1.16.5 there are no "status upgrade"? because they don't appear in the jei

**Comment by vizthex123** [comment]
Do you mean the redstone upgrades? They're all there - min, max, and regular.

Try searching "redstone" perhaps?

**Comment by MAXIS05** [comment]
If it is one of the redstone updates, but 1 is missing, in other versions I saw that there is an update that turns on a light in the chest when it is full or similar

**Comment by aneuhold** [comment]
Seems like there was an older mention of this as well: #882. Also having the same issue!

**Comment by jaquadro** [comment]
These have been brought back in the latest 1.16!
