### ISSUE TITLE
DrawerItemHandler returns slot limit for N+1 drawer

### ISSUE THREAD

**Issue by Equinox-** [jaquadro/StorageDrawers#951]
DrawerItemHandler#getSlotLimit does not account for the virtual slot=0, causing it to return the limit for the N+1 drawer.

This line should be using `slot - 1` instead of `slot`.
https://github.com/jaquadro/StorageDrawers/blob/e97b885da327379ef9851711923453d47d1a37f2/src/main/java/com/jaquadro/minecraft/storagedrawers/capabilities/DrawerItemHandler.java#L153

**Comment by jaquadro** [comment]
Thanks, this oversight is now fixed in the latest 1.16 release
