### ISSUE TITLE
See-through storage drawers bug

### ISSUE THREAD

**Issue by Aurum208** [jaquadro/StorageDrawers#952]
I placed a Jungle Half Drawer 2x2 in front of another Jungle Half Drawer 2x2 and the back one gliched out and became see-through.

**Comment by kcranky** [comment]
This is similar to 944, 929, 924, 883, 815

Because https://github.com/jaquadro/StorageDrawers/issues/815 is the oldest, could you please close this ticket and add any useful information you have to that issue (mod version, game version, additional mods, etc)?

**Comment by jaquadro** [comment]
Fixed in 1.16
