### ISSUE TITLE
[1.16.5 Suggestion] Add support for the nether woods, warped and crimson.

### ISSUE THREAD

**Issue by vizthex123** [jaquadro/StorageDrawers#954]
Title. It would be quite nice to have nether wood drawers.

**Comment by kcranky** [comment]
This is the same as https://github.com/jaquadro/StorageDrawers/issues/946
Please close this issue and comment on that one if you have anything to add.

**Comment by jaquadro** [comment]
Added in newest 1.16

**Comment by vizthex123** [comment]
noice, thanks
