### ISSUE TITLE
[Suggestion] Upgrade to keep 1 of an item/set an item for a drawer.

### ISSUE THREAD

**Issue by Cubly** [jaquadro/StorageDrawers#961]
Would be nice if you could either apply an upgrade that kept 1 of an item in a drawer or if you could set a drawers item so no other items could be inserted. This would be very useful when using Storage Drawers alongside other mods via the controller, it would pull all items but would not pull the last item from a drawer, allowing you to keep the drawers organised in anyway you wish.

**Comment by kcranky** [comment]
If you lock the draw with the item you wish to keep in there, you will get this behaviour. The locked draw will maintain its item, even if the count drops to 0

**Comment by Cubly** [comment]
Had no idea, assumed it would lock the drawer to prevent input/output completely.
Thanks!
