### ISSUE TITLE
Typo in loot entry

### ISSUE THREAD

**Issue by CodeGordon** [jaquadro/StorageDrawers#966]
I don't think this causes any actual issues in-game, but still something that should probably be resolved at some point.

https://github.com/jaquadro/StorageDrawers/blob/1294050fd5eb13d7e3afb91eb4f760d0591bc6c4/src/main/resources/data/storagedrawers/loot_tables/blocks/controller_slave.json#L2

**Comment by jaquadro** [comment]
Fixed, thanks
