### ISSUE TITLE
xray 1.16.5

### ISSUE THREAD

**Issue by ChlorideNotSalt** [jaquadro/StorageDrawers#979]
![2021-12-04_21 28 18](https://user-images.githubusercontent.com/59537574/144723745-80bed5f7-1e02-4bae-ad41-8415214dde7b.png)
Basically, when you put a block in front of the storage drawer (not sure if it works with other ones) you get xray

**Comment by jaquadro** [comment]
Thanks, fixed in 8.3.1.
