### ISSUE TITLE
Drawers have no harvest tool (1.18)

### ISSUE THREAD

**Issue by lamoyrl90** [jaquadro/StorageDrawers#982]
Just as the title says, Storage Drawers don't have a harvest tool in this version. Breaking with an axe or pickaxe takes the same amount of time as breaking by hand, although they do still drop the drawer with correct NBT.

Storage Drawers 10.0.0
Minecraft 1.18.1
Forge 39.0.5

**Comment by jaquadro** [comment]
Yeah this is actually fixed in dev, so it'll be in the next release

**Comment by jaquadro** [comment]
Fixed in latest release
