### ISSUE TITLE
Storage Drawers not tagged for 1.16.5

### ISSUE THREAD

**Issue by Darinth** [jaquadro/StorageDrawers#990]
The 1.16 version of storage drawers is not tagged as compatible with 1.16.5 which prevents installation in custom modpacks (at least easily, there's gotta be a way to force curseforge to do it... but my efforts thus far haven't been successful)

**Comment by jaquadro** [comment]
It looks correctly tagged to me.  What version does CF think is latest?

**Comment by Darinth** [comment]
My apologies, either there was something weird going on with CF when I was working on the pack that day or this was user error (probably the latter...) as I can now find it in the curseforge client and it shows up on the curseforge site with 1.16.5 versions that are compatible going back a very long time.
