### ISSUE TITLE
No framing table 1.16.5

### ISSUE THREAD

**Issue by StephJ2Fan** [jaquadro/StorageDrawers#996]
I am playing Cuboid Outpost(1.16.5 minecraft) and it has both Compacting Framing drawers and Storage drawers, but there is no framing table available? Was the framing table part of the Storage drawers originally?

**Comment by hulapyk** [comment]
Same issue right now on 1.18.1
I can't seem to find the framing table anywhere. I've got Armor Blocks mod which creates armors from various mod blocks, including Storage drawers, and the recipe for a helmet is the same as the table using wood trims. I have however also installed a mod to see if other recipes are available using the same recipe, but it doesn't show anything else for this recipe, only the helmet, no table.

**Comment by moon-st0ne** [comment]
i have no framing table or framed drawers at all in 1.16.5

**Comment by agriasrex** [comment]
No framing table in Create: Above and Beyond on 1.16.5 either.

**Comment by ArnauGames** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/framed-compacting-drawers
